#ifndef STEAMKIT_TYPES_WORKSHOP_FILE_TYPE_H
#define STEAMKIT_TYPES_WORKSHOP_FILE_TYPE_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum sk_workshop_file_type {
    SK_WORKSHOP_FILE_TYPE_FIRST = 0,
    SK_WORKSHOP_FILE_TYPE_COMMUNITY = 0,
    SK_WORKSHOP_FILE_TYPE_MICROTRANSACTION = 1,
    SK_WORKSHOP_FILE_TYPE_COLLECTION = 2,
    SK_WORKSHOP_FILE_TYPE_ART = 3,
    SK_WORKSHOP_FILE_TYPE_VIDEO = 4,
    SK_WORKSHOP_FILE_TYPE_SCREENSHOT = 5,
    SK_WORKSHOP_FILE_TYPE_GAME = 6,
    SK_WORKSHOP_FILE_TYPE_SOFTWARE = 7,
    SK_WORKSHOP_FILE_TYPE_CONCEPT = 8,
    SK_WORKSHOP_FILE_TYPE_WEB_GUIDE = 9,
    SK_WORKSHOP_FILE_TYPE_INTEGRATED_GUIDE = 10,
    SK_WORKSHOP_FILE_TYPE_MERCH = 11,
    SK_WORKSHOP_FILE_TYPE_CONTROLLER_BINDING = 12,
    SK_WORKSHOP_FILE_TYPE_STEAMWORKS_ACCESS_INVITE = 13,
    SK_WORKSHOP_FILE_TYPE_STEAM_VIDEO = 14,
    SK_WORKSHOP_FILE_TYPE_GAME_MANAGED_ITEM = 15,
    SK_WORKSHOP_FILE_TYPE_CLIP = 16,
    SK_WORKSHOP_FILE_TYPE_MAX = 17
} sk_workshop_file_type_t;

bool sk_workshop_file_type_is_supported(sk_workshop_file_type_t type);

#ifdef __cplusplus
}
#endif

#endif