#ifndef STEAMKIT_STEAM_HANDLERS_STEAM_USER_CALLBACKS_H
#define STEAMKIT_STEAM_HANDLERS_STEAM_USER_CALLBACKS_H

#include "steamkit/steam/callbacks.h"
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum sk_eresult {
    SK_ERESULT_OK = 1,
    SK_ERESULT_FAIL = 2,
    SK_ERESULT_NO_CONNECTION = 3,
    SK_ERESULT_INVALID_PASSWORD = 5,
    SK_ERESULT_LOGGED_IN_ELSEWHERE = 6,
    SK_ERESULT_INVALID_PROTOCOL_VER = 7,
    SK_ERESULT_INVALID_PARAM = 8,
    SK_ERESULT_FILE_NOT_FOUND = 9,
    SK_ERESULT_BUSY = 10,
    SK_ERESULT_INVALID_STATE = 11,
    SK_ERESULT_INVALID_NAME = 12,
    SK_ERESULT_INVALID_EMAIL = 13,
    SK_ERESULT_DUPLICATE_NAME = 14,
    SK_ERESULT_ACCESS_DENIED = 15,
    SK_ERESULT_TIMEOUT = 16,
    SK_ERESULT_BANNED = 17,
    SK_ERESULT_ACCOUNT_NOT_FOUND = 18,
    SK_ERESULT_INVALID_STEAM_ID = 19,
    SK_ERESULT_SERVICE_UNAVAILABLE = 20,
    SK_ERESULT_NOT_LOGGED_ON = 21,
    SK_ERESULT_PENDING = 22,
    SK_ERESULT_CONFLICT = 23,
    SK_ERESULT_RESET = 24,
    SK_ERESULT_INVALID_STEAM_TICKET = 30,
    SK_ERESULT_ALREADY_OWNED = 40,
    SK_RESULT_MAX = 45,
} sk_eresult_t;

typedef enum sk_elogon_result {
    SK_ELOGON_RESULT_OK = SK_ERESULT_OK,
    SK_ELOGON_RESULT_FAIL = SK_ERESULT_FAIL,
    SK_ELOGON_RESULT_NO_CONNECTION = SK_ERESULT_NO_CONNECTION,
    SK_ELOGON_RESULT_INVALID_CREDENTIALS = SK_ERESULT_INVALID_PASSWORD,
    SK_ELOGON_RESULT_DISABLED = 25,
    SK_ELOGON_RESULT_LIMITED = 26,
    SK_ELOGON_RESULT_ACCOUNT_NOT_FOUND = 27,
    SK_ELOGON_RESULT_ACCOUNT_LOCKED = 28,
    SK_ELOGON_RESULT_ACCOUNT_LIMIT_EXCEEDED = 29,
    SK_ELOGON_RESULT_TWO_FACTOR_CODE_MISMATCH = 36,
    SK_ELOGON_RESULT_EMAIL_TOKEN_INVALID = 37,
    SK_ELOGON_RESULT_ACCOUNT_ALREADY_LOGGED_IN = 38,
    SK_ELOGON_RESULT_LOGIN_FAILED = 39,
} sk_elogon_result_t;

#ifdef __cplusplus
}
#endif

#endif // STEAMKIT_STEAM_HANDLERS_STEAM_USER_CALLBACKS_H
