/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: contenthubs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "contenthubs.pb-c.h"
void   cstore_page_filter__sale_page_filter__init
                     (CStorePageFilter__SalePageFilter         *message)
{
  static const CStorePageFilter__SalePageFilter init_value = CSTORE_PAGE_FILTER__SALE_PAGE_FILTER__INIT;
  *message = init_value;
}
void   cstore_page_filter__content_hub_filter__opt_in_info__init
                     (CStorePageFilter__ContentHubFilter__OptInInfo         *message)
{
  static const CStorePageFilter__ContentHubFilter__OptInInfo init_value = CSTORE_PAGE_FILTER__CONTENT_HUB_FILTER__OPT_IN_INFO__INIT;
  *message = init_value;
}
void   cstore_page_filter__content_hub_filter__init
                     (CStorePageFilter__ContentHubFilter         *message)
{
  static const CStorePageFilter__ContentHubFilter init_value = CSTORE_PAGE_FILTER__CONTENT_HUB_FILTER__INIT;
  *message = init_value;
}
void   cstore_page_filter__store_filter__init
                     (CStorePageFilter__StoreFilter         *message)
{
  static const CStorePageFilter__StoreFilter init_value = CSTORE_PAGE_FILTER__STORE_FILTER__INIT;
  *message = init_value;
}
void   cstore_page_filter__init
                     (CStorePageFilter         *message)
{
  static const CStorePageFilter init_value = CSTORE_PAGE_FILTER__INIT;
  *message = init_value;
}
size_t cstore_page_filter__get_packed_size
                     (const CStorePageFilter *message)
{
  assert(message->base.descriptor == &cstore_page_filter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cstore_page_filter__pack
                     (const CStorePageFilter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cstore_page_filter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cstore_page_filter__pack_to_buffer
                     (const CStorePageFilter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cstore_page_filter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CStorePageFilter *
       cstore_page_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CStorePageFilter *)
     protobuf_c_message_unpack (&cstore_page_filter__descriptor,
                                allocator, len, data);
}
void   cstore_page_filter__free_unpacked
                     (CStorePageFilter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cstore_page_filter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cstore_page_filter__sale_page_filter__field_descriptors[2] =
{
  {
    "sale_tagid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CStorePageFilter__SalePageFilter, has_sale_tagid),
    offsetof(CStorePageFilter__SalePageFilter, sale_tagid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "creator_clan_account_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CStorePageFilter__SalePageFilter, has_creator_clan_account_id),
    offsetof(CStorePageFilter__SalePageFilter, creator_clan_account_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cstore_page_filter__sale_page_filter__field_indices_by_name[] = {
  1,   /* field[1] = creator_clan_account_id */
  0,   /* field[0] = sale_tagid */
};
static const ProtobufCIntRange cstore_page_filter__sale_page_filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cstore_page_filter__sale_page_filter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CStorePageFilter.SalePageFilter",
  "SalePageFilter",
  "CStorePageFilter__SalePageFilter",
  "",
  sizeof(CStorePageFilter__SalePageFilter),
  2,
  cstore_page_filter__sale_page_filter__field_descriptors,
  cstore_page_filter__sale_page_filter__field_indices_by_name,
  1,  cstore_page_filter__sale_page_filter__number_ranges,
  (ProtobufCMessageInit) cstore_page_filter__sale_page_filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cstore_page_filter__content_hub_filter__opt_in_info__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CStorePageFilter__ContentHubFilter__OptInInfo, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optin_tagid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CStorePageFilter__ContentHubFilter__OptInInfo, has_optin_tagid),
    offsetof(CStorePageFilter__ContentHubFilter__OptInInfo, optin_tagid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prune_tagid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CStorePageFilter__ContentHubFilter__OptInInfo, has_prune_tagid),
    offsetof(CStorePageFilter__ContentHubFilter__OptInInfo, prune_tagid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optin_only",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CStorePageFilter__ContentHubFilter__OptInInfo, has_optin_only),
    offsetof(CStorePageFilter__ContentHubFilter__OptInInfo, optin_only),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cstore_page_filter__content_hub_filter__opt_in_info__field_indices_by_name[] = {
  0,   /* field[0] = name */
  3,   /* field[3] = optin_only */
  1,   /* field[1] = optin_tagid */
  2,   /* field[2] = prune_tagid */
};
static const ProtobufCIntRange cstore_page_filter__content_hub_filter__opt_in_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cstore_page_filter__content_hub_filter__opt_in_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CStorePageFilter.ContentHubFilter.OptInInfo",
  "OptInInfo",
  "CStorePageFilter__ContentHubFilter__OptInInfo",
  "",
  sizeof(CStorePageFilter__ContentHubFilter__OptInInfo),
  4,
  cstore_page_filter__content_hub_filter__opt_in_info__field_descriptors,
  cstore_page_filter__content_hub_filter__opt_in_info__field_indices_by_name,
  1,  cstore_page_filter__content_hub_filter__opt_in_info__number_ranges,
  (ProtobufCMessageInit) cstore_page_filter__content_hub_filter__opt_in_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const EContentHubDiscountFilterType cstore_page_filter__content_hub_filter__discount_filter__default_value = ECONTENT_HUB_DISCOUNT_FILTER_TYPE__k_EContentHubDiscountFilterType_None;
static const ProtobufCFieldDescriptor cstore_page_filter__content_hub_filter__field_descriptors[5] =
{
  {
    "hub_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CStorePageFilter__ContentHubFilter, hub_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hub_category",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CStorePageFilter__ContentHubFilter, hub_category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hub_tagid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CStorePageFilter__ContentHubFilter, has_hub_tagid),
    offsetof(CStorePageFilter__ContentHubFilter, hub_tagid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "discount_filter",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CStorePageFilter__ContentHubFilter, has_discount_filter),
    offsetof(CStorePageFilter__ContentHubFilter, discount_filter),
    &econtent_hub_discount_filter_type__descriptor,
    &cstore_page_filter__content_hub_filter__discount_filter__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optin",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CStorePageFilter__ContentHubFilter, optin),
    &cstore_page_filter__content_hub_filter__opt_in_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cstore_page_filter__content_hub_filter__field_indices_by_name[] = {
  3,   /* field[3] = discount_filter */
  1,   /* field[1] = hub_category */
  2,   /* field[2] = hub_tagid */
  0,   /* field[0] = hub_type */
  4,   /* field[4] = optin */
};
static const ProtobufCIntRange cstore_page_filter__content_hub_filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor cstore_page_filter__content_hub_filter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CStorePageFilter.ContentHubFilter",
  "ContentHubFilter",
  "CStorePageFilter__ContentHubFilter",
  "",
  sizeof(CStorePageFilter__ContentHubFilter),
  5,
  cstore_page_filter__content_hub_filter__field_descriptors,
  cstore_page_filter__content_hub_filter__field_indices_by_name,
  1,  cstore_page_filter__content_hub_filter__number_ranges,
  (ProtobufCMessageInit) cstore_page_filter__content_hub_filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cstore_page_filter__store_filter__field_descriptors[2] =
{
  {
    "filter_json",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CStorePageFilter__StoreFilter, filter_json),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cache_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CStorePageFilter__StoreFilter, cache_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cstore_page_filter__store_filter__field_indices_by_name[] = {
  1,   /* field[1] = cache_key */
  0,   /* field[0] = filter_json */
};
static const ProtobufCIntRange cstore_page_filter__store_filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cstore_page_filter__store_filter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CStorePageFilter.StoreFilter",
  "StoreFilter",
  "CStorePageFilter__StoreFilter",
  "",
  sizeof(CStorePageFilter__StoreFilter),
  2,
  cstore_page_filter__store_filter__field_descriptors,
  cstore_page_filter__store_filter__field_indices_by_name,
  1,  cstore_page_filter__store_filter__number_ranges,
  (ProtobufCMessageInit) cstore_page_filter__store_filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cstore_page_filter__field_descriptors[3] =
{
  {
    "sale_filter",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CStorePageFilter, sale_filter),
    &cstore_page_filter__sale_page_filter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_hub_filter",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CStorePageFilter, content_hub_filter),
    &cstore_page_filter__content_hub_filter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "store_filters",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CStorePageFilter, n_store_filters),
    offsetof(CStorePageFilter, store_filters),
    &cstore_page_filter__store_filter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cstore_page_filter__field_indices_by_name[] = {
  1,   /* field[1] = content_hub_filter */
  0,   /* field[0] = sale_filter */
  2,   /* field[2] = store_filters */
};
static const ProtobufCIntRange cstore_page_filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cstore_page_filter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CStorePageFilter",
  "CStorePageFilter",
  "CStorePageFilter",
  "",
  sizeof(CStorePageFilter),
  3,
  cstore_page_filter__field_descriptors,
  cstore_page_filter__field_indices_by_name,
  1,  cstore_page_filter__number_ranges,
  (ProtobufCMessageInit) cstore_page_filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue econtent_hub_discount_filter_type__enum_values_by_number[3] =
{
  { "k_EContentHubDiscountFilterType_None", "ECONTENT_HUB_DISCOUNT_FILTER_TYPE__k_EContentHubDiscountFilterType_None", 0 },
  { "k_EContentHubDiscountFilterType_DiscountsOnly", "ECONTENT_HUB_DISCOUNT_FILTER_TYPE__k_EContentHubDiscountFilterType_DiscountsOnly", 1 },
  { "k_EContentHubDiscountFilterType_PrioritizeDiscounts", "ECONTENT_HUB_DISCOUNT_FILTER_TYPE__k_EContentHubDiscountFilterType_PrioritizeDiscounts", 2 },
};
static const ProtobufCIntRange econtent_hub_discount_filter_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex econtent_hub_discount_filter_type__enum_values_by_name[3] =
{
  { "k_EContentHubDiscountFilterType_DiscountsOnly", 1 },
  { "k_EContentHubDiscountFilterType_None", 0 },
  { "k_EContentHubDiscountFilterType_PrioritizeDiscounts", 2 },
};
const ProtobufCEnumDescriptor econtent_hub_discount_filter_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EContentHubDiscountFilterType",
  "EContentHubDiscountFilterType",
  "EContentHubDiscountFilterType",
  "",
  3,
  econtent_hub_discount_filter_type__enum_values_by_number,
  3,
  econtent_hub_discount_filter_type__enum_values_by_name,
  1,
  econtent_hub_discount_filter_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
