/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: enums_productinfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "enums_productinfo.pb-c.h"
static const ProtobufCEnumValue econtent_descriptor_id__enum_values_by_number[6] =
{
  { "k_EContentDescriptor_NudityOrSexualContent", "ECONTENT_DESCRIPTOR_ID__k_EContentDescriptor_NudityOrSexualContent", 1 },
  { "k_EContentDescriptor_FrequentViolenceOrGore", "ECONTENT_DESCRIPTOR_ID__k_EContentDescriptor_FrequentViolenceOrGore", 2 },
  { "k_EContentDescriptor_AdultOnlySexualContent", "ECONTENT_DESCRIPTOR_ID__k_EContentDescriptor_AdultOnlySexualContent", 3 },
  { "k_EContentDescriptor_GratuitousSexualContent", "ECONTENT_DESCRIPTOR_ID__k_EContentDescriptor_GratuitousSexualContent", 4 },
  { "k_EContentDescriptor_AnyMatureContent", "ECONTENT_DESCRIPTOR_ID__k_EContentDescriptor_AnyMatureContent", 5 },
  { "k_EContentDescriptorMAX", "ECONTENT_DESCRIPTOR_ID__k_EContentDescriptorMAX", 6 },
};
static const ProtobufCIntRange econtent_descriptor_id__value_ranges[] = {
{1, 0},{0, 6}
};
static const ProtobufCEnumValueIndex econtent_descriptor_id__enum_values_by_name[6] =
{
  { "k_EContentDescriptorMAX", 5 },
  { "k_EContentDescriptor_AdultOnlySexualContent", 2 },
  { "k_EContentDescriptor_AnyMatureContent", 4 },
  { "k_EContentDescriptor_FrequentViolenceOrGore", 1 },
  { "k_EContentDescriptor_GratuitousSexualContent", 3 },
  { "k_EContentDescriptor_NudityOrSexualContent", 0 },
};
const ProtobufCEnumDescriptor econtent_descriptor_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EContentDescriptorID",
  "EContentDescriptorID",
  "EContentDescriptorID",
  "",
  6,
  econtent_descriptor_id__enum_values_by_number,
  6,
  econtent_descriptor_id__enum_values_by_name,
  1,
  econtent_descriptor_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue erating_agency__enum_values_by_number[19] =
{
  { "k_ERatingAgency_Invalid", "ERATING_AGENCY__k_ERatingAgency_Invalid", 0 },
  { "k_ERatingAgency_ESRB", "ERATING_AGENCY__k_ERatingAgency_ESRB", 1 },
  { "k_ERatingAgency_PEGI", "ERATING_AGENCY__k_ERatingAgency_PEGI", 2 },
  { "k_ERatingAgency_BBFC", "ERATING_AGENCY__k_ERatingAgency_BBFC", 3 },
  { "k_ERatingAgency_USK", "ERATING_AGENCY__k_ERatingAgency_USK", 4 },
  { "k_ERatingAgency_OFLC_AU", "ERATING_AGENCY__k_ERatingAgency_OFLC_AU", 5 },
  { "k_ERatingAgency_OFLC_NZ", "ERATING_AGENCY__k_ERatingAgency_OFLC_NZ", 6 },
  { "k_ERatingAgency_CERO", "ERATING_AGENCY__k_ERatingAgency_CERO", 7 },
  { "k_ERatingAgency_GRAC", "ERATING_AGENCY__k_ERatingAgency_GRAC", 8 },
  { "k_ERatingAgency_GMEDIA", "ERATING_AGENCY__k_ERatingAgency_GMEDIA", 9 },
  { "k_ERatingAgency_DEJUS", "ERATING_AGENCY__k_ERatingAgency_DEJUS", 10 },
  { "k_ERatingAgency_IMDA", "ERATING_AGENCY__k_ERatingAgency_IMDA", 11 },
  { "k_ERatingAgency_FPB", "ERATING_AGENCY__k_ERatingAgency_FPB", 12 },
  { "k_ERatingAgency_TESRI", "ERATING_AGENCY__k_ERatingAgency_TESRI", 13 },
  { "k_ERatingAgency_RARS", "ERATING_AGENCY__k_ERatingAgency_RARS", 14 },
  { "k_ERatingAgency_AGCOM", "ERATING_AGENCY__k_ERatingAgency_AGCOM", 15 },
  { "k_ERatingAgency_IGRS", "ERATING_AGENCY__k_ERatingAgency_IGRS", 16 },
  { "k_ERatingAgency_Steam_Germany", "ERATING_AGENCY__k_ERatingAgency_Steam_Germany", 17 },
  { "k_ERatingAgency_Steam_Australia", "ERATING_AGENCY__k_ERatingAgency_Steam_Australia", 18 },
};
static const ProtobufCIntRange erating_agency__value_ranges[] = {
{0, 0},{0, 19}
};
static const ProtobufCEnumValueIndex erating_agency__enum_values_by_name[19] =
{
  { "k_ERatingAgency_AGCOM", 15 },
  { "k_ERatingAgency_BBFC", 3 },
  { "k_ERatingAgency_CERO", 7 },
  { "k_ERatingAgency_DEJUS", 10 },
  { "k_ERatingAgency_ESRB", 1 },
  { "k_ERatingAgency_FPB", 12 },
  { "k_ERatingAgency_GMEDIA", 9 },
  { "k_ERatingAgency_GRAC", 8 },
  { "k_ERatingAgency_IGRS", 16 },
  { "k_ERatingAgency_IMDA", 11 },
  { "k_ERatingAgency_Invalid", 0 },
  { "k_ERatingAgency_OFLC_AU", 5 },
  { "k_ERatingAgency_OFLC_NZ", 6 },
  { "k_ERatingAgency_PEGI", 2 },
  { "k_ERatingAgency_RARS", 14 },
  { "k_ERatingAgency_Steam_Australia", 18 },
  { "k_ERatingAgency_Steam_Germany", 17 },
  { "k_ERatingAgency_TESRI", 13 },
  { "k_ERatingAgency_USK", 4 },
};
const ProtobufCEnumDescriptor erating_agency__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ERatingAgency",
  "ERatingAgency",
  "ERatingAgency",
  "",
  19,
  erating_agency__enum_values_by_number,
  19,
  erating_agency__enum_values_by_name,
  1,
  erating_agency__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
