/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_lobbymatchmaking.steamclient.proto */

#ifndef PROTOBUF_C_steammessages_5flobbymatchmaking_2esteamclient_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5flobbymatchmaking_2esteamclient_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "steammessages_unified_base.steamclient.pb-c.h"

typedef struct LobbyMatchmakingLegacyGetLobbyStatusRequest LobbyMatchmakingLegacyGetLobbyStatusRequest;
typedef struct LobbyMatchmakingLegacyGetLobbyStatusResponse LobbyMatchmakingLegacyGetLobbyStatusResponse;


/* --- enums --- */

typedef enum _ELobbyStatus {
  ELOBBY_STATUS__k_ELobbyStatusInvalid = 0,
  ELOBBY_STATUS__k_ELobbyStatusExists = 1,
  ELOBBY_STATUS__k_ELobbyStatusDoesNotExist = 2,
  ELOBBY_STATUS__k_ELobbyStatusNotAMember = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ELOBBY_STATUS)
} ELobbyStatus;

/* --- messages --- */

struct  LobbyMatchmakingLegacyGetLobbyStatusRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_app_id;
  uint32_t app_id;
  protobuf_c_boolean has_steamid_lobby;
  uint64_t steamid_lobby;
  protobuf_c_boolean has_claim_ownership;
  protobuf_c_boolean claim_ownership;
  protobuf_c_boolean has_claim_membership;
  protobuf_c_boolean claim_membership;
  protobuf_c_boolean has_version_num;
  uint32_t version_num;
};
#define LOBBY_MATCHMAKING_LEGACY__GET_LOBBY_STATUS__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lobby_matchmaking_legacy__get_lobby_status__request__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  LobbyMatchmakingLegacyGetLobbyStatusResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_app_id;
  uint32_t app_id;
  protobuf_c_boolean has_steamid_lobby;
  uint64_t steamid_lobby;
  protobuf_c_boolean has_lobby_status;
  ELobbyStatus lobby_status;
};
#define LOBBY_MATCHMAKING_LEGACY__GET_LOBBY_STATUS__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lobby_matchmaking_legacy__get_lobby_status__response__descriptor) \
, 0, 0, 0, 0, 0, ELOBBY_STATUS__k_ELobbyStatusInvalid }


/* LobbyMatchmakingLegacyGetLobbyStatusRequest methods */
void   lobby_matchmaking_legacy__get_lobby_status__request__init
                     (LobbyMatchmakingLegacyGetLobbyStatusRequest         *message);
size_t lobby_matchmaking_legacy__get_lobby_status__request__get_packed_size
                     (const LobbyMatchmakingLegacyGetLobbyStatusRequest   *message);
size_t lobby_matchmaking_legacy__get_lobby_status__request__pack
                     (const LobbyMatchmakingLegacyGetLobbyStatusRequest   *message,
                      uint8_t             *out);
size_t lobby_matchmaking_legacy__get_lobby_status__request__pack_to_buffer
                     (const LobbyMatchmakingLegacyGetLobbyStatusRequest   *message,
                      ProtobufCBuffer     *buffer);
LobbyMatchmakingLegacyGetLobbyStatusRequest *
       lobby_matchmaking_legacy__get_lobby_status__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lobby_matchmaking_legacy__get_lobby_status__request__free_unpacked
                     (LobbyMatchmakingLegacyGetLobbyStatusRequest *message,
                      ProtobufCAllocator *allocator);
/* LobbyMatchmakingLegacyGetLobbyStatusResponse methods */
void   lobby_matchmaking_legacy__get_lobby_status__response__init
                     (LobbyMatchmakingLegacyGetLobbyStatusResponse         *message);
size_t lobby_matchmaking_legacy__get_lobby_status__response__get_packed_size
                     (const LobbyMatchmakingLegacyGetLobbyStatusResponse   *message);
size_t lobby_matchmaking_legacy__get_lobby_status__response__pack
                     (const LobbyMatchmakingLegacyGetLobbyStatusResponse   *message,
                      uint8_t             *out);
size_t lobby_matchmaking_legacy__get_lobby_status__response__pack_to_buffer
                     (const LobbyMatchmakingLegacyGetLobbyStatusResponse   *message,
                      ProtobufCBuffer     *buffer);
LobbyMatchmakingLegacyGetLobbyStatusResponse *
       lobby_matchmaking_legacy__get_lobby_status__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lobby_matchmaking_legacy__get_lobby_status__response__free_unpacked
                     (LobbyMatchmakingLegacyGetLobbyStatusResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LobbyMatchmakingLegacyGetLobbyStatusRequest_Closure)
                 (const LobbyMatchmakingLegacyGetLobbyStatusRequest *message,
                  void *closure_data);
typedef void (*LobbyMatchmakingLegacyGetLobbyStatusResponse_Closure)
                 (const LobbyMatchmakingLegacyGetLobbyStatusResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct LobbyMatchmakingLegacy_Service LobbyMatchmakingLegacy_Service;
struct LobbyMatchmakingLegacy_Service
{
  ProtobufCService base;
  void (*get_lobby_status)(LobbyMatchmakingLegacy_Service *service,
                           const LobbyMatchmakingLegacyGetLobbyStatusRequest *input,
                           LobbyMatchmakingLegacyGetLobbyStatusResponse_Closure closure,
                           void *closure_data);
};
typedef void (*LobbyMatchmakingLegacy_ServiceDestroy)(LobbyMatchmakingLegacy_Service *);
void lobby_matchmaking_legacy__init (LobbyMatchmakingLegacy_Service *service,
                                     LobbyMatchmakingLegacy_ServiceDestroy destroy);
#define LOBBY_MATCHMAKING_LEGACY__BASE_INIT \
    { &lobby_matchmaking_legacy__descriptor, protobuf_c_service_invoke_internal, NULL }
#define LOBBY_MATCHMAKING_LEGACY__INIT(function_prefix__) \
    { LOBBY_MATCHMAKING_LEGACY__BASE_INIT,\
      function_prefix__ ## get_lobby_status  }
void lobby_matchmaking_legacy__get_lobby_status(ProtobufCService *service,
                                                const LobbyMatchmakingLegacyGetLobbyStatusRequest *input,
                                                LobbyMatchmakingLegacyGetLobbyStatusResponse_Closure closure,
                                                void *closure_data);

/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    elobby_status__descriptor;
extern const ProtobufCMessageDescriptor lobby_matchmaking_legacy__get_lobby_status__request__descriptor;
extern const ProtobufCMessageDescriptor lobby_matchmaking_legacy__get_lobby_status__response__descriptor;
extern const ProtobufCServiceDescriptor lobby_matchmaking_legacy__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5flobbymatchmaking_2esteamclient_2eproto__INCLUDED */
