/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_parental_objects.proto */

#ifndef PROTOBUF_C_steammessages_5fparental_5fobjects_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5fparental_5fobjects_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "enums.pb-c.h"

typedef struct ParentalApp ParentalApp;
typedef struct ParentalPlaytimeDay ParentalPlaytimeDay;
typedef struct ParentalPlaytimeRestrictions ParentalPlaytimeRestrictions;
typedef struct ParentalTemporaryPlaytimeRestrictions ParentalTemporaryPlaytimeRestrictions;
typedef struct ParentalSettings ParentalSettings;
typedef struct ParentalFeatureRequest ParentalFeatureRequest;
typedef struct ParentalPlaytimeRequest ParentalPlaytimeRequest;


/* --- enums --- */


/* --- messages --- */

struct  ParentalApp
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_is_allowed;
  protobuf_c_boolean is_allowed;
};
#define PARENTAL_APP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parental_app__descriptor) \
, 0, 0, 0, 0 }


struct  ParentalPlaytimeDay
{
  ProtobufCMessage base;
  protobuf_c_boolean has_allowed_time_windows;
  uint64_t allowed_time_windows;
  protobuf_c_boolean has_allowed_daily_minutes;
  uint32_t allowed_daily_minutes;
};
#define PARENTAL_PLAYTIME_DAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parental_playtime_day__descriptor) \
, 0, 0, 0, 0 }


struct  ParentalPlaytimeRestrictions
{
  ProtobufCMessage base;
  protobuf_c_boolean has_apply_playtime_restrictions;
  protobuf_c_boolean apply_playtime_restrictions;
  size_t n_playtime_days;
  ParentalPlaytimeDay **playtime_days;
};
#define PARENTAL_PLAYTIME_RESTRICTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parental_playtime_restrictions__descriptor) \
, 0, 0, 0,NULL }


struct  ParentalTemporaryPlaytimeRestrictions
{
  ProtobufCMessage base;
  ParentalPlaytimeDay *restrictions;
  protobuf_c_boolean has_rtime_expires;
  uint32_t rtime_expires;
};
#define PARENTAL_TEMPORARY_PLAYTIME_RESTRICTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parental_temporary_playtime_restrictions__descriptor) \
, NULL, 0, 0 }


struct  ParentalSettings
{
  ProtobufCMessage base;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  protobuf_c_boolean has_applist_base_id;
  uint32_t applist_base_id;
  char *applist_base_description;
  size_t n_applist_base;
  ParentalApp **applist_base;
  size_t n_applist_custom;
  ParentalApp **applist_custom;
  protobuf_c_boolean has_passwordhashtype;
  uint32_t passwordhashtype;
  protobuf_c_boolean has_salt;
  ProtobufCBinaryData salt;
  protobuf_c_boolean has_passwordhash;
  ProtobufCBinaryData passwordhash;
  protobuf_c_boolean has_is_enabled;
  protobuf_c_boolean is_enabled;
  protobuf_c_boolean has_enabled_features;
  uint32_t enabled_features;
  char *recovery_email;
  protobuf_c_boolean has_is_site_license_lock;
  protobuf_c_boolean is_site_license_lock;
  protobuf_c_boolean has_temporary_enabled_features;
  uint32_t temporary_enabled_features;
  protobuf_c_boolean has_rtime_temporary_feature_expiration;
  uint32_t rtime_temporary_feature_expiration;
  ParentalPlaytimeRestrictions *playtime_restrictions;
  ParentalTemporaryPlaytimeRestrictions *temporary_playtime_restrictions;
  size_t n_excluded_store_content_descriptors;
  uint32_t *excluded_store_content_descriptors;
  size_t n_excluded_community_content_descriptors;
  uint32_t *excluded_community_content_descriptors;
  size_t n_utility_appids;
  uint32_t *utility_appids;
};
#define PARENTAL_SETTINGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parental_settings__descriptor) \
, 0, 0, 0, 0, NULL, 0,NULL, 0,NULL, 0, 0, 0, {0,NULL}, 0, {0,NULL}, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, NULL, 0,NULL, 0,NULL, 0,NULL }


struct  ParentalFeatureRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_requestid;
  uint64_t requestid;
  protobuf_c_boolean has_family_groupid;
  uint64_t family_groupid;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  protobuf_c_boolean has_features;
  uint32_t features;
  protobuf_c_boolean has_time_requested;
  uint32_t time_requested;
  protobuf_c_boolean has_approved;
  protobuf_c_boolean approved;
  protobuf_c_boolean has_steamid_responder;
  uint64_t steamid_responder;
  protobuf_c_boolean has_time_responded;
  uint32_t time_responded;
};
#define PARENTAL_FEATURE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parental_feature_request__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  ParentalPlaytimeRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_requestid;
  uint64_t requestid;
  protobuf_c_boolean has_family_groupid;
  uint64_t family_groupid;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  ParentalPlaytimeDay *current_playtime_restrictions;
  protobuf_c_boolean has_time_expires;
  uint32_t time_expires;
  protobuf_c_boolean has_time_requested;
  uint32_t time_requested;
  protobuf_c_boolean has_approved;
  protobuf_c_boolean approved;
  protobuf_c_boolean has_steamid_responder;
  uint64_t steamid_responder;
  protobuf_c_boolean has_time_responded;
  uint32_t time_responded;
  ParentalTemporaryPlaytimeRestrictions *restrictions_approved;
};
#define PARENTAL_PLAYTIME_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parental_playtime_request__descriptor) \
, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL }


/* ParentalApp methods */
void   parental_app__init
                     (ParentalApp         *message);
size_t parental_app__get_packed_size
                     (const ParentalApp   *message);
size_t parental_app__pack
                     (const ParentalApp   *message,
                      uint8_t             *out);
size_t parental_app__pack_to_buffer
                     (const ParentalApp   *message,
                      ProtobufCBuffer     *buffer);
ParentalApp *
       parental_app__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parental_app__free_unpacked
                     (ParentalApp *message,
                      ProtobufCAllocator *allocator);
/* ParentalPlaytimeDay methods */
void   parental_playtime_day__init
                     (ParentalPlaytimeDay         *message);
size_t parental_playtime_day__get_packed_size
                     (const ParentalPlaytimeDay   *message);
size_t parental_playtime_day__pack
                     (const ParentalPlaytimeDay   *message,
                      uint8_t             *out);
size_t parental_playtime_day__pack_to_buffer
                     (const ParentalPlaytimeDay   *message,
                      ProtobufCBuffer     *buffer);
ParentalPlaytimeDay *
       parental_playtime_day__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parental_playtime_day__free_unpacked
                     (ParentalPlaytimeDay *message,
                      ProtobufCAllocator *allocator);
/* ParentalPlaytimeRestrictions methods */
void   parental_playtime_restrictions__init
                     (ParentalPlaytimeRestrictions         *message);
size_t parental_playtime_restrictions__get_packed_size
                     (const ParentalPlaytimeRestrictions   *message);
size_t parental_playtime_restrictions__pack
                     (const ParentalPlaytimeRestrictions   *message,
                      uint8_t             *out);
size_t parental_playtime_restrictions__pack_to_buffer
                     (const ParentalPlaytimeRestrictions   *message,
                      ProtobufCBuffer     *buffer);
ParentalPlaytimeRestrictions *
       parental_playtime_restrictions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parental_playtime_restrictions__free_unpacked
                     (ParentalPlaytimeRestrictions *message,
                      ProtobufCAllocator *allocator);
/* ParentalTemporaryPlaytimeRestrictions methods */
void   parental_temporary_playtime_restrictions__init
                     (ParentalTemporaryPlaytimeRestrictions         *message);
size_t parental_temporary_playtime_restrictions__get_packed_size
                     (const ParentalTemporaryPlaytimeRestrictions   *message);
size_t parental_temporary_playtime_restrictions__pack
                     (const ParentalTemporaryPlaytimeRestrictions   *message,
                      uint8_t             *out);
size_t parental_temporary_playtime_restrictions__pack_to_buffer
                     (const ParentalTemporaryPlaytimeRestrictions   *message,
                      ProtobufCBuffer     *buffer);
ParentalTemporaryPlaytimeRestrictions *
       parental_temporary_playtime_restrictions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parental_temporary_playtime_restrictions__free_unpacked
                     (ParentalTemporaryPlaytimeRestrictions *message,
                      ProtobufCAllocator *allocator);
/* ParentalSettings methods */
void   parental_settings__init
                     (ParentalSettings         *message);
size_t parental_settings__get_packed_size
                     (const ParentalSettings   *message);
size_t parental_settings__pack
                     (const ParentalSettings   *message,
                      uint8_t             *out);
size_t parental_settings__pack_to_buffer
                     (const ParentalSettings   *message,
                      ProtobufCBuffer     *buffer);
ParentalSettings *
       parental_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parental_settings__free_unpacked
                     (ParentalSettings *message,
                      ProtobufCAllocator *allocator);
/* ParentalFeatureRequest methods */
void   parental_feature_request__init
                     (ParentalFeatureRequest         *message);
size_t parental_feature_request__get_packed_size
                     (const ParentalFeatureRequest   *message);
size_t parental_feature_request__pack
                     (const ParentalFeatureRequest   *message,
                      uint8_t             *out);
size_t parental_feature_request__pack_to_buffer
                     (const ParentalFeatureRequest   *message,
                      ProtobufCBuffer     *buffer);
ParentalFeatureRequest *
       parental_feature_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parental_feature_request__free_unpacked
                     (ParentalFeatureRequest *message,
                      ProtobufCAllocator *allocator);
/* ParentalPlaytimeRequest methods */
void   parental_playtime_request__init
                     (ParentalPlaytimeRequest         *message);
size_t parental_playtime_request__get_packed_size
                     (const ParentalPlaytimeRequest   *message);
size_t parental_playtime_request__pack
                     (const ParentalPlaytimeRequest   *message,
                      uint8_t             *out);
size_t parental_playtime_request__pack_to_buffer
                     (const ParentalPlaytimeRequest   *message,
                      ProtobufCBuffer     *buffer);
ParentalPlaytimeRequest *
       parental_playtime_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parental_playtime_request__free_unpacked
                     (ParentalPlaytimeRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ParentalApp_Closure)
                 (const ParentalApp *message,
                  void *closure_data);
typedef void (*ParentalPlaytimeDay_Closure)
                 (const ParentalPlaytimeDay *message,
                  void *closure_data);
typedef void (*ParentalPlaytimeRestrictions_Closure)
                 (const ParentalPlaytimeRestrictions *message,
                  void *closure_data);
typedef void (*ParentalTemporaryPlaytimeRestrictions_Closure)
                 (const ParentalTemporaryPlaytimeRestrictions *message,
                  void *closure_data);
typedef void (*ParentalSettings_Closure)
                 (const ParentalSettings *message,
                  void *closure_data);
typedef void (*ParentalFeatureRequest_Closure)
                 (const ParentalFeatureRequest *message,
                  void *closure_data);
typedef void (*ParentalPlaytimeRequest_Closure)
                 (const ParentalPlaytimeRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor parental_app__descriptor;
extern const ProtobufCMessageDescriptor parental_playtime_day__descriptor;
extern const ProtobufCMessageDescriptor parental_playtime_restrictions__descriptor;
extern const ProtobufCMessageDescriptor parental_temporary_playtime_restrictions__descriptor;
extern const ProtobufCMessageDescriptor parental_settings__descriptor;
extern const ProtobufCMessageDescriptor parental_feature_request__descriptor;
extern const ProtobufCMessageDescriptor parental_playtime_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5fparental_5fobjects_2eproto__INCLUDED */
