/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_parental_objects.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "steammessages_parental_objects.pb-c.h"
void   parental_app__init
                     (ParentalApp         *message)
{
  static const ParentalApp init_value = PARENTAL_APP__INIT;
  *message = init_value;
}
size_t parental_app__get_packed_size
                     (const ParentalApp *message)
{
  assert(message->base.descriptor == &parental_app__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parental_app__pack
                     (const ParentalApp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parental_app__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parental_app__pack_to_buffer
                     (const ParentalApp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parental_app__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParentalApp *
       parental_app__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParentalApp *)
     protobuf_c_message_unpack (&parental_app__descriptor,
                                allocator, len, data);
}
void   parental_app__free_unpacked
                     (ParentalApp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parental_app__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parental_playtime_day__init
                     (ParentalPlaytimeDay         *message)
{
  static const ParentalPlaytimeDay init_value = PARENTAL_PLAYTIME_DAY__INIT;
  *message = init_value;
}
size_t parental_playtime_day__get_packed_size
                     (const ParentalPlaytimeDay *message)
{
  assert(message->base.descriptor == &parental_playtime_day__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parental_playtime_day__pack
                     (const ParentalPlaytimeDay *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parental_playtime_day__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parental_playtime_day__pack_to_buffer
                     (const ParentalPlaytimeDay *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parental_playtime_day__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParentalPlaytimeDay *
       parental_playtime_day__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParentalPlaytimeDay *)
     protobuf_c_message_unpack (&parental_playtime_day__descriptor,
                                allocator, len, data);
}
void   parental_playtime_day__free_unpacked
                     (ParentalPlaytimeDay *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parental_playtime_day__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parental_playtime_restrictions__init
                     (ParentalPlaytimeRestrictions         *message)
{
  static const ParentalPlaytimeRestrictions init_value = PARENTAL_PLAYTIME_RESTRICTIONS__INIT;
  *message = init_value;
}
size_t parental_playtime_restrictions__get_packed_size
                     (const ParentalPlaytimeRestrictions *message)
{
  assert(message->base.descriptor == &parental_playtime_restrictions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parental_playtime_restrictions__pack
                     (const ParentalPlaytimeRestrictions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parental_playtime_restrictions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parental_playtime_restrictions__pack_to_buffer
                     (const ParentalPlaytimeRestrictions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parental_playtime_restrictions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParentalPlaytimeRestrictions *
       parental_playtime_restrictions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParentalPlaytimeRestrictions *)
     protobuf_c_message_unpack (&parental_playtime_restrictions__descriptor,
                                allocator, len, data);
}
void   parental_playtime_restrictions__free_unpacked
                     (ParentalPlaytimeRestrictions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parental_playtime_restrictions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parental_temporary_playtime_restrictions__init
                     (ParentalTemporaryPlaytimeRestrictions         *message)
{
  static const ParentalTemporaryPlaytimeRestrictions init_value = PARENTAL_TEMPORARY_PLAYTIME_RESTRICTIONS__INIT;
  *message = init_value;
}
size_t parental_temporary_playtime_restrictions__get_packed_size
                     (const ParentalTemporaryPlaytimeRestrictions *message)
{
  assert(message->base.descriptor == &parental_temporary_playtime_restrictions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parental_temporary_playtime_restrictions__pack
                     (const ParentalTemporaryPlaytimeRestrictions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parental_temporary_playtime_restrictions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parental_temporary_playtime_restrictions__pack_to_buffer
                     (const ParentalTemporaryPlaytimeRestrictions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parental_temporary_playtime_restrictions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParentalTemporaryPlaytimeRestrictions *
       parental_temporary_playtime_restrictions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParentalTemporaryPlaytimeRestrictions *)
     protobuf_c_message_unpack (&parental_temporary_playtime_restrictions__descriptor,
                                allocator, len, data);
}
void   parental_temporary_playtime_restrictions__free_unpacked
                     (ParentalTemporaryPlaytimeRestrictions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parental_temporary_playtime_restrictions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parental_settings__init
                     (ParentalSettings         *message)
{
  static const ParentalSettings init_value = PARENTAL_SETTINGS__INIT;
  *message = init_value;
}
size_t parental_settings__get_packed_size
                     (const ParentalSettings *message)
{
  assert(message->base.descriptor == &parental_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parental_settings__pack
                     (const ParentalSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parental_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parental_settings__pack_to_buffer
                     (const ParentalSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parental_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParentalSettings *
       parental_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParentalSettings *)
     protobuf_c_message_unpack (&parental_settings__descriptor,
                                allocator, len, data);
}
void   parental_settings__free_unpacked
                     (ParentalSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parental_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parental_feature_request__init
                     (ParentalFeatureRequest         *message)
{
  static const ParentalFeatureRequest init_value = PARENTAL_FEATURE_REQUEST__INIT;
  *message = init_value;
}
size_t parental_feature_request__get_packed_size
                     (const ParentalFeatureRequest *message)
{
  assert(message->base.descriptor == &parental_feature_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parental_feature_request__pack
                     (const ParentalFeatureRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parental_feature_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parental_feature_request__pack_to_buffer
                     (const ParentalFeatureRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parental_feature_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParentalFeatureRequest *
       parental_feature_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParentalFeatureRequest *)
     protobuf_c_message_unpack (&parental_feature_request__descriptor,
                                allocator, len, data);
}
void   parental_feature_request__free_unpacked
                     (ParentalFeatureRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parental_feature_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parental_playtime_request__init
                     (ParentalPlaytimeRequest         *message)
{
  static const ParentalPlaytimeRequest init_value = PARENTAL_PLAYTIME_REQUEST__INIT;
  *message = init_value;
}
size_t parental_playtime_request__get_packed_size
                     (const ParentalPlaytimeRequest *message)
{
  assert(message->base.descriptor == &parental_playtime_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parental_playtime_request__pack
                     (const ParentalPlaytimeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parental_playtime_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parental_playtime_request__pack_to_buffer
                     (const ParentalPlaytimeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parental_playtime_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParentalPlaytimeRequest *
       parental_playtime_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParentalPlaytimeRequest *)
     protobuf_c_message_unpack (&parental_playtime_request__descriptor,
                                allocator, len, data);
}
void   parental_playtime_request__free_unpacked
                     (ParentalPlaytimeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parental_playtime_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor parental_app__field_descriptors[2] =
{
  {
    "appid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalApp, has_appid),
    offsetof(ParentalApp, appid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_allowed",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ParentalApp, has_is_allowed),
    offsetof(ParentalApp, is_allowed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parental_app__field_indices_by_name[] = {
  0,   /* field[0] = appid */
  1,   /* field[1] = is_allowed */
};
static const ProtobufCIntRange parental_app__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parental_app__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParentalApp",
  "ParentalApp",
  "ParentalApp",
  "",
  sizeof(ParentalApp),
  2,
  parental_app__field_descriptors,
  parental_app__field_indices_by_name,
  1,  parental_app__number_ranges,
  (ProtobufCMessageInit) parental_app__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parental_playtime_day__field_descriptors[2] =
{
  {
    "allowed_time_windows",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ParentalPlaytimeDay, has_allowed_time_windows),
    offsetof(ParentalPlaytimeDay, allowed_time_windows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allowed_daily_minutes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalPlaytimeDay, has_allowed_daily_minutes),
    offsetof(ParentalPlaytimeDay, allowed_daily_minutes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parental_playtime_day__field_indices_by_name[] = {
  1,   /* field[1] = allowed_daily_minutes */
  0,   /* field[0] = allowed_time_windows */
};
static const ProtobufCIntRange parental_playtime_day__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parental_playtime_day__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParentalPlaytimeDay",
  "ParentalPlaytimeDay",
  "ParentalPlaytimeDay",
  "",
  sizeof(ParentalPlaytimeDay),
  2,
  parental_playtime_day__field_descriptors,
  parental_playtime_day__field_indices_by_name,
  1,  parental_playtime_day__number_ranges,
  (ProtobufCMessageInit) parental_playtime_day__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parental_playtime_restrictions__field_descriptors[2] =
{
  {
    "apply_playtime_restrictions",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ParentalPlaytimeRestrictions, has_apply_playtime_restrictions),
    offsetof(ParentalPlaytimeRestrictions, apply_playtime_restrictions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playtime_days",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ParentalPlaytimeRestrictions, n_playtime_days),
    offsetof(ParentalPlaytimeRestrictions, playtime_days),
    &parental_playtime_day__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parental_playtime_restrictions__field_indices_by_name[] = {
  0,   /* field[0] = apply_playtime_restrictions */
  1,   /* field[1] = playtime_days */
};
static const ProtobufCIntRange parental_playtime_restrictions__number_ranges[2 + 1] =
{
  { 2, 0 },
  { 15, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parental_playtime_restrictions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParentalPlaytimeRestrictions",
  "ParentalPlaytimeRestrictions",
  "ParentalPlaytimeRestrictions",
  "",
  sizeof(ParentalPlaytimeRestrictions),
  2,
  parental_playtime_restrictions__field_descriptors,
  parental_playtime_restrictions__field_indices_by_name,
  2,  parental_playtime_restrictions__number_ranges,
  (ProtobufCMessageInit) parental_playtime_restrictions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parental_temporary_playtime_restrictions__field_descriptors[2] =
{
  {
    "restrictions",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ParentalTemporaryPlaytimeRestrictions, restrictions),
    &parental_playtime_day__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rtime_expires",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalTemporaryPlaytimeRestrictions, has_rtime_expires),
    offsetof(ParentalTemporaryPlaytimeRestrictions, rtime_expires),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parental_temporary_playtime_restrictions__field_indices_by_name[] = {
  0,   /* field[0] = restrictions */
  1,   /* field[1] = rtime_expires */
};
static const ProtobufCIntRange parental_temporary_playtime_restrictions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parental_temporary_playtime_restrictions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParentalTemporaryPlaytimeRestrictions",
  "ParentalTemporaryPlaytimeRestrictions",
  "ParentalTemporaryPlaytimeRestrictions",
  "",
  sizeof(ParentalTemporaryPlaytimeRestrictions),
  2,
  parental_temporary_playtime_restrictions__field_descriptors,
  parental_temporary_playtime_restrictions__field_indices_by_name,
  1,  parental_temporary_playtime_restrictions__number_ranges,
  (ProtobufCMessageInit) parental_temporary_playtime_restrictions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parental_settings__field_descriptors[19] =
{
  {
    "steamid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalSettings, has_steamid),
    offsetof(ParentalSettings, steamid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applist_base_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalSettings, has_applist_base_id),
    offsetof(ParentalSettings, applist_base_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applist_base_description",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ParentalSettings, applist_base_description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applist_base",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ParentalSettings, n_applist_base),
    offsetof(ParentalSettings, applist_base),
    &parental_app__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applist_custom",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ParentalSettings, n_applist_custom),
    offsetof(ParentalSettings, applist_custom),
    &parental_app__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "passwordhashtype",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalSettings, has_passwordhashtype),
    offsetof(ParentalSettings, passwordhashtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "salt",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ParentalSettings, has_salt),
    offsetof(ParentalSettings, salt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "passwordhash",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ParentalSettings, has_passwordhash),
    offsetof(ParentalSettings, passwordhash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_enabled",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ParentalSettings, has_is_enabled),
    offsetof(ParentalSettings, is_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enabled_features",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalSettings, has_enabled_features),
    offsetof(ParentalSettings, enabled_features),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recovery_email",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ParentalSettings, recovery_email),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_site_license_lock",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ParentalSettings, has_is_site_license_lock),
    offsetof(ParentalSettings, is_site_license_lock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temporary_enabled_features",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalSettings, has_temporary_enabled_features),
    offsetof(ParentalSettings, temporary_enabled_features),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rtime_temporary_feature_expiration",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalSettings, has_rtime_temporary_feature_expiration),
    offsetof(ParentalSettings, rtime_temporary_feature_expiration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playtime_restrictions",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ParentalSettings, playtime_restrictions),
    &parental_playtime_restrictions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temporary_playtime_restrictions",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ParentalSettings, temporary_playtime_restrictions),
    &parental_temporary_playtime_restrictions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "excluded_store_content_descriptors",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalSettings, n_excluded_store_content_descriptors),
    offsetof(ParentalSettings, excluded_store_content_descriptors),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "excluded_community_content_descriptors",
    18,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalSettings, n_excluded_community_content_descriptors),
    offsetof(ParentalSettings, excluded_community_content_descriptors),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "utility_appids",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalSettings, n_utility_appids),
    offsetof(ParentalSettings, utility_appids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parental_settings__field_indices_by_name[] = {
  3,   /* field[3] = applist_base */
  2,   /* field[2] = applist_base_description */
  1,   /* field[1] = applist_base_id */
  4,   /* field[4] = applist_custom */
  9,   /* field[9] = enabled_features */
  17,   /* field[17] = excluded_community_content_descriptors */
  16,   /* field[16] = excluded_store_content_descriptors */
  8,   /* field[8] = is_enabled */
  11,   /* field[11] = is_site_license_lock */
  7,   /* field[7] = passwordhash */
  5,   /* field[5] = passwordhashtype */
  14,   /* field[14] = playtime_restrictions */
  10,   /* field[10] = recovery_email */
  13,   /* field[13] = rtime_temporary_feature_expiration */
  6,   /* field[6] = salt */
  0,   /* field[0] = steamid */
  12,   /* field[12] = temporary_enabled_features */
  15,   /* field[15] = temporary_playtime_restrictions */
  18,   /* field[18] = utility_appids */
};
static const ProtobufCIntRange parental_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor parental_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParentalSettings",
  "ParentalSettings",
  "ParentalSettings",
  "",
  sizeof(ParentalSettings),
  19,
  parental_settings__field_descriptors,
  parental_settings__field_indices_by_name,
  1,  parental_settings__number_ranges,
  (ProtobufCMessageInit) parental_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parental_feature_request__field_descriptors[8] =
{
  {
    "requestid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalFeatureRequest, has_requestid),
    offsetof(ParentalFeatureRequest, requestid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "family_groupid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalFeatureRequest, has_family_groupid),
    offsetof(ParentalFeatureRequest, family_groupid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steamid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalFeatureRequest, has_steamid),
    offsetof(ParentalFeatureRequest, steamid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "features",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalFeatureRequest, has_features),
    offsetof(ParentalFeatureRequest, features),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_requested",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalFeatureRequest, has_time_requested),
    offsetof(ParentalFeatureRequest, time_requested),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "approved",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ParentalFeatureRequest, has_approved),
    offsetof(ParentalFeatureRequest, approved),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steamid_responder",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalFeatureRequest, has_steamid_responder),
    offsetof(ParentalFeatureRequest, steamid_responder),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_responded",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalFeatureRequest, has_time_responded),
    offsetof(ParentalFeatureRequest, time_responded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parental_feature_request__field_indices_by_name[] = {
  5,   /* field[5] = approved */
  1,   /* field[1] = family_groupid */
  3,   /* field[3] = features */
  0,   /* field[0] = requestid */
  2,   /* field[2] = steamid */
  6,   /* field[6] = steamid_responder */
  4,   /* field[4] = time_requested */
  7,   /* field[7] = time_responded */
};
static const ProtobufCIntRange parental_feature_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor parental_feature_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParentalFeatureRequest",
  "ParentalFeatureRequest",
  "ParentalFeatureRequest",
  "",
  sizeof(ParentalFeatureRequest),
  8,
  parental_feature_request__field_descriptors,
  parental_feature_request__field_indices_by_name,
  1,  parental_feature_request__number_ranges,
  (ProtobufCMessageInit) parental_feature_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parental_playtime_request__field_descriptors[10] =
{
  {
    "requestid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalPlaytimeRequest, has_requestid),
    offsetof(ParentalPlaytimeRequest, requestid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "family_groupid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalPlaytimeRequest, has_family_groupid),
    offsetof(ParentalPlaytimeRequest, family_groupid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steamid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalPlaytimeRequest, has_steamid),
    offsetof(ParentalPlaytimeRequest, steamid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_playtime_restrictions",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ParentalPlaytimeRequest, current_playtime_restrictions),
    &parental_playtime_day__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_expires",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalPlaytimeRequest, has_time_expires),
    offsetof(ParentalPlaytimeRequest, time_expires),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_requested",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalPlaytimeRequest, has_time_requested),
    offsetof(ParentalPlaytimeRequest, time_requested),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "approved",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ParentalPlaytimeRequest, has_approved),
    offsetof(ParentalPlaytimeRequest, approved),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steamid_responder",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ParentalPlaytimeRequest, has_steamid_responder),
    offsetof(ParentalPlaytimeRequest, steamid_responder),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_responded",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ParentalPlaytimeRequest, has_time_responded),
    offsetof(ParentalPlaytimeRequest, time_responded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "restrictions_approved",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ParentalPlaytimeRequest, restrictions_approved),
    &parental_temporary_playtime_restrictions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parental_playtime_request__field_indices_by_name[] = {
  6,   /* field[6] = approved */
  3,   /* field[3] = current_playtime_restrictions */
  1,   /* field[1] = family_groupid */
  0,   /* field[0] = requestid */
  9,   /* field[9] = restrictions_approved */
  2,   /* field[2] = steamid */
  7,   /* field[7] = steamid_responder */
  4,   /* field[4] = time_expires */
  5,   /* field[5] = time_requested */
  8,   /* field[8] = time_responded */
};
static const ProtobufCIntRange parental_playtime_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor parental_playtime_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParentalPlaytimeRequest",
  "ParentalPlaytimeRequest",
  "ParentalPlaytimeRequest",
  "",
  sizeof(ParentalPlaytimeRequest),
  10,
  parental_playtime_request__field_descriptors,
  parental_playtime_request__field_indices_by_name,
  1,  parental_playtime_request__number_ranges,
  (ProtobufCMessageInit) parental_playtime_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
