/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_timedtrial.steamclient.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "steammessages_timedtrial.steamclient.pb-c.h"
void   ctimed_trial__get_time_remaining__request__init
                     (CTimedTrialGetTimeRemainingRequest         *message)
{
  static const CTimedTrialGetTimeRemainingRequest init_value = CTIMED_TRIAL__GET_TIME_REMAINING__REQUEST__INIT;
  *message = init_value;
}
size_t ctimed_trial__get_time_remaining__request__get_packed_size
                     (const CTimedTrialGetTimeRemainingRequest *message)
{
  assert(message->base.descriptor == &ctimed_trial__get_time_remaining__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ctimed_trial__get_time_remaining__request__pack
                     (const CTimedTrialGetTimeRemainingRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ctimed_trial__get_time_remaining__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ctimed_trial__get_time_remaining__request__pack_to_buffer
                     (const CTimedTrialGetTimeRemainingRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ctimed_trial__get_time_remaining__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTimedTrialGetTimeRemainingRequest *
       ctimed_trial__get_time_remaining__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTimedTrialGetTimeRemainingRequest *)
     protobuf_c_message_unpack (&ctimed_trial__get_time_remaining__request__descriptor,
                                allocator, len, data);
}
void   ctimed_trial__get_time_remaining__request__free_unpacked
                     (CTimedTrialGetTimeRemainingRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ctimed_trial__get_time_remaining__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ctimed_trial__get_time_remaining__response__init
                     (CTimedTrialGetTimeRemainingResponse         *message)
{
  static const CTimedTrialGetTimeRemainingResponse init_value = CTIMED_TRIAL__GET_TIME_REMAINING__RESPONSE__INIT;
  *message = init_value;
}
size_t ctimed_trial__get_time_remaining__response__get_packed_size
                     (const CTimedTrialGetTimeRemainingResponse *message)
{
  assert(message->base.descriptor == &ctimed_trial__get_time_remaining__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ctimed_trial__get_time_remaining__response__pack
                     (const CTimedTrialGetTimeRemainingResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ctimed_trial__get_time_remaining__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ctimed_trial__get_time_remaining__response__pack_to_buffer
                     (const CTimedTrialGetTimeRemainingResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ctimed_trial__get_time_remaining__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTimedTrialGetTimeRemainingResponse *
       ctimed_trial__get_time_remaining__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTimedTrialGetTimeRemainingResponse *)
     protobuf_c_message_unpack (&ctimed_trial__get_time_remaining__response__descriptor,
                                allocator, len, data);
}
void   ctimed_trial__get_time_remaining__response__free_unpacked
                     (CTimedTrialGetTimeRemainingResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ctimed_trial__get_time_remaining__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ctimed_trial__record_playtime__request__init
                     (CTimedTrialRecordPlaytimeRequest         *message)
{
  static const CTimedTrialRecordPlaytimeRequest init_value = CTIMED_TRIAL__RECORD_PLAYTIME__REQUEST__INIT;
  *message = init_value;
}
size_t ctimed_trial__record_playtime__request__get_packed_size
                     (const CTimedTrialRecordPlaytimeRequest *message)
{
  assert(message->base.descriptor == &ctimed_trial__record_playtime__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ctimed_trial__record_playtime__request__pack
                     (const CTimedTrialRecordPlaytimeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ctimed_trial__record_playtime__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ctimed_trial__record_playtime__request__pack_to_buffer
                     (const CTimedTrialRecordPlaytimeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ctimed_trial__record_playtime__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTimedTrialRecordPlaytimeRequest *
       ctimed_trial__record_playtime__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTimedTrialRecordPlaytimeRequest *)
     protobuf_c_message_unpack (&ctimed_trial__record_playtime__request__descriptor,
                                allocator, len, data);
}
void   ctimed_trial__record_playtime__request__free_unpacked
                     (CTimedTrialRecordPlaytimeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ctimed_trial__record_playtime__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ctimed_trial__record_playtime__response__init
                     (CTimedTrialRecordPlaytimeResponse         *message)
{
  static const CTimedTrialRecordPlaytimeResponse init_value = CTIMED_TRIAL__RECORD_PLAYTIME__RESPONSE__INIT;
  *message = init_value;
}
size_t ctimed_trial__record_playtime__response__get_packed_size
                     (const CTimedTrialRecordPlaytimeResponse *message)
{
  assert(message->base.descriptor == &ctimed_trial__record_playtime__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ctimed_trial__record_playtime__response__pack
                     (const CTimedTrialRecordPlaytimeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ctimed_trial__record_playtime__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ctimed_trial__record_playtime__response__pack_to_buffer
                     (const CTimedTrialRecordPlaytimeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ctimed_trial__record_playtime__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTimedTrialRecordPlaytimeResponse *
       ctimed_trial__record_playtime__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTimedTrialRecordPlaytimeResponse *)
     protobuf_c_message_unpack (&ctimed_trial__record_playtime__response__descriptor,
                                allocator, len, data);
}
void   ctimed_trial__record_playtime__response__free_unpacked
                     (CTimedTrialRecordPlaytimeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ctimed_trial__record_playtime__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ctimed_trial__reset_playtime__request__init
                     (CTimedTrialResetPlaytimeRequest         *message)
{
  static const CTimedTrialResetPlaytimeRequest init_value = CTIMED_TRIAL__RESET_PLAYTIME__REQUEST__INIT;
  *message = init_value;
}
size_t ctimed_trial__reset_playtime__request__get_packed_size
                     (const CTimedTrialResetPlaytimeRequest *message)
{
  assert(message->base.descriptor == &ctimed_trial__reset_playtime__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ctimed_trial__reset_playtime__request__pack
                     (const CTimedTrialResetPlaytimeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ctimed_trial__reset_playtime__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ctimed_trial__reset_playtime__request__pack_to_buffer
                     (const CTimedTrialResetPlaytimeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ctimed_trial__reset_playtime__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTimedTrialResetPlaytimeRequest *
       ctimed_trial__reset_playtime__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTimedTrialResetPlaytimeRequest *)
     protobuf_c_message_unpack (&ctimed_trial__reset_playtime__request__descriptor,
                                allocator, len, data);
}
void   ctimed_trial__reset_playtime__request__free_unpacked
                     (CTimedTrialResetPlaytimeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ctimed_trial__reset_playtime__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ctimed_trial__reset_playtime__response__init
                     (CTimedTrialResetPlaytimeResponse         *message)
{
  static const CTimedTrialResetPlaytimeResponse init_value = CTIMED_TRIAL__RESET_PLAYTIME__RESPONSE__INIT;
  *message = init_value;
}
size_t ctimed_trial__reset_playtime__response__get_packed_size
                     (const CTimedTrialResetPlaytimeResponse *message)
{
  assert(message->base.descriptor == &ctimed_trial__reset_playtime__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ctimed_trial__reset_playtime__response__pack
                     (const CTimedTrialResetPlaytimeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ctimed_trial__reset_playtime__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ctimed_trial__reset_playtime__response__pack_to_buffer
                     (const CTimedTrialResetPlaytimeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ctimed_trial__reset_playtime__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTimedTrialResetPlaytimeResponse *
       ctimed_trial__reset_playtime__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTimedTrialResetPlaytimeResponse *)
     protobuf_c_message_unpack (&ctimed_trial__reset_playtime__response__descriptor,
                                allocator, len, data);
}
void   ctimed_trial__reset_playtime__response__free_unpacked
                     (CTimedTrialResetPlaytimeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ctimed_trial__reset_playtime__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ctimed_trial__get_time_remaining__request__field_descriptors[1] =
{
  {
    "appid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialGetTimeRemainingRequest, has_appid),
    offsetof(CTimedTrialGetTimeRemainingRequest, appid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ctimed_trial__get_time_remaining__request__field_indices_by_name[] = {
  0,   /* field[0] = appid */
};
static const ProtobufCIntRange ctimed_trial__get_time_remaining__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ctimed_trial__get_time_remaining__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CTimedTrial_GetTimeRemaining_Request",
  "CTimedTrialGetTimeRemainingRequest",
  "CTimedTrialGetTimeRemainingRequest",
  "",
  sizeof(CTimedTrialGetTimeRemainingRequest),
  1,
  ctimed_trial__get_time_remaining__request__field_descriptors,
  ctimed_trial__get_time_remaining__request__field_indices_by_name,
  1,  ctimed_trial__get_time_remaining__request__number_ranges,
  (ProtobufCMessageInit) ctimed_trial__get_time_remaining__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ctimed_trial__get_time_remaining__response__field_descriptors[4] =
{
  {
    "seconds_played",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialGetTimeRemainingResponse, has_seconds_played),
    offsetof(CTimedTrialGetTimeRemainingResponse, seconds_played),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seconds_allowed",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialGetTimeRemainingResponse, has_seconds_allowed),
    offsetof(CTimedTrialGetTimeRemainingResponse, seconds_allowed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packageid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialGetTimeRemainingResponse, has_packageid),
    offsetof(CTimedTrialGetTimeRemainingResponse, packageid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mastersub_appid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialGetTimeRemainingResponse, has_mastersub_appid),
    offsetof(CTimedTrialGetTimeRemainingResponse, mastersub_appid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ctimed_trial__get_time_remaining__response__field_indices_by_name[] = {
  3,   /* field[3] = mastersub_appid */
  2,   /* field[2] = packageid */
  1,   /* field[1] = seconds_allowed */
  0,   /* field[0] = seconds_played */
};
static const ProtobufCIntRange ctimed_trial__get_time_remaining__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ctimed_trial__get_time_remaining__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CTimedTrial_GetTimeRemaining_Response",
  "CTimedTrialGetTimeRemainingResponse",
  "CTimedTrialGetTimeRemainingResponse",
  "",
  sizeof(CTimedTrialGetTimeRemainingResponse),
  4,
  ctimed_trial__get_time_remaining__response__field_descriptors,
  ctimed_trial__get_time_remaining__response__field_indices_by_name,
  1,  ctimed_trial__get_time_remaining__response__number_ranges,
  (ProtobufCMessageInit) ctimed_trial__get_time_remaining__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ctimed_trial__record_playtime__request__field_descriptors[2] =
{
  {
    "appid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialRecordPlaytimeRequest, has_appid),
    offsetof(CTimedTrialRecordPlaytimeRequest, appid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seconds_played",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialRecordPlaytimeRequest, has_seconds_played),
    offsetof(CTimedTrialRecordPlaytimeRequest, seconds_played),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ctimed_trial__record_playtime__request__field_indices_by_name[] = {
  0,   /* field[0] = appid */
  1,   /* field[1] = seconds_played */
};
static const ProtobufCIntRange ctimed_trial__record_playtime__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ctimed_trial__record_playtime__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CTimedTrial_RecordPlaytime_Request",
  "CTimedTrialRecordPlaytimeRequest",
  "CTimedTrialRecordPlaytimeRequest",
  "",
  sizeof(CTimedTrialRecordPlaytimeRequest),
  2,
  ctimed_trial__record_playtime__request__field_descriptors,
  ctimed_trial__record_playtime__request__field_indices_by_name,
  1,  ctimed_trial__record_playtime__request__number_ranges,
  (ProtobufCMessageInit) ctimed_trial__record_playtime__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ctimed_trial__record_playtime__response__field_descriptors[2] =
{
  {
    "seconds_played",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialRecordPlaytimeResponse, has_seconds_played),
    offsetof(CTimedTrialRecordPlaytimeResponse, seconds_played),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seconds_allowed",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialRecordPlaytimeResponse, has_seconds_allowed),
    offsetof(CTimedTrialRecordPlaytimeResponse, seconds_allowed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ctimed_trial__record_playtime__response__field_indices_by_name[] = {
  1,   /* field[1] = seconds_allowed */
  0,   /* field[0] = seconds_played */
};
static const ProtobufCIntRange ctimed_trial__record_playtime__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ctimed_trial__record_playtime__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CTimedTrial_RecordPlaytime_Response",
  "CTimedTrialRecordPlaytimeResponse",
  "CTimedTrialRecordPlaytimeResponse",
  "",
  sizeof(CTimedTrialRecordPlaytimeResponse),
  2,
  ctimed_trial__record_playtime__response__field_descriptors,
  ctimed_trial__record_playtime__response__field_indices_by_name,
  1,  ctimed_trial__record_playtime__response__number_ranges,
  (ProtobufCMessageInit) ctimed_trial__record_playtime__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ctimed_trial__reset_playtime__request__field_descriptors[1] =
{
  {
    "appid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialResetPlaytimeRequest, has_appid),
    offsetof(CTimedTrialResetPlaytimeRequest, appid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ctimed_trial__reset_playtime__request__field_indices_by_name[] = {
  0,   /* field[0] = appid */
};
static const ProtobufCIntRange ctimed_trial__reset_playtime__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ctimed_trial__reset_playtime__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CTimedTrial_ResetPlaytime_Request",
  "CTimedTrialResetPlaytimeRequest",
  "CTimedTrialResetPlaytimeRequest",
  "",
  sizeof(CTimedTrialResetPlaytimeRequest),
  1,
  ctimed_trial__reset_playtime__request__field_descriptors,
  ctimed_trial__reset_playtime__request__field_indices_by_name,
  1,  ctimed_trial__reset_playtime__request__number_ranges,
  (ProtobufCMessageInit) ctimed_trial__reset_playtime__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ctimed_trial__reset_playtime__response__field_descriptors[2] =
{
  {
    "seconds_played",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialResetPlaytimeResponse, has_seconds_played),
    offsetof(CTimedTrialResetPlaytimeResponse, seconds_played),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seconds_allowed",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CTimedTrialResetPlaytimeResponse, has_seconds_allowed),
    offsetof(CTimedTrialResetPlaytimeResponse, seconds_allowed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ctimed_trial__reset_playtime__response__field_indices_by_name[] = {
  1,   /* field[1] = seconds_allowed */
  0,   /* field[0] = seconds_played */
};
static const ProtobufCIntRange ctimed_trial__reset_playtime__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ctimed_trial__reset_playtime__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CTimedTrial_ResetPlaytime_Response",
  "CTimedTrialResetPlaytimeResponse",
  "CTimedTrialResetPlaytimeResponse",
  "",
  sizeof(CTimedTrialResetPlaytimeResponse),
  2,
  ctimed_trial__reset_playtime__response__field_descriptors,
  ctimed_trial__reset_playtime__response__field_indices_by_name,
  1,  ctimed_trial__reset_playtime__response__number_ranges,
  (ProtobufCMessageInit) ctimed_trial__reset_playtime__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor timed_trial__method_descriptors[3] =
{
  { "GetTimeRemaining", &ctimed_trial__get_time_remaining__request__descriptor, &ctimed_trial__get_time_remaining__response__descriptor },
  { "RecordPlaytime", &ctimed_trial__record_playtime__request__descriptor, &ctimed_trial__record_playtime__response__descriptor },
  { "ResetPlaytime", &ctimed_trial__reset_playtime__request__descriptor, &ctimed_trial__reset_playtime__response__descriptor },
};
const unsigned timed_trial__method_indices_by_name[] = {
  0,        /* GetTimeRemaining */
  1,        /* RecordPlaytime */
  2         /* ResetPlaytime */
};
const ProtobufCServiceDescriptor timed_trial__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "TimedTrial",
  "TimedTrial",
  "TimedTrial",
  "",
  3,
  timed_trial__method_descriptors,
  timed_trial__method_indices_by_name
};
void timed_trial__get_time_remaining(ProtobufCService *service,
                                     const CTimedTrialGetTimeRemainingRequest *input,
                                     CTimedTrialGetTimeRemainingResponse_Closure closure,
                                     void *closure_data)
{
  assert(service->descriptor == &timed_trial__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void timed_trial__record_playtime(ProtobufCService *service,
                                  const CTimedTrialRecordPlaytimeRequest *input,
                                  CTimedTrialRecordPlaytimeResponse_Closure closure,
                                  void *closure_data)
{
  assert(service->descriptor == &timed_trial__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void timed_trial__reset_playtime(ProtobufCService *service,
                                 const CTimedTrialResetPlaytimeRequest *input,
                                 CTimedTrialResetPlaytimeResponse_Closure closure,
                                 void *closure_data)
{
  assert(service->descriptor == &timed_trial__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void timed_trial__init (TimedTrial_Service *service,
                        TimedTrial_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &timed_trial__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
