/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_childprocessquery.proto */

#ifndef PROTOBUF_C_steammessages_5fchildprocessquery_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5fchildprocessquery_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "enums.pb-c.h"

typedef struct CMsgChildProcessQueryResponse CMsgChildProcessQueryResponse;
typedef struct CMsgChildProcessQueryGpuTopology CMsgChildProcessQueryGpuTopology;
typedef struct CMsgChildProcessQueryGpuTopology__GpuInfo CMsgChildProcessQueryGpuTopology__GpuInfo;


/* --- enums --- */

typedef enum _EChildProcessQueryCommand {
  ECHILD_PROCESS_QUERY_COMMAND__k_EChildProcessQueryCommand_Invalid = 0,
  ECHILD_PROCESS_QUERY_COMMAND__k_EChildProcessQueryCommand_GpuTopology = 1,
  ECHILD_PROCESS_QUERY_COMMAND__k_EChildProcessQueryCommand_Max = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ECHILD_PROCESS_QUERY_COMMAND)
} EChildProcessQueryCommand;

/* --- messages --- */

typedef enum {
  CMSG_CHILD_PROCESS_QUERY_RESPONSE__RESPONSE__NOT_SET = 0,
  CMSG_CHILD_PROCESS_QUERY_RESPONSE__RESPONSE_GPU_TOPOLOGY = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CMSG_CHILD_PROCESS_QUERY_RESPONSE__RESPONSE__CASE)
} CMsgChildProcessQueryResponse__ResponseCase;

struct  CMsgChildProcessQueryResponse
{
  ProtobufCMessage base;
  CMsgChildProcessQueryResponse__ResponseCase response_case;
  union {
    CMsgChildProcessQueryGpuTopology *gpu_topology;
  };
};
#define CMSG_CHILD_PROCESS_QUERY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_child_process_query_response__descriptor) \
, CMSG_CHILD_PROCESS_QUERY_RESPONSE__RESPONSE__NOT_SET, {0} }


struct  CMsgChildProcessQueryGpuTopology__GpuInfo
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  uint32_t id;
  char *name;
  protobuf_c_boolean has_vram_size_bytes;
  uint64_t vram_size_bytes;
  protobuf_c_boolean has_driver_id;
  EGpuDriverId driver_id;
  protobuf_c_boolean has_driver_version_major;
  int32_t driver_version_major;
  protobuf_c_boolean has_driver_version_minor;
  int32_t driver_version_minor;
  protobuf_c_boolean has_driver_version_patch;
  int32_t driver_version_patch;
  protobuf_c_boolean has_luid;
  uint64_t luid;
};
#define CMSG_CHILD_PROCESS_QUERY_GPU_TOPOLOGY__GPU_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_child_process_query_gpu_topology__gpu_info__descriptor) \
, 0, 0, NULL, 0, 0, 0, EGPU_DRIVER_ID__k_EGpuDriverId_Invalid, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CMsgChildProcessQueryGpuTopology
{
  ProtobufCMessage base;
  size_t n_gpus;
  CMsgChildProcessQueryGpuTopology__GpuInfo **gpus;
  protobuf_c_boolean has_default_gpu_id;
  uint32_t default_gpu_id;
};
#define CMSG_CHILD_PROCESS_QUERY_GPU_TOPOLOGY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_child_process_query_gpu_topology__descriptor) \
, 0,NULL, 0, 0 }


/* CMsgChildProcessQueryResponse methods */
void   cmsg_child_process_query_response__init
                     (CMsgChildProcessQueryResponse         *message);
size_t cmsg_child_process_query_response__get_packed_size
                     (const CMsgChildProcessQueryResponse   *message);
size_t cmsg_child_process_query_response__pack
                     (const CMsgChildProcessQueryResponse   *message,
                      uint8_t             *out);
size_t cmsg_child_process_query_response__pack_to_buffer
                     (const CMsgChildProcessQueryResponse   *message,
                      ProtobufCBuffer     *buffer);
CMsgChildProcessQueryResponse *
       cmsg_child_process_query_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_child_process_query_response__free_unpacked
                     (CMsgChildProcessQueryResponse *message,
                      ProtobufCAllocator *allocator);
/* CMsgChildProcessQueryGpuTopology__GpuInfo methods */
void   cmsg_child_process_query_gpu_topology__gpu_info__init
                     (CMsgChildProcessQueryGpuTopology__GpuInfo         *message);
/* CMsgChildProcessQueryGpuTopology methods */
void   cmsg_child_process_query_gpu_topology__init
                     (CMsgChildProcessQueryGpuTopology         *message);
size_t cmsg_child_process_query_gpu_topology__get_packed_size
                     (const CMsgChildProcessQueryGpuTopology   *message);
size_t cmsg_child_process_query_gpu_topology__pack
                     (const CMsgChildProcessQueryGpuTopology   *message,
                      uint8_t             *out);
size_t cmsg_child_process_query_gpu_topology__pack_to_buffer
                     (const CMsgChildProcessQueryGpuTopology   *message,
                      ProtobufCBuffer     *buffer);
CMsgChildProcessQueryGpuTopology *
       cmsg_child_process_query_gpu_topology__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_child_process_query_gpu_topology__free_unpacked
                     (CMsgChildProcessQueryGpuTopology *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CMsgChildProcessQueryResponse_Closure)
                 (const CMsgChildProcessQueryResponse *message,
                  void *closure_data);
typedef void (*CMsgChildProcessQueryGpuTopology__GpuInfo_Closure)
                 (const CMsgChildProcessQueryGpuTopology__GpuInfo *message,
                  void *closure_data);
typedef void (*CMsgChildProcessQueryGpuTopology_Closure)
                 (const CMsgChildProcessQueryGpuTopology *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    echild_process_query_command__descriptor;
extern const ProtobufCMessageDescriptor cmsg_child_process_query_response__descriptor;
extern const ProtobufCMessageDescriptor cmsg_child_process_query_gpu_topology__descriptor;
extern const ProtobufCMessageDescriptor cmsg_child_process_query_gpu_topology__gpu_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5fchildprocessquery_2eproto__INCLUDED */
