/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_timedtrial.steamclient.proto */

#ifndef PROTOBUF_C_steammessages_5ftimedtrial_2esteamclient_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5ftimedtrial_2esteamclient_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "steammessages_unified_base.steamclient.pb-c.h"

typedef struct CTimedTrialGetTimeRemainingRequest CTimedTrialGetTimeRemainingRequest;
typedef struct CTimedTrialGetTimeRemainingResponse CTimedTrialGetTimeRemainingResponse;
typedef struct CTimedTrialRecordPlaytimeRequest CTimedTrialRecordPlaytimeRequest;
typedef struct CTimedTrialRecordPlaytimeResponse CTimedTrialRecordPlaytimeResponse;
typedef struct CTimedTrialResetPlaytimeRequest CTimedTrialResetPlaytimeRequest;
typedef struct CTimedTrialResetPlaytimeResponse CTimedTrialResetPlaytimeResponse;


/* --- enums --- */


/* --- messages --- */

struct  CTimedTrialGetTimeRemainingRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
};
#define CTIMED_TRIAL__GET_TIME_REMAINING__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctimed_trial__get_time_remaining__request__descriptor) \
, 0, 0 }


struct  CTimedTrialGetTimeRemainingResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_seconds_played;
  uint32_t seconds_played;
  protobuf_c_boolean has_seconds_allowed;
  uint32_t seconds_allowed;
  protobuf_c_boolean has_packageid;
  uint32_t packageid;
  protobuf_c_boolean has_mastersub_appid;
  uint32_t mastersub_appid;
};
#define CTIMED_TRIAL__GET_TIME_REMAINING__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctimed_trial__get_time_remaining__response__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CTimedTrialRecordPlaytimeRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_seconds_played;
  uint32_t seconds_played;
};
#define CTIMED_TRIAL__RECORD_PLAYTIME__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctimed_trial__record_playtime__request__descriptor) \
, 0, 0, 0, 0 }


struct  CTimedTrialRecordPlaytimeResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_seconds_played;
  uint32_t seconds_played;
  protobuf_c_boolean has_seconds_allowed;
  uint32_t seconds_allowed;
};
#define CTIMED_TRIAL__RECORD_PLAYTIME__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctimed_trial__record_playtime__response__descriptor) \
, 0, 0, 0, 0 }


struct  CTimedTrialResetPlaytimeRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
};
#define CTIMED_TRIAL__RESET_PLAYTIME__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctimed_trial__reset_playtime__request__descriptor) \
, 0, 0 }


struct  CTimedTrialResetPlaytimeResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_seconds_played;
  uint32_t seconds_played;
  protobuf_c_boolean has_seconds_allowed;
  uint32_t seconds_allowed;
};
#define CTIMED_TRIAL__RESET_PLAYTIME__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctimed_trial__reset_playtime__response__descriptor) \
, 0, 0, 0, 0 }


/* CTimedTrialGetTimeRemainingRequest methods */
void   ctimed_trial__get_time_remaining__request__init
                     (CTimedTrialGetTimeRemainingRequest         *message);
size_t ctimed_trial__get_time_remaining__request__get_packed_size
                     (const CTimedTrialGetTimeRemainingRequest   *message);
size_t ctimed_trial__get_time_remaining__request__pack
                     (const CTimedTrialGetTimeRemainingRequest   *message,
                      uint8_t             *out);
size_t ctimed_trial__get_time_remaining__request__pack_to_buffer
                     (const CTimedTrialGetTimeRemainingRequest   *message,
                      ProtobufCBuffer     *buffer);
CTimedTrialGetTimeRemainingRequest *
       ctimed_trial__get_time_remaining__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctimed_trial__get_time_remaining__request__free_unpacked
                     (CTimedTrialGetTimeRemainingRequest *message,
                      ProtobufCAllocator *allocator);
/* CTimedTrialGetTimeRemainingResponse methods */
void   ctimed_trial__get_time_remaining__response__init
                     (CTimedTrialGetTimeRemainingResponse         *message);
size_t ctimed_trial__get_time_remaining__response__get_packed_size
                     (const CTimedTrialGetTimeRemainingResponse   *message);
size_t ctimed_trial__get_time_remaining__response__pack
                     (const CTimedTrialGetTimeRemainingResponse   *message,
                      uint8_t             *out);
size_t ctimed_trial__get_time_remaining__response__pack_to_buffer
                     (const CTimedTrialGetTimeRemainingResponse   *message,
                      ProtobufCBuffer     *buffer);
CTimedTrialGetTimeRemainingResponse *
       ctimed_trial__get_time_remaining__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctimed_trial__get_time_remaining__response__free_unpacked
                     (CTimedTrialGetTimeRemainingResponse *message,
                      ProtobufCAllocator *allocator);
/* CTimedTrialRecordPlaytimeRequest methods */
void   ctimed_trial__record_playtime__request__init
                     (CTimedTrialRecordPlaytimeRequest         *message);
size_t ctimed_trial__record_playtime__request__get_packed_size
                     (const CTimedTrialRecordPlaytimeRequest   *message);
size_t ctimed_trial__record_playtime__request__pack
                     (const CTimedTrialRecordPlaytimeRequest   *message,
                      uint8_t             *out);
size_t ctimed_trial__record_playtime__request__pack_to_buffer
                     (const CTimedTrialRecordPlaytimeRequest   *message,
                      ProtobufCBuffer     *buffer);
CTimedTrialRecordPlaytimeRequest *
       ctimed_trial__record_playtime__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctimed_trial__record_playtime__request__free_unpacked
                     (CTimedTrialRecordPlaytimeRequest *message,
                      ProtobufCAllocator *allocator);
/* CTimedTrialRecordPlaytimeResponse methods */
void   ctimed_trial__record_playtime__response__init
                     (CTimedTrialRecordPlaytimeResponse         *message);
size_t ctimed_trial__record_playtime__response__get_packed_size
                     (const CTimedTrialRecordPlaytimeResponse   *message);
size_t ctimed_trial__record_playtime__response__pack
                     (const CTimedTrialRecordPlaytimeResponse   *message,
                      uint8_t             *out);
size_t ctimed_trial__record_playtime__response__pack_to_buffer
                     (const CTimedTrialRecordPlaytimeResponse   *message,
                      ProtobufCBuffer     *buffer);
CTimedTrialRecordPlaytimeResponse *
       ctimed_trial__record_playtime__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctimed_trial__record_playtime__response__free_unpacked
                     (CTimedTrialRecordPlaytimeResponse *message,
                      ProtobufCAllocator *allocator);
/* CTimedTrialResetPlaytimeRequest methods */
void   ctimed_trial__reset_playtime__request__init
                     (CTimedTrialResetPlaytimeRequest         *message);
size_t ctimed_trial__reset_playtime__request__get_packed_size
                     (const CTimedTrialResetPlaytimeRequest   *message);
size_t ctimed_trial__reset_playtime__request__pack
                     (const CTimedTrialResetPlaytimeRequest   *message,
                      uint8_t             *out);
size_t ctimed_trial__reset_playtime__request__pack_to_buffer
                     (const CTimedTrialResetPlaytimeRequest   *message,
                      ProtobufCBuffer     *buffer);
CTimedTrialResetPlaytimeRequest *
       ctimed_trial__reset_playtime__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctimed_trial__reset_playtime__request__free_unpacked
                     (CTimedTrialResetPlaytimeRequest *message,
                      ProtobufCAllocator *allocator);
/* CTimedTrialResetPlaytimeResponse methods */
void   ctimed_trial__reset_playtime__response__init
                     (CTimedTrialResetPlaytimeResponse         *message);
size_t ctimed_trial__reset_playtime__response__get_packed_size
                     (const CTimedTrialResetPlaytimeResponse   *message);
size_t ctimed_trial__reset_playtime__response__pack
                     (const CTimedTrialResetPlaytimeResponse   *message,
                      uint8_t             *out);
size_t ctimed_trial__reset_playtime__response__pack_to_buffer
                     (const CTimedTrialResetPlaytimeResponse   *message,
                      ProtobufCBuffer     *buffer);
CTimedTrialResetPlaytimeResponse *
       ctimed_trial__reset_playtime__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctimed_trial__reset_playtime__response__free_unpacked
                     (CTimedTrialResetPlaytimeResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CTimedTrialGetTimeRemainingRequest_Closure)
                 (const CTimedTrialGetTimeRemainingRequest *message,
                  void *closure_data);
typedef void (*CTimedTrialGetTimeRemainingResponse_Closure)
                 (const CTimedTrialGetTimeRemainingResponse *message,
                  void *closure_data);
typedef void (*CTimedTrialRecordPlaytimeRequest_Closure)
                 (const CTimedTrialRecordPlaytimeRequest *message,
                  void *closure_data);
typedef void (*CTimedTrialRecordPlaytimeResponse_Closure)
                 (const CTimedTrialRecordPlaytimeResponse *message,
                  void *closure_data);
typedef void (*CTimedTrialResetPlaytimeRequest_Closure)
                 (const CTimedTrialResetPlaytimeRequest *message,
                  void *closure_data);
typedef void (*CTimedTrialResetPlaytimeResponse_Closure)
                 (const CTimedTrialResetPlaytimeResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct TimedTrial_Service TimedTrial_Service;
struct TimedTrial_Service
{
  ProtobufCService base;
  void (*get_time_remaining)(TimedTrial_Service *service,
                             const CTimedTrialGetTimeRemainingRequest *input,
                             CTimedTrialGetTimeRemainingResponse_Closure closure,
                             void *closure_data);
  void (*record_playtime)(TimedTrial_Service *service,
                          const CTimedTrialRecordPlaytimeRequest *input,
                          CTimedTrialRecordPlaytimeResponse_Closure closure,
                          void *closure_data);
  void (*reset_playtime)(TimedTrial_Service *service,
                         const CTimedTrialResetPlaytimeRequest *input,
                         CTimedTrialResetPlaytimeResponse_Closure closure,
                         void *closure_data);
};
typedef void (*TimedTrial_ServiceDestroy)(TimedTrial_Service *);
void timed_trial__init (TimedTrial_Service *service,
                        TimedTrial_ServiceDestroy destroy);
#define TIMED_TRIAL__BASE_INIT \
    { &timed_trial__descriptor, protobuf_c_service_invoke_internal, NULL }
#define TIMED_TRIAL__INIT(function_prefix__) \
    { TIMED_TRIAL__BASE_INIT,\
      function_prefix__ ## get_time_remaining,\
      function_prefix__ ## record_playtime,\
      function_prefix__ ## reset_playtime  }
void timed_trial__get_time_remaining(ProtobufCService *service,
                                     const CTimedTrialGetTimeRemainingRequest *input,
                                     CTimedTrialGetTimeRemainingResponse_Closure closure,
                                     void *closure_data);
void timed_trial__record_playtime(ProtobufCService *service,
                                  const CTimedTrialRecordPlaytimeRequest *input,
                                  CTimedTrialRecordPlaytimeResponse_Closure closure,
                                  void *closure_data);
void timed_trial__reset_playtime(ProtobufCService *service,
                                 const CTimedTrialResetPlaytimeRequest *input,
                                 CTimedTrialResetPlaytimeResponse_Closure closure,
                                 void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ctimed_trial__get_time_remaining__request__descriptor;
extern const ProtobufCMessageDescriptor ctimed_trial__get_time_remaining__response__descriptor;
extern const ProtobufCMessageDescriptor ctimed_trial__record_playtime__request__descriptor;
extern const ProtobufCMessageDescriptor ctimed_trial__record_playtime__response__descriptor;
extern const ProtobufCMessageDescriptor ctimed_trial__reset_playtime__request__descriptor;
extern const ProtobufCMessageDescriptor ctimed_trial__reset_playtime__response__descriptor;
extern const ProtobufCServiceDescriptor timed_trial__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5ftimedtrial_2esteamclient_2eproto__INCLUDED */
