/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_market.steamclient.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "steammessages_market.steamclient.pb-c.h"
void   cecon_market__is_marketplace_allowed__request__init
                     (CEconMarketIsMarketplaceAllowedRequest         *message)
{
  static const CEconMarketIsMarketplaceAllowedRequest init_value = CECON_MARKET__IS_MARKETPLACE_ALLOWED__REQUEST__INIT;
  *message = init_value;
}
size_t cecon_market__is_marketplace_allowed__request__get_packed_size
                     (const CEconMarketIsMarketplaceAllowedRequest *message)
{
  assert(message->base.descriptor == &cecon_market__is_marketplace_allowed__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cecon_market__is_marketplace_allowed__request__pack
                     (const CEconMarketIsMarketplaceAllowedRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cecon_market__is_marketplace_allowed__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cecon_market__is_marketplace_allowed__request__pack_to_buffer
                     (const CEconMarketIsMarketplaceAllowedRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cecon_market__is_marketplace_allowed__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CEconMarketIsMarketplaceAllowedRequest *
       cecon_market__is_marketplace_allowed__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CEconMarketIsMarketplaceAllowedRequest *)
     protobuf_c_message_unpack (&cecon_market__is_marketplace_allowed__request__descriptor,
                                allocator, len, data);
}
void   cecon_market__is_marketplace_allowed__request__free_unpacked
                     (CEconMarketIsMarketplaceAllowedRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cecon_market__is_marketplace_allowed__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cecon_market__is_marketplace_allowed__response__init
                     (CEconMarketIsMarketplaceAllowedResponse         *message)
{
  static const CEconMarketIsMarketplaceAllowedResponse init_value = CECON_MARKET__IS_MARKETPLACE_ALLOWED__RESPONSE__INIT;
  *message = init_value;
}
size_t cecon_market__is_marketplace_allowed__response__get_packed_size
                     (const CEconMarketIsMarketplaceAllowedResponse *message)
{
  assert(message->base.descriptor == &cecon_market__is_marketplace_allowed__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cecon_market__is_marketplace_allowed__response__pack
                     (const CEconMarketIsMarketplaceAllowedResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cecon_market__is_marketplace_allowed__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cecon_market__is_marketplace_allowed__response__pack_to_buffer
                     (const CEconMarketIsMarketplaceAllowedResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cecon_market__is_marketplace_allowed__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CEconMarketIsMarketplaceAllowedResponse *
       cecon_market__is_marketplace_allowed__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CEconMarketIsMarketplaceAllowedResponse *)
     protobuf_c_message_unpack (&cecon_market__is_marketplace_allowed__response__descriptor,
                                allocator, len, data);
}
void   cecon_market__is_marketplace_allowed__response__free_unpacked
                     (CEconMarketIsMarketplaceAllowedResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cecon_market__is_marketplace_allowed__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cecon_market__is_marketplace_allowed__request__field_descriptors[1] =
{
  {
    "webcookie",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CEconMarketIsMarketplaceAllowedRequest, webcookie),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cecon_market__is_marketplace_allowed__request__field_indices_by_name[] = {
  0,   /* field[0] = webcookie */
};
static const ProtobufCIntRange cecon_market__is_marketplace_allowed__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cecon_market__is_marketplace_allowed__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CEconMarket_IsMarketplaceAllowed_Request",
  "CEconMarketIsMarketplaceAllowedRequest",
  "CEconMarketIsMarketplaceAllowedRequest",
  "",
  sizeof(CEconMarketIsMarketplaceAllowedRequest),
  1,
  cecon_market__is_marketplace_allowed__request__field_descriptors,
  cecon_market__is_marketplace_allowed__request__field_indices_by_name,
  1,  cecon_market__is_marketplace_allowed__request__number_ranges,
  (ProtobufCMessageInit) cecon_market__is_marketplace_allowed__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cecon_market__is_marketplace_allowed__response__field_descriptors[7] =
{
  {
    "allowed",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CEconMarketIsMarketplaceAllowedResponse, has_allowed),
    offsetof(CEconMarketIsMarketplaceAllowedResponse, allowed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reason",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CEconMarketIsMarketplaceAllowedResponse, has_reason),
    offsetof(CEconMarketIsMarketplaceAllowedResponse, reason),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allowed_at_time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CEconMarketIsMarketplaceAllowedResponse, has_allowed_at_time),
    offsetof(CEconMarketIsMarketplaceAllowedResponse, allowed_at_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steamguard_required_days",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CEconMarketIsMarketplaceAllowedResponse, has_steamguard_required_days),
    offsetof(CEconMarketIsMarketplaceAllowedResponse, steamguard_required_days),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forms_requested",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CEconMarketIsMarketplaceAllowedResponse, has_forms_requested),
    offsetof(CEconMarketIsMarketplaceAllowedResponse, forms_requested),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forms_require_verification",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CEconMarketIsMarketplaceAllowedResponse, has_forms_require_verification),
    offsetof(CEconMarketIsMarketplaceAllowedResponse, forms_require_verification),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_device_cooldown_days",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CEconMarketIsMarketplaceAllowedResponse, has_new_device_cooldown_days),
    offsetof(CEconMarketIsMarketplaceAllowedResponse, new_device_cooldown_days),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cecon_market__is_marketplace_allowed__response__field_indices_by_name[] = {
  0,   /* field[0] = allowed */
  2,   /* field[2] = allowed_at_time */
  4,   /* field[4] = forms_requested */
  5,   /* field[5] = forms_require_verification */
  6,   /* field[6] = new_device_cooldown_days */
  1,   /* field[1] = reason */
  3,   /* field[3] = steamguard_required_days */
};
static const ProtobufCIntRange cecon_market__is_marketplace_allowed__response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 7, 4 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor cecon_market__is_marketplace_allowed__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CEconMarket_IsMarketplaceAllowed_Response",
  "CEconMarketIsMarketplaceAllowedResponse",
  "CEconMarketIsMarketplaceAllowedResponse",
  "",
  sizeof(CEconMarketIsMarketplaceAllowedResponse),
  7,
  cecon_market__is_marketplace_allowed__response__field_descriptors,
  cecon_market__is_marketplace_allowed__response__field_indices_by_name,
  2,  cecon_market__is_marketplace_allowed__response__number_ranges,
  (ProtobufCMessageInit) cecon_market__is_marketplace_allowed__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor econ_market__method_descriptors[1] =
{
  { "IsMarketplaceAllowed", &cecon_market__is_marketplace_allowed__request__descriptor, &cecon_market__is_marketplace_allowed__response__descriptor },
};
const unsigned econ_market__method_indices_by_name[] = {
  0         /* IsMarketplaceAllowed */
};
const ProtobufCServiceDescriptor econ_market__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "EconMarket",
  "EconMarket",
  "EconMarket",
  "",
  1,
  econ_market__method_descriptors,
  econ_market__method_indices_by_name
};
void econ_market__is_marketplace_allowed(ProtobufCService *service,
                                         const CEconMarketIsMarketplaceAllowedRequest *input,
                                         CEconMarketIsMarketplaceAllowedResponse_Closure closure,
                                         void *closure_data)
{
  assert(service->descriptor == &econ_market__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void econ_market__init (EconMarket_Service *service,
                        EconMarket_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &econ_market__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
