/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_appoverview.proto */

#ifndef PROTOBUF_C_steammessages_5fappoverview_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5fappoverview_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "enums.pb-c.h"

typedef struct CAppOverviewPerClientData CAppOverviewPerClientData;
typedef struct CAppOverview CAppOverview;
typedef struct CAppOverviewChange CAppOverviewChange;


/* --- enums --- */

typedef enum _EDisplayStatus {
  EDISPLAY_STATUS__k_EDisplayStatusInvalid = 0,
  EDISPLAY_STATUS__k_EDisplayStatusLaunching = 1,
  EDISPLAY_STATUS__k_EDisplayStatusUninstalling = 2,
  EDISPLAY_STATUS__k_EDisplayStatusInstalling = 3,
  EDISPLAY_STATUS__k_EDisplayStatusRunning = 4,
  EDISPLAY_STATUS__k_EDisplayStatusValidating = 5,
  EDISPLAY_STATUS__k_EDisplayStatusUpdating = 6,
  EDISPLAY_STATUS__k_EDisplayStatusDownloading = 7,
  EDISPLAY_STATUS__k_EDisplayStatusSynchronizing = 8,
  EDISPLAY_STATUS__k_EDisplayStatusReadyToInstall = 9,
  EDISPLAY_STATUS__k_EDisplayStatusReadyToPreload = 10,
  EDISPLAY_STATUS__k_EDisplayStatusReadyToLaunch = 11,
  EDISPLAY_STATUS__k_EDisplayStatusRegionRestricted = 12,
  EDISPLAY_STATUS__k_EDisplayStatusPresaleOnly = 13,
  EDISPLAY_STATUS__k_EDisplayStatusInvalidPlatform = 14,
  EDISPLAY_STATUS__k_EDisplayStatusPreloadComplete = 16,
  EDISPLAY_STATUS__k_EDisplayStatusBorrowerLocked = 17,
  EDISPLAY_STATUS__k_EDisplayStatusUpdatePaused = 18,
  EDISPLAY_STATUS__k_EDisplayStatusUpdateQueued = 19,
  EDISPLAY_STATUS__k_EDisplayStatusUpdateRequired = 20,
  EDISPLAY_STATUS__k_EDisplayStatusUpdateDisabled = 21,
  EDISPLAY_STATUS__k_EDisplayStatusDownloadPaused = 22,
  EDISPLAY_STATUS__k_EDisplayStatusDownloadQueued = 23,
  EDISPLAY_STATUS__k_EDisplayStatusDownloadRequired = 24,
  EDISPLAY_STATUS__k_EDisplayStatusDownloadDisabled = 25,
  EDISPLAY_STATUS__k_EDisplayStatusLicensePending = 26,
  EDISPLAY_STATUS__k_EDisplayStatusLicenseExpired = 27,
  EDISPLAY_STATUS__k_EDisplayStatusAvailForFree = 28,
  EDISPLAY_STATUS__k_EDisplayStatusAvailToBorrow = 29,
  EDISPLAY_STATUS__k_EDisplayStatusAvailGuestPass = 30,
  EDISPLAY_STATUS__k_EDisplayStatusPurchase = 31,
  EDISPLAY_STATUS__k_EDisplayStatusUnavailable = 32,
  EDISPLAY_STATUS__k_EDisplayStatusNotLaunchable = 33,
  EDISPLAY_STATUS__k_EDisplayStatusCloudError = 34,
  EDISPLAY_STATUS__k_EDisplayStatusCloudOutOfDate = 35,
  EDISPLAY_STATUS__k_EDisplayStatusTerminating = 36,
  EDISPLAY_STATUS__k_EDisplayStatusOwnerLocked = 37,
  EDISPLAY_STATUS__k_EDisplayStatusDownloadFailed = 38,
  EDISPLAY_STATUS__k_EDisplayStatusUpdateFailed = 39
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EDISPLAY_STATUS)
} EDisplayStatus;
typedef enum _EAppCloudStatus {
  EAPP_CLOUD_STATUS__k_EAppCloudStatusInvalid = 0,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusDisabled = 1,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusUnknown = 2,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusSynchronized = 3,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusChecking = 4,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusOutOfSync = 5,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusUploading = 6,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusDownloading = 7,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusSyncFailed = 8,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusConflict = 9,
  EAPP_CLOUD_STATUS__k_EAppCloudStatusPendingElsewhere = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EAPP_CLOUD_STATUS)
} EAppCloudStatus;
typedef enum _EAppControllerSupportLevel {
  EAPP_CONTROLLER_SUPPORT_LEVEL__k_EAppControllerSupportLevelNone = 0,
  EAPP_CONTROLLER_SUPPORT_LEVEL__k_EAppControllerSupportLevelPartial = 1,
  EAPP_CONTROLLER_SUPPORT_LEVEL__k_EAppControllerSupportLevelFull = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EAPP_CONTROLLER_SUPPORT_LEVEL)
} EAppControllerSupportLevel;
typedef enum _EAppGamepadGyroTrackpadSupportLevel {
  EAPP_GAMEPAD_GYRO_TRACKPAD_SUPPORT_LEVEL__k_EAppGamepadGyroTrackpadSupportLevelUnknown = -1,
  EAPP_GAMEPAD_GYRO_TRACKPAD_SUPPORT_LEVEL__k_EAppGamepadGyroTrackpadSupportLevelNoGamepad = 0,
  EAPP_GAMEPAD_GYRO_TRACKPAD_SUPPORT_LEVEL__k_EAppGamepadGyroTrackpadSupportLevelGamepad = 1,
  EAPP_GAMEPAD_GYRO_TRACKPAD_SUPPORT_LEVEL__k_EAppGamepadGyroTrackpadSupportLevelSimultaneous = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EAPP_GAMEPAD_GYRO_TRACKPAD_SUPPORT_LEVEL)
} EAppGamepadGyroTrackpadSupportLevel;
typedef enum _EAppHDRSupport {
  EAPP_HDRSUPPORT__k_EHDRSupport_Unknown = 0,
  EAPP_HDRSUPPORT__k_EHDRSupport_SDR = 1,
  EAPP_HDRSUPPORT__k_EHDRSupport_HDR = 2,
  EAPP_HDRSUPPORT__k_EHDRSupport_HDR_Broken = 3,
  EAPP_HDRSUPPORT__k_EHDRSupport_HDR_RequiresUserAction = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EAPP_HDRSUPPORT)
} EAppHDRSupport;

/* --- messages --- */

struct  CAppOverviewPerClientData
{
  ProtobufCMessage base;
  protobuf_c_boolean has_clientid;
  uint64_t clientid;
  char *client_name;
  protobuf_c_boolean has_display_status;
  EDisplayStatus display_status;
  protobuf_c_boolean has_status_percentage;
  uint32_t status_percentage;
  char *active_beta;
  protobuf_c_boolean has_installed;
  protobuf_c_boolean installed;
  protobuf_c_boolean has_streaming_to_local_client;
  protobuf_c_boolean streaming_to_local_client;
  protobuf_c_boolean has_is_available_on_current_platform;
  protobuf_c_boolean is_available_on_current_platform;
  protobuf_c_boolean has_is_invalid_os_type;
  protobuf_c_boolean is_invalid_os_type;
  protobuf_c_boolean has_playtime_left;
  uint32_t playtime_left;
  protobuf_c_boolean has_update_available_but_disabled_by_app;
  protobuf_c_boolean update_available_but_disabled_by_app;
};
#define CAPP_OVERVIEW__PER_CLIENT_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&capp_overview__per_client_data__descriptor) \
, 0, 0ull, NULL, 0, EDISPLAY_STATUS__k_EDisplayStatusInvalid, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CAppOverview
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  char *display_name;
  protobuf_c_boolean has_visible_in_game_list;
  protobuf_c_boolean visible_in_game_list;
  protobuf_c_boolean has_subscribed_to;
  protobuf_c_boolean subscribed_to;
  char *sort_as;
  protobuf_c_boolean has_app_type;
  EProtoAppType app_type;
  protobuf_c_boolean has_mru_index;
  uint32_t mru_index;
  protobuf_c_boolean has_rt_recent_activity_time;
  uint32_t rt_recent_activity_time;
  protobuf_c_boolean has_minutes_playtime_forever;
  uint32_t minutes_playtime_forever;
  protobuf_c_boolean has_minutes_playtime_last_two_weeks;
  uint32_t minutes_playtime_last_two_weeks;
  protobuf_c_boolean has_rt_last_time_played;
  uint32_t rt_last_time_played;
  size_t n_store_tag;
  uint32_t *store_tag;
  size_t n_store_category;
  uint32_t *store_category;
  protobuf_c_boolean has_rt_original_release_date;
  uint32_t rt_original_release_date;
  protobuf_c_boolean has_rt_steam_release_date;
  uint32_t rt_steam_release_date;
  char *icon_hash;
  protobuf_c_boolean has_xbox_controller_support;
  EAppControllerSupportLevel xbox_controller_support;
  protobuf_c_boolean has_vr_supported;
  protobuf_c_boolean vr_supported;
  protobuf_c_boolean has_metacritic_score;
  uint32_t metacritic_score;
  protobuf_c_boolean has_size_on_disk;
  uint64_t size_on_disk;
  protobuf_c_boolean has_third_party_mod;
  protobuf_c_boolean third_party_mod;
  char *icon_data;
  char *icon_data_format;
  char *gameid;
  char *library_capsule_filename;
  size_t n_per_client_data;
  CAppOverviewPerClientData **per_client_data;
  protobuf_c_boolean has_most_available_clientid;
  uint64_t most_available_clientid;
  protobuf_c_boolean has_selected_clientid;
  uint64_t selected_clientid;
  protobuf_c_boolean has_rt_store_asset_mtime;
  uint32_t rt_store_asset_mtime;
  protobuf_c_boolean has_rt_custom_image_mtime;
  uint32_t rt_custom_image_mtime;
  protobuf_c_boolean has_optional_parent_app_id;
  uint32_t optional_parent_app_id;
  protobuf_c_boolean has_owner_account_id;
  uint32_t owner_account_id;
  protobuf_c_boolean has_review_score_with_bombs;
  uint32_t review_score_with_bombs;
  protobuf_c_boolean has_review_percentage_with_bombs;
  uint32_t review_percentage_with_bombs;
  protobuf_c_boolean has_review_score_without_bombs;
  uint32_t review_score_without_bombs;
  protobuf_c_boolean has_review_percentage_without_bombs;
  uint32_t review_percentage_without_bombs;
  char *library_id;
  protobuf_c_boolean has_vr_only;
  protobuf_c_boolean vr_only;
  protobuf_c_boolean has_mastersub_appid;
  uint32_t mastersub_appid;
  char *mastersub_includedwith_logo;
  char *site_license_site_name;
  protobuf_c_boolean has_shortcut_override_appid;
  uint32_t shortcut_override_appid;
  protobuf_c_boolean has_rt_last_time_locally_played;
  uint32_t rt_last_time_locally_played;
  protobuf_c_boolean has_rt_purchased_time;
  uint32_t rt_purchased_time;
  char *header_filename;
  protobuf_c_boolean has_local_cache_version;
  uint32_t local_cache_version;
  protobuf_c_boolean has_number_of_copies;
  uint32_t number_of_copies;
  protobuf_c_boolean has_steam_hw_compat_category_packed;
  uint32_t steam_hw_compat_category_packed;
  char *album_cover_hash;
  protobuf_c_boolean has_display_name_elanguage;
  int32_t display_name_elanguage;
  protobuf_c_boolean has_has_custom_sort_as;
  protobuf_c_boolean has_custom_sort_as;
  protobuf_c_boolean has_bitfield_supported_languages;
  uint64_t bitfield_supported_languages;
  size_t n_remote_per_client_data;
  CAppOverviewPerClientData **remote_per_client_data;
};
#define CAPP_OVERVIEW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&capp_overview__descriptor) \
, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, EPROTO_APP_TYPE__k_EAppTypeInvalid, 0, 0, 0, 0u, 0, 0u, 0, 0u, 0, 0u, 0,NULL, 0,NULL, 0, 0u, 0, 0u, NULL, 0, EAPP_CONTROLLER_SUPPORT_LEVEL__k_EAppControllerSupportLevelNone, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, 0,NULL, 0, 0ull, 0, 0ull, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0u, 0, 0u, 0, 0u, 0, 0u, NULL, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 1u, 0, 0u, NULL, 0, -1, 0, 0, 0, 0ull, 0,NULL }


struct  CAppOverviewChange
{
  ProtobufCMessage base;
  size_t n_app_overview;
  CAppOverview **app_overview;
  size_t n_removed_appid;
  uint32_t *removed_appid;
  protobuf_c_boolean has_full_update;
  protobuf_c_boolean full_update;
  protobuf_c_boolean has_update_complete;
  protobuf_c_boolean update_complete;
};
#define CAPP_OVERVIEW__CHANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&capp_overview__change__descriptor) \
, 0,NULL, 0,NULL, 0, 0, 0, 0 }


/* CAppOverviewPerClientData methods */
void   capp_overview__per_client_data__init
                     (CAppOverviewPerClientData         *message);
size_t capp_overview__per_client_data__get_packed_size
                     (const CAppOverviewPerClientData   *message);
size_t capp_overview__per_client_data__pack
                     (const CAppOverviewPerClientData   *message,
                      uint8_t             *out);
size_t capp_overview__per_client_data__pack_to_buffer
                     (const CAppOverviewPerClientData   *message,
                      ProtobufCBuffer     *buffer);
CAppOverviewPerClientData *
       capp_overview__per_client_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   capp_overview__per_client_data__free_unpacked
                     (CAppOverviewPerClientData *message,
                      ProtobufCAllocator *allocator);
/* CAppOverview methods */
void   capp_overview__init
                     (CAppOverview         *message);
size_t capp_overview__get_packed_size
                     (const CAppOverview   *message);
size_t capp_overview__pack
                     (const CAppOverview   *message,
                      uint8_t             *out);
size_t capp_overview__pack_to_buffer
                     (const CAppOverview   *message,
                      ProtobufCBuffer     *buffer);
CAppOverview *
       capp_overview__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   capp_overview__free_unpacked
                     (CAppOverview *message,
                      ProtobufCAllocator *allocator);
/* CAppOverviewChange methods */
void   capp_overview__change__init
                     (CAppOverviewChange         *message);
size_t capp_overview__change__get_packed_size
                     (const CAppOverviewChange   *message);
size_t capp_overview__change__pack
                     (const CAppOverviewChange   *message,
                      uint8_t             *out);
size_t capp_overview__change__pack_to_buffer
                     (const CAppOverviewChange   *message,
                      ProtobufCBuffer     *buffer);
CAppOverviewChange *
       capp_overview__change__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   capp_overview__change__free_unpacked
                     (CAppOverviewChange *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CAppOverviewPerClientData_Closure)
                 (const CAppOverviewPerClientData *message,
                  void *closure_data);
typedef void (*CAppOverview_Closure)
                 (const CAppOverview *message,
                  void *closure_data);
typedef void (*CAppOverviewChange_Closure)
                 (const CAppOverviewChange *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    edisplay_status__descriptor;
extern const ProtobufCEnumDescriptor    eapp_cloud_status__descriptor;
extern const ProtobufCEnumDescriptor    eapp_controller_support_level__descriptor;
extern const ProtobufCEnumDescriptor    eapp_gamepad_gyro_trackpad_support_level__descriptor;
extern const ProtobufCEnumDescriptor    eapp_hdrsupport__descriptor;
extern const ProtobufCMessageDescriptor capp_overview__per_client_data__descriptor;
extern const ProtobufCMessageDescriptor capp_overview__descriptor;
extern const ProtobufCMessageDescriptor capp_overview__change__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5fappoverview_2eproto__INCLUDED */
