/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_clientsettings.proto */

#ifndef PROTOBUF_C_steammessages_5fclientsettings_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5fclientsettings_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "google/protobuf/descriptor.pb-c.h"
#include "enums.pb-c.h"

typedef struct CMsgHotkey CMsgHotkey;
typedef struct CMsgSettingVariant CMsgSettingVariant;
typedef struct CMsgClientSettings CMsgClientSettings;


/* --- enums --- */

typedef enum _EClientSettingStore {
  ECLIENT_SETTING_STORE__k_EClientSettingStore_Invalid = 0,
  ECLIENT_SETTING_STORE__k_EClientSettingStore_ConfigStore_Install = 1,
  ECLIENT_SETTING_STORE__k_EClientSettingStore_ConfigStore_UserRoaming = 2,
  ECLIENT_SETTING_STORE__k_EClientSettingStore_ConfigStore_UserLocal = 3,
  ECLIENT_SETTING_STORE__k_EClientSettingStore_Registry = 4,
  ECLIENT_SETTING_STORE__k_EClientSettingStore_CustomFunc = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ECLIENT_SETTING_STORE)
} EClientSettingStore;
typedef enum _EOverlayToggleBarLocation {
  EOVERLAY_TOGGLE_BAR_LOCATION__k_EOverlayToggleBarLocation_Bottom = 0,
  EOVERLAY_TOGGLE_BAR_LOCATION__k_EOverlayToggleBarLocation_Left = 1,
  EOVERLAY_TOGGLE_BAR_LOCATION__k_EOverlayToggleBarLocation_Right = 2,
  EOVERLAY_TOGGLE_BAR_LOCATION__k_EOverlayToggleBarLocation_Top = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EOVERLAY_TOGGLE_BAR_LOCATION)
} EOverlayToggleBarLocation;
typedef enum _ESettingProfileMode {
  ESETTING_PROFILE_MODE__k_ESettingProfileMode_None = 0,
  ESETTING_PROFILE_MODE__k_ESettingProfileMode_PerGame = 1,
  ESETTING_PROFILE_MODE__k_ESettingProfileMode_PerGamePerDisplay = 2,
  ESETTING_PROFILE_MODE__k_ESettingProfileMode_PerDisplay = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ESETTING_PROFILE_MODE)
} ESettingProfileMode;
typedef enum _EGRAudio {
  EGRAUDIO__k_EGRAudio_Game = 0,
  EGRAUDIO__k_EGRAudio_System = 1,
  EGRAUDIO__k_EGRAudio_Select = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EGRAUDIO)
} EGRAudio;
typedef enum _EGRExportLimitType {
  EGREXPORT_LIMIT_TYPE__k_EGRExportLimitType_Native = 0,
  EGREXPORT_LIMIT_TYPE__k_EGRExportLimitType_FileSize = 1,
  EGREXPORT_LIMIT_TYPE__k_EGRExportLimitType_Advanced = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EGREXPORT_LIMIT_TYPE)
} EGRExportLimitType;
typedef enum _EFrameRateReportEnabled {
  EFRAME_RATE_REPORT_ENABLED__k_EFrameRateReportEnabled_Unset = 0,
  EFRAME_RATE_REPORT_ENABLED__k_EFrameRateReportEnabled_Enabled = 1,
  EFRAME_RATE_REPORT_ENABLED__k_EFrameRateReportEnabled_Disabled = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EFRAME_RATE_REPORT_ENABLED)
} EFrameRateReportEnabled;

/* --- messages --- */

struct  CMsgHotkey
{
  ProtobufCMessage base;
  protobuf_c_boolean has_key_code;
  uint32_t key_code;
  protobuf_c_boolean has_alt_key;
  protobuf_c_boolean alt_key;
  protobuf_c_boolean has_shift_key;
  protobuf_c_boolean shift_key;
  protobuf_c_boolean has_ctrl_key;
  protobuf_c_boolean ctrl_key;
  protobuf_c_boolean has_meta_key;
  protobuf_c_boolean meta_key;
  char *display_name;
};
#define CMSG_HOTKEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_hotkey__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL }


typedef enum {
  CMSG_SETTING_VARIANT__VALUE__NOT_SET = 0,
  CMSG_SETTING_VARIANT__VALUE_VALUE_BOOL = 1,
  CMSG_SETTING_VARIANT__VALUE_VALUE_INT32 = 2,
  CMSG_SETTING_VARIANT__VALUE_VALUE_UINT32 = 3,
  CMSG_SETTING_VARIANT__VALUE_VALUE_UINT64 = 5,
  CMSG_SETTING_VARIANT__VALUE_VALUE_FLOAT = 6,
  CMSG_SETTING_VARIANT__VALUE_VALUE_STRING = 7,
  CMSG_SETTING_VARIANT__VALUE_VALUE_HOTKEY = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CMSG_SETTING_VARIANT__VALUE__CASE)
} CMsgSettingVariant__ValueCase;

struct  CMsgSettingVariant
{
  ProtobufCMessage base;
  CMsgSettingVariant__ValueCase value_case;
  union {
    int64_t value_uint64;
    char *value_string;
    CMsgHotkey *value_hotkey;
    float value_float;
    int32_t value_int32;
    uint32_t value_uint32;
    protobuf_c_boolean value_bool;
  };
};
#define CMSG_SETTING_VARIANT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_setting_variant__descriptor) \
, CMSG_SETTING_VARIANT__VALUE__NOT_SET, {0} }


struct  CMsgClientSettings
{
  ProtobufCMessage base;
  protobuf_c_boolean has_no_save_personal_info;
  protobuf_c_boolean no_save_personal_info;
  char *preferred_monitor;
  protobuf_c_boolean has_steam_cef_gpu_blocklist_disabled;
  protobuf_c_boolean steam_cef_gpu_blocklist_disabled;
  protobuf_c_boolean has_bigpicture_windowed;
  protobuf_c_boolean bigpicture_windowed;
  char *display_name;
  protobuf_c_boolean has_is_external_display;
  protobuf_c_boolean is_external_display;
  protobuf_c_boolean has_steam_os_underscan_level;
  float steam_os_underscan_level;
  protobuf_c_boolean has_steam_os_underscan_enabled;
  protobuf_c_boolean steam_os_underscan_enabled;
  protobuf_c_boolean has_min_scale_factor;
  float min_scale_factor;
  protobuf_c_boolean has_max_scale_factor;
  float max_scale_factor;
  protobuf_c_boolean has_auto_scale_factor;
  float auto_scale_factor;
  protobuf_c_boolean has_small_mode;
  protobuf_c_boolean small_mode;
  protobuf_c_boolean has_skip_steamvr_install_dialog;
  protobuf_c_boolean skip_steamvr_install_dialog;
  protobuf_c_boolean has_always_show_user_chooser;
  protobuf_c_boolean always_show_user_chooser;
  protobuf_c_boolean has_os_version_unsupported;
  protobuf_c_boolean os_version_unsupported;
  protobuf_c_boolean has_show_family_sharing_notifications;
  protobuf_c_boolean show_family_sharing_notifications;
  protobuf_c_boolean has_show_copy_count_in_library;
  protobuf_c_boolean show_copy_count_in_library;
  protobuf_c_boolean has_overlay_fps_counter_corner;
  int32_t overlay_fps_counter_corner;
  protobuf_c_boolean has_overlay_fps_counter_high_contrast;
  protobuf_c_boolean overlay_fps_counter_high_contrast;
  CMsgHotkey *overlay_key;
  CMsgHotkey *screenshot_key;
  protobuf_c_boolean has_enable_overlay;
  protobuf_c_boolean enable_overlay;
  protobuf_c_boolean has_enable_screenshot_notification;
  protobuf_c_boolean enable_screenshot_notification;
  protobuf_c_boolean has_enable_screenshot_sound;
  protobuf_c_boolean enable_screenshot_sound;
  protobuf_c_boolean has_save_uncompressed_screenshots;
  protobuf_c_boolean save_uncompressed_screenshots;
  char *screenshots_path;
  protobuf_c_boolean has_default_ping_rate;
  int32_t default_ping_rate;
  protobuf_c_boolean has_server_ping_rate;
  int32_t server_ping_rate;
  protobuf_c_boolean has_steam_networking_share_ip;
  int32_t steam_networking_share_ip;
  char *web_browser_home;
  char *voice_mic_device_name;
  protobuf_c_boolean has_voice_mic_input_gain;
  float voice_mic_input_gain;
  protobuf_c_boolean has_voice_speaker_output_gain;
  float voice_speaker_output_gain;
  protobuf_c_boolean has_voice_push_to_talk_setting;
  int32_t voice_push_to_talk_setting;
  CMsgHotkey *voice_push_to_talk_key;
  protobuf_c_boolean has_overlay_toolbar_list_view;
  protobuf_c_boolean overlay_toolbar_list_view;
  protobuf_c_boolean has_always_use_gamepadui_overlay;
  protobuf_c_boolean always_use_gamepadui_overlay;
  char *overlay_tabs;
  protobuf_c_boolean has_overlay_scale_interface;
  protobuf_c_boolean overlay_scale_interface;
  protobuf_c_boolean has_overlay_restore_browser_tabs;
  protobuf_c_boolean overlay_restore_browser_tabs;
  protobuf_c_boolean has_enable_avif_screenshots;
  protobuf_c_boolean enable_avif_screenshots;
  protobuf_c_boolean has_overlay_fps_counter_detail_level;
  int32_t overlay_fps_counter_detail_level;
  protobuf_c_boolean has_overlay_fps_counter_saturation_factor;
  float overlay_fps_counter_saturation_factor;
  protobuf_c_boolean has_overlay_fps_counter_bgopacity;
  float overlay_fps_counter_bgopacity;
  protobuf_c_boolean has_overlay_fps_counter_scale_factor;
  float overlay_fps_counter_scale_factor;
  CMsgHotkey *overlay_fps_counter_key;
  protobuf_c_boolean has_overlay_fps_counter_fps_graph;
  protobuf_c_boolean overlay_fps_counter_fps_graph;
  protobuf_c_boolean has_overlay_fps_counter_cpu_graph;
  protobuf_c_boolean overlay_fps_counter_cpu_graph;
  protobuf_c_boolean has_overlay_fps_counter_allow_km_driver;
  protobuf_c_boolean overlay_fps_counter_allow_km_driver;
  protobuf_c_boolean has_achievement_notification_toast;
  protobuf_c_boolean achievement_notification_toast;
  protobuf_c_boolean has_achievement_notification_sound;
  protobuf_c_boolean achievement_notification_sound;
  protobuf_c_boolean has_controllerconnect_notification_toast;
  protobuf_c_boolean controllerconnect_notification_toast;
  protobuf_c_boolean has_controllerconnect_notification_sound;
  protobuf_c_boolean controllerconnect_notification_sound;
  protobuf_c_boolean has_controller_low_battery_notification_toast;
  protobuf_c_boolean controller_low_battery_notification_toast;
  protobuf_c_boolean has_controller_low_battery_notification_sound;
  protobuf_c_boolean controller_low_battery_notification_sound;
  protobuf_c_boolean has_smooth_scroll_webviews;
  protobuf_c_boolean smooth_scroll_webviews;
  protobuf_c_boolean has_enable_gpu_accelerated_webviews;
  protobuf_c_boolean enable_gpu_accelerated_webviews;
  protobuf_c_boolean has_enable_hardware_video_decoding;
  protobuf_c_boolean enable_hardware_video_decoding;
  protobuf_c_boolean has_run_at_startup;
  protobuf_c_boolean run_at_startup;
  protobuf_c_boolean has_enable_dpi_scaling;
  protobuf_c_boolean enable_dpi_scaling;
  protobuf_c_boolean has_enable_marketing_messages;
  protobuf_c_boolean enable_marketing_messages;
  protobuf_c_boolean has_start_in_big_picture_mode;
  protobuf_c_boolean start_in_big_picture_mode;
  protobuf_c_boolean has_jumplist_flags;
  uint32_t jumplist_flags;
  protobuf_c_boolean has_enable_ui_sounds;
  protobuf_c_boolean enable_ui_sounds;
  protobuf_c_boolean has_enable_gamescope_composer;
  protobuf_c_boolean enable_gamescope_composer;
  protobuf_c_boolean has_enable_gamescope_composer_vr;
  protobuf_c_boolean enable_gamescope_composer_vr;
  protobuf_c_boolean has_show_switch_to_desktop_at_login;
  protobuf_c_boolean show_switch_to_desktop_at_login;
  protobuf_c_boolean has_enable_steamrt64_client;
  protobuf_c_boolean enable_steamrt64_client;
  protobuf_c_boolean has_disable_all_toasts;
  protobuf_c_boolean disable_all_toasts;
  protobuf_c_boolean has_disable_toasts_in_game;
  protobuf_c_boolean disable_toasts_in_game;
  protobuf_c_boolean has_play_sound_on_toast;
  protobuf_c_boolean play_sound_on_toast;
  protobuf_c_boolean has_library_display_size;
  int32_t library_display_size;
  protobuf_c_boolean has_library_whats_new_show_only_product_updates;
  protobuf_c_boolean library_whats_new_show_only_product_updates;
  protobuf_c_boolean has_show_store_content_on_home;
  protobuf_c_boolean show_store_content_on_home;
  char *start_page;
  protobuf_c_boolean has_library_low_bandwidth_mode;
  protobuf_c_boolean library_low_bandwidth_mode;
  protobuf_c_boolean has_library_low_perf_mode;
  protobuf_c_boolean library_low_perf_mode;
  protobuf_c_boolean has_library_disable_community_content;
  protobuf_c_boolean library_disable_community_content;
  protobuf_c_boolean has_library_display_icon_in_game_list;
  protobuf_c_boolean library_display_icon_in_game_list;
  protobuf_c_boolean has_ready_to_play_includes_streaming;
  protobuf_c_boolean ready_to_play_includes_streaming;
  protobuf_c_boolean has_show_steam_deck_info;
  protobuf_c_boolean show_steam_deck_info;
  protobuf_c_boolean has_enable_shader_precache;
  protobuf_c_boolean enable_shader_precache;
  protobuf_c_boolean has_enable_shader_background_processing;
  protobuf_c_boolean enable_shader_background_processing;
  protobuf_c_boolean has_shader_precached_size;
  uint64_t shader_precached_size;
  protobuf_c_boolean has_needs_steam_service_repair;
  protobuf_c_boolean needs_steam_service_repair;
  protobuf_c_boolean has_download_peer_content;
  int32_t download_peer_content;
  protobuf_c_boolean has_download_rate_bits_per_s;
  protobuf_c_boolean download_rate_bits_per_s;
  protobuf_c_boolean has_restrict_auto_updates;
  protobuf_c_boolean restrict_auto_updates;
  protobuf_c_boolean has_restrict_auto_updates_start;
  int32_t restrict_auto_updates_start;
  protobuf_c_boolean has_restrict_auto_updates_end;
  int32_t restrict_auto_updates_end;
  protobuf_c_boolean has_download_region;
  int32_t download_region;
  protobuf_c_boolean has_download_while_app_running;
  protobuf_c_boolean download_while_app_running;
  protobuf_c_boolean has_download_throttle_while_streaming;
  protobuf_c_boolean download_throttle_while_streaming;
  protobuf_c_boolean has_download_throttle_rate;
  int32_t download_throttle_rate;
  protobuf_c_boolean has_default_app_update_behavior;
  int32_t default_app_update_behavior;
  protobuf_c_boolean has_cloud_enabled;
  protobuf_c_boolean cloud_enabled;
  protobuf_c_boolean has_show_screenshot_manager;
  protobuf_c_boolean show_screenshot_manager;
  protobuf_c_boolean has_music_volume;
  int32_t music_volume;
  protobuf_c_boolean has_music_pause_on_app_start;
  protobuf_c_boolean music_pause_on_app_start;
  protobuf_c_boolean has_music_pause_on_voice_chat;
  protobuf_c_boolean music_pause_on_voice_chat;
  protobuf_c_boolean has_music_download_high_quality;
  protobuf_c_boolean music_download_high_quality;
  protobuf_c_boolean has_broadcast_permissions;
  EBroadcastPermission broadcast_permissions;
  protobuf_c_boolean has_broadcast_output_width;
  int32_t broadcast_output_width;
  protobuf_c_boolean has_broadcast_output_height;
  int32_t broadcast_output_height;
  protobuf_c_boolean has_broadcast_bitrate;
  int32_t broadcast_bitrate;
  protobuf_c_boolean has_broadcast_encoding_option;
  EBroadcastEncoderSetting broadcast_encoding_option;
  protobuf_c_boolean has_broadcast_record_all_video;
  protobuf_c_boolean broadcast_record_all_video;
  protobuf_c_boolean has_broadcast_record_all_audio;
  protobuf_c_boolean broadcast_record_all_audio;
  protobuf_c_boolean has_broadcast_record_microphone;
  protobuf_c_boolean broadcast_record_microphone;
  protobuf_c_boolean has_broadcast_show_upload_stats;
  protobuf_c_boolean broadcast_show_upload_stats;
  protobuf_c_boolean has_broadcast_show_live_reminder;
  protobuf_c_boolean broadcast_show_live_reminder;
  protobuf_c_boolean has_broadcast_chat_corner;
  int32_t broadcast_chat_corner;
  protobuf_c_boolean has_gamestream_hardware_video_encode;
  protobuf_c_boolean gamestream_hardware_video_encode;
  protobuf_c_boolean has_gamestream_enable_video_h265;
  protobuf_c_boolean gamestream_enable_video_h265;
  protobuf_c_boolean has_steam_input_configurator_error_msg_enable;
  protobuf_c_boolean steam_input_configurator_error_msg_enable;
  protobuf_c_boolean has_controller_guide_button_focus_steam;
  protobuf_c_boolean controller_guide_button_focus_steam;
  protobuf_c_boolean has_controller_ps_support;
  int32_t controller_ps_support;
  protobuf_c_boolean has_controller_xbox_support;
  protobuf_c_boolean controller_xbox_support;
  protobuf_c_boolean has_controller_xbox_driver;
  protobuf_c_boolean controller_xbox_driver;
  protobuf_c_boolean has_controller_switch_support;
  protobuf_c_boolean controller_switch_support;
  protobuf_c_boolean has_controller_generic_support;
  protobuf_c_boolean controller_generic_support;
  protobuf_c_boolean has_controller_power_off_timeout;
  int32_t controller_power_off_timeout;
  protobuf_c_boolean has_turn_off_controller_on_exit;
  protobuf_c_boolean turn_off_controller_on_exit;
  protobuf_c_boolean has_controller_combine_nintendo_joycons;
  protobuf_c_boolean controller_combine_nintendo_joycons;
  protobuf_c_boolean has_controller_enable_chord;
  protobuf_c_boolean controller_enable_chord;
  protobuf_c_boolean has_controller_poll_rate;
  protobuf_c_boolean controller_poll_rate;
  protobuf_c_boolean has_controller_siapi_config_author_mode;
  protobuf_c_boolean controller_siapi_config_author_mode;
  protobuf_c_boolean has_controller_show_ibex_tour;
  protobuf_c_boolean controller_show_ibex_tour;
  char *controller_chat_radial_menu_option_0;
  char *controller_chat_radial_menu_option_1;
  char *controller_chat_radial_menu_option_2;
  char *controller_chat_radial_menu_option_3;
  char *controller_chat_radial_menu_option_4;
  char *controller_chat_radial_menu_option_5;
  char *controller_chat_radial_menu_option_6;
  char *controller_chat_radial_menu_option_7;
  protobuf_c_boolean has_startup_movie_id;
  uint64_t startup_movie_id;
  char *startup_movie_local_path;
  protobuf_c_boolean has_startup_movie_shuffle;
  protobuf_c_boolean startup_movie_shuffle;
  protobuf_c_boolean has_startup_movie_used_for_resume;
  protobuf_c_boolean startup_movie_used_for_resume;
  protobuf_c_boolean has_game_notes_enable_spellcheck;
  protobuf_c_boolean game_notes_enable_spellcheck;
  protobuf_c_boolean has_screenshot_items_per_row;
  int32_t screenshot_items_per_row;
  char *gamerecording_background_path;
  char *gamerecording_background_max_keep;
  protobuf_c_boolean has_gamerecording_background_time_resolution;
  int32_t gamerecording_background_time_resolution;
  CMsgHotkey *gamerecording_background_mk;
  CMsgHotkey *gamerecording_background_tg;
  protobuf_c_boolean has_gamerecording_background_a_m;
  protobuf_c_boolean gamerecording_background_a_m;
  char *gamerecording_video_bitrate;
  protobuf_c_boolean has_gamerecording_background_mode;
  EGRMode gamerecording_background_mode;
  protobuf_c_boolean has_gamerecording_background_audio;
  EGRAudio gamerecording_background_audio;
  protobuf_c_boolean has_gamerecording_max_fps;
  int32_t gamerecording_max_fps;
  CMsgHotkey *gamerecording_hotkey_ic;
  protobuf_c_boolean has_gamerecording_ic_seconds;
  float gamerecording_ic_seconds;
  protobuf_c_boolean has_gamerecording_export_limit_type;
  EGRExportLimitType gamerecording_export_limit_type;
  protobuf_c_boolean has_gamerecording_export_limit_size_mb;
  int32_t gamerecording_export_limit_size_mb;
  protobuf_c_boolean has_gamerecording_export_limit_bitrate;
  int32_t gamerecording_export_limit_bitrate;
  protobuf_c_boolean has_gamerecording_export_limit_width;
  int32_t gamerecording_export_limit_width;
  protobuf_c_boolean has_gamerecording_export_limit_height;
  int32_t gamerecording_export_limit_height;
  protobuf_c_boolean has_gamerecording_export_limit_frame_rate;
  int32_t gamerecording_export_limit_frame_rate;
  char *gamerecording_export_directory;
  protobuf_c_boolean has_gamerecording_export_codec;
  EExportCodec gamerecording_export_codec;
  protobuf_c_boolean has_gamerecording_video_maxheight;
  int32_t gamerecording_video_maxheight;
  protobuf_c_boolean has_gamerecording_force_mic_mono;
  protobuf_c_boolean gamerecording_force_mic_mono;
  protobuf_c_boolean has_gamerecording_automatic_gain_control;
  protobuf_c_boolean gamerecording_automatic_gain_control;
  protobuf_c_boolean has_show_timestamps_in_console;
  protobuf_c_boolean show_timestamps_in_console;
  protobuf_c_boolean has_override_browser_composer_mode;
  int32_t override_browser_composer_mode;
  protobuf_c_boolean has_cef_remote_debugging_enabled;
  protobuf_c_boolean cef_remote_debugging_enabled;
  protobuf_c_boolean has_force_deck_perf_tab;
  protobuf_c_boolean force_deck_perf_tab;
  protobuf_c_boolean has_force_fake_mandatory_update;
  protobuf_c_boolean force_fake_mandatory_update;
  protobuf_c_boolean has_hdr_compat_testing;
  protobuf_c_boolean hdr_compat_testing;
  protobuf_c_boolean has_developer_mode_enabled;
  protobuf_c_boolean developer_mode_enabled;
  protobuf_c_boolean has_show_advanced_update_channels;
  protobuf_c_boolean show_advanced_update_channels;
  protobuf_c_boolean has_browserview_underlays_allowed;
  protobuf_c_boolean browserview_underlays_allowed;
  protobuf_c_boolean has_gamescope_hdr_visualization;
  EHDRVisualization gamescope_hdr_visualization;
  protobuf_c_boolean has_gamescope_app_target_framerate;
  int32_t gamescope_app_target_framerate;
  protobuf_c_boolean has_gamescope_enable_app_target_framerate;
  protobuf_c_boolean gamescope_enable_app_target_framerate;
  protobuf_c_boolean has_gamescope_disable_framelimit;
  protobuf_c_boolean gamescope_disable_framelimit;
  protobuf_c_boolean has_gamescope_display_refresh_rate;
  int32_t gamescope_display_refresh_rate;
  protobuf_c_boolean has_gamescope_use_game_refresh_rate_in_steam;
  protobuf_c_boolean gamescope_use_game_refresh_rate_in_steam;
  protobuf_c_boolean has_gamescope_disable_mura_correction;
  protobuf_c_boolean gamescope_disable_mura_correction;
  protobuf_c_boolean has_gamescope_include_steamui_in_screenshots;
  protobuf_c_boolean gamescope_include_steamui_in_screenshots;
  protobuf_c_boolean has_gamescope_allow_tearing;
  protobuf_c_boolean gamescope_allow_tearing;
  protobuf_c_boolean has_gamescope_composite_debug;
  protobuf_c_boolean gamescope_composite_debug;
  protobuf_c_boolean has_gamescope_force_composite;
  protobuf_c_boolean gamescope_force_composite;
  char *gamescope_game_resolution_global;
  CMsgHotkey *gamescope_guide_hotkey;
  CMsgHotkey *gamescope_qam_hotkey;
  protobuf_c_boolean has_gamescope_hdr_enabled;
  protobuf_c_boolean gamescope_hdr_enabled;
  protobuf_c_boolean has_gamescope_native_external_res_in_steam;
  protobuf_c_boolean gamescope_native_external_res_in_steam;
  protobuf_c_boolean has_steamos_status_led_brightness;
  int32_t steamos_status_led_brightness;
  protobuf_c_boolean has_steamos_tdp_limit_enabled;
  protobuf_c_boolean steamos_tdp_limit_enabled;
  protobuf_c_boolean has_steamos_tdp_limit;
  int32_t steamos_tdp_limit;
  protobuf_c_boolean has_steamos_cec_enabled;
  protobuf_c_boolean steamos_cec_enabled;
  protobuf_c_boolean has_steamos_cec_wake_on_resume;
  protobuf_c_boolean steamos_cec_wake_on_resume;
  protobuf_c_boolean has_steamos_wifi_debug;
  protobuf_c_boolean steamos_wifi_debug;
  protobuf_c_boolean has_steamos_wifi_force_wpa_supplicant;
  protobuf_c_boolean steamos_wifi_force_wpa_supplicant;
  protobuf_c_boolean has_steamos_magnifier_scale;
  int32_t steamos_magnifier_scale;
  protobuf_c_boolean has_steamos_manual_gpu_clock_enabled;
  protobuf_c_boolean steamos_manual_gpu_clock_enabled;
  protobuf_c_boolean has_steamos_manual_gpu_clock_hz;
  int32_t steamos_manual_gpu_clock_hz;
  char *steamos_platform_performance_profile;
  protobuf_c_boolean has_steamos_charge_limit_enabled;
  protobuf_c_boolean steamos_charge_limit_enabled;
  protobuf_c_boolean has_steamos_charge_limit;
  int32_t steamos_charge_limit;
  protobuf_c_boolean has_steamos_charge_limit_devmode;
  protobuf_c_boolean steamos_charge_limit_devmode;
  protobuf_c_boolean has_steamos_system_tracing_enabled;
  protobuf_c_boolean steamos_system_tracing_enabled;
  protobuf_c_boolean has_steamos_vrs_enabled;
  protobuf_c_boolean steamos_vrs_enabled;
  protobuf_c_boolean has_steamos_separate_led_colors;
  protobuf_c_boolean steamos_separate_led_colors;
  protobuf_c_boolean has_steamos_wifi_reload_wifi_driver_on_sleep;
  protobuf_c_boolean steamos_wifi_reload_wifi_driver_on_sleep;
  protobuf_c_boolean has_steamos_wifi_power_management_enabled;
  protobuf_c_boolean steamos_wifi_power_management_enabled;
  protobuf_c_boolean has_steamos_cec_control;
  protobuf_c_boolean steamos_cec_control;
  protobuf_c_boolean has_steamos_cec_suspend_tv;
  protobuf_c_boolean steamos_cec_suspend_tv;
  protobuf_c_boolean has_steamos_cec_suspend_device;
  protobuf_c_boolean steamos_cec_suspend_device;
  protobuf_c_boolean has_steamos_cec_wake_tv;
  protobuf_c_boolean steamos_cec_wake_tv;
  protobuf_c_boolean has_steamos_cec_wake_device;
  protobuf_c_boolean steamos_cec_wake_device;
  protobuf_c_boolean has_steamos_ec_logging_enabled;
  protobuf_c_boolean steamos_ec_logging_enabled;
  protobuf_c_boolean has_setting_validation_bool;
  protobuf_c_boolean setting_validation_bool;
  protobuf_c_boolean has_setting_validation_enum;
  EHDRVisualization setting_validation_enum;
  protobuf_c_boolean has_setting_validation_int32;
  int32_t setting_validation_int32;
  protobuf_c_boolean has_setting_validation_uint32;
  uint32_t setting_validation_uint32;
  protobuf_c_boolean has_setting_validation_uint64;
  uint64_t setting_validation_uint64;
  protobuf_c_boolean has_setting_validation_float;
  float setting_validation_float;
  char *setting_validation_string;
  CMsgHotkey *setting_validation_hotkey;
  protobuf_c_boolean has_system_bluetooth_enabled;
  protobuf_c_boolean system_bluetooth_enabled;
  protobuf_c_boolean has_hardware_updater_enabled;
  protobuf_c_boolean hardware_updater_enabled;
  protobuf_c_boolean has_system_idle_suspend_battery_sec;
  int32_t system_idle_suspend_battery_sec;
  protobuf_c_boolean has_system_idle_suspend_ac_sec;
  int32_t system_idle_suspend_ac_sec;
  protobuf_c_boolean has_system_enable_low_power_downloads;
  protobuf_c_boolean system_enable_low_power_downloads;
  protobuf_c_boolean has_system_allow_battery_low_power_downloads;
  protobuf_c_boolean system_allow_battery_low_power_downloads;
  protobuf_c_boolean has_system_idle_screensaver_battery_sec;
  int32_t system_idle_screensaver_battery_sec;
  protobuf_c_boolean has_system_idle_screensaver_ac_sec;
  int32_t system_idle_screensaver_ac_sec;
  protobuf_c_boolean has_vr_show_perf_graph_in_hmd;
  protobuf_c_boolean vr_show_perf_graph_in_hmd;
  protobuf_c_boolean has_vr_audio_spatialize;
  protobuf_c_boolean vr_audio_spatialize;
  protobuf_c_boolean has_vr_audio_spatialize_surround;
  protobuf_c_boolean vr_audio_spatialize_surround;
  protobuf_c_boolean has_accessibility_debug_visualizer;
  protobuf_c_boolean accessibility_debug_visualizer;
  protobuf_c_boolean has_accessibility_screen_reader_enabled;
  protobuf_c_boolean accessibility_screen_reader_enabled;
  protobuf_c_boolean has_accessibility_screen_reader_rate;
  float accessibility_screen_reader_rate;
  protobuf_c_boolean has_accessibility_screen_reader_pitch;
  float accessibility_screen_reader_pitch;
  protobuf_c_boolean has_accessibility_screen_reader_volume;
  float accessibility_screen_reader_volume;
  protobuf_c_boolean has_accessibility_high_contrast_mode;
  protobuf_c_boolean accessibility_high_contrast_mode;
  protobuf_c_boolean has_accessibility_reduce_motion;
  protobuf_c_boolean accessibility_reduce_motion;
  protobuf_c_boolean has_accessibility_minimum_font_size;
  uint32_t accessibility_minimum_font_size;
  char *accessibility_color_filter_name;
  protobuf_c_boolean has_accessibility_desktop_ui_scale;
  float accessibility_desktop_ui_scale;
  char *accessibility_screen_reader_locale;
  protobuf_c_boolean has_accessibility_mono_audio;
  protobuf_c_boolean accessibility_mono_audio;
  protobuf_c_boolean has_remote_play_wifi_ap_enabled;
  protobuf_c_boolean remote_play_wifi_ap_enabled;
  protobuf_c_boolean has_remote_play_wifi_ap_channel_5ghz;
  int32_t remote_play_wifi_ap_channel_5ghz;
  protobuf_c_boolean has_remote_play_wifi_ap_channel_6ghz;
  int32_t remote_play_wifi_ap_channel_6ghz;
  protobuf_c_boolean has_remote_play_wifi_ap_channel_width;
  int32_t remote_play_wifi_ap_channel_width;
  protobuf_c_boolean has_remote_play_wifi_ap_hotspot_mode;
  protobuf_c_boolean remote_play_wifi_ap_hotspot_mode;
  char *remote_play_wifi_ap_hotspot_ssid;
  char *remote_play_wifi_ap_hotspot_password;
  char *remote_play_wifi_ap_hotspot_routing;
  protobuf_c_boolean has_remote_play_wifi_ap_show_advanced;
  protobuf_c_boolean remote_play_wifi_ap_show_advanced;
  char *remote_play_wifi_ap_paired_ssid;
  protobuf_c_boolean has_skip_steamframe_pairing_dialog;
  protobuf_c_boolean skip_steamframe_pairing_dialog;
  protobuf_c_boolean has_skip_steamframe_troubleshooting_dialog;
  protobuf_c_boolean skip_steamframe_troubleshooting_dialog;
  protobuf_c_boolean has_skip_steamframe_airplane_dialog;
  protobuf_c_boolean skip_steamframe_airplane_dialog;
  protobuf_c_boolean has_oobe_completed;
  protobuf_c_boolean oobe_completed;
  protobuf_c_boolean has_oobe_test_mode_enabled;
  protobuf_c_boolean oobe_test_mode_enabled;
  protobuf_c_boolean has_force_oobe;
  protobuf_c_boolean force_oobe;
  protobuf_c_boolean has_oobe_stage_2_completed;
  protobuf_c_boolean oobe_stage_2_completed;
  protobuf_c_boolean has_oobe_stage_2_test_mode_enabled;
  protobuf_c_boolean oobe_stage_2_test_mode_enabled;
  protobuf_c_boolean has_force_stage_2_oobe;
  protobuf_c_boolean force_stage_2_oobe;
};
#define CMSG_CLIENT_SETTINGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_client_settings__descriptor) \
, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, EBROADCAST_PERMISSION__k_EBroadcastPermissionDisabled, 0, 0, 0, 0, 0, 0, 0, EBROADCAST_ENCODER_SETTING__k_EBroadcastEncoderBestQuality, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, NULL, NULL, 0, 0, NULL, 0, EGRMODE__k_EGRMode_Never, 0, EGRAUDIO__k_EGRAudio_Game, 0, 0, NULL, 0, 0, 0, EGREXPORT_LIMIT_TYPE__k_EGRExportLimitType_Native, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, EEXPORT_CODEC__k_EExportCodec_Default, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, EHDRVISUALIZATION__k_EHDRVisualization_None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, EHDRVISUALIZATION__k_EHDRVisualization_None, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* CMsgHotkey methods */
void   cmsg_hotkey__init
                     (CMsgHotkey         *message);
size_t cmsg_hotkey__get_packed_size
                     (const CMsgHotkey   *message);
size_t cmsg_hotkey__pack
                     (const CMsgHotkey   *message,
                      uint8_t             *out);
size_t cmsg_hotkey__pack_to_buffer
                     (const CMsgHotkey   *message,
                      ProtobufCBuffer     *buffer);
CMsgHotkey *
       cmsg_hotkey__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_hotkey__free_unpacked
                     (CMsgHotkey *message,
                      ProtobufCAllocator *allocator);
/* CMsgSettingVariant methods */
void   cmsg_setting_variant__init
                     (CMsgSettingVariant         *message);
size_t cmsg_setting_variant__get_packed_size
                     (const CMsgSettingVariant   *message);
size_t cmsg_setting_variant__pack
                     (const CMsgSettingVariant   *message,
                      uint8_t             *out);
size_t cmsg_setting_variant__pack_to_buffer
                     (const CMsgSettingVariant   *message,
                      ProtobufCBuffer     *buffer);
CMsgSettingVariant *
       cmsg_setting_variant__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_setting_variant__free_unpacked
                     (CMsgSettingVariant *message,
                      ProtobufCAllocator *allocator);
/* CMsgClientSettings methods */
void   cmsg_client_settings__init
                     (CMsgClientSettings         *message);
size_t cmsg_client_settings__get_packed_size
                     (const CMsgClientSettings   *message);
size_t cmsg_client_settings__pack
                     (const CMsgClientSettings   *message,
                      uint8_t             *out);
size_t cmsg_client_settings__pack_to_buffer
                     (const CMsgClientSettings   *message,
                      ProtobufCBuffer     *buffer);
CMsgClientSettings *
       cmsg_client_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_client_settings__free_unpacked
                     (CMsgClientSettings *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CMsgHotkey_Closure)
                 (const CMsgHotkey *message,
                  void *closure_data);
typedef void (*CMsgSettingVariant_Closure)
                 (const CMsgSettingVariant *message,
                  void *closure_data);
typedef void (*CMsgClientSettings_Closure)
                 (const CMsgClientSettings *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    eclient_setting_store__descriptor;
extern const ProtobufCEnumDescriptor    eoverlay_toggle_bar_location__descriptor;
extern const ProtobufCEnumDescriptor    esetting_profile_mode__descriptor;
extern const ProtobufCEnumDescriptor    egraudio__descriptor;
extern const ProtobufCEnumDescriptor    egrexport_limit_type__descriptor;
extern const ProtobufCEnumDescriptor    eframe_rate_report_enabled__descriptor;
extern const ProtobufCMessageDescriptor cmsg_hotkey__descriptor;
extern const ProtobufCMessageDescriptor cmsg_setting_variant__descriptor;
extern const ProtobufCMessageDescriptor cmsg_client_settings__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5fclientsettings_2eproto__INCLUDED */
