/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_unified_test.steamclient.proto */

#ifndef PROTOBUF_C_steammessages_5funified_5ftest_2esteamclient_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5funified_5ftest_2esteamclient_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "steammessages_unified_base.steamclient.pb-c.h"

typedef struct CMsgTestMessageToClientRequest CMsgTestMessageToClientRequest;
typedef struct CMsgTestMessageToClientResponse CMsgTestMessageToClientResponse;
typedef struct CMsgTestNotifyClientNotification CMsgTestNotifyClientNotification;
typedef struct CMsgTestMessageToServerRequest CMsgTestMessageToServerRequest;
typedef struct CMsgTestMessageToServerResponse CMsgTestMessageToServerResponse;
typedef struct CMsgTestNotifyServerNotification CMsgTestNotifyServerNotification;
typedef struct CMsgTestTestClientCallRequest CMsgTestTestClientCallRequest;
typedef struct CMsgTestTestClientCallResponse CMsgTestTestClientCallResponse;
typedef struct CMsgTestNoBodyRequest CMsgTestNoBodyRequest;
typedef struct CMsgTestCallClientResponse CMsgTestCallClientResponse;


/* --- enums --- */


/* --- messages --- */

struct  CMsgTestMessageToClientRequest
{
  ProtobufCMessage base;
  char *some_text;
};
#define CMSG_TEST__MESSAGE_TO_CLIENT__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__message_to_client__request__descriptor) \
, NULL }


struct  CMsgTestMessageToClientResponse
{
  ProtobufCMessage base;
  char *some_text;
};
#define CMSG_TEST__MESSAGE_TO_CLIENT__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__message_to_client__response__descriptor) \
, NULL }


struct  CMsgTestNotifyClientNotification
{
  ProtobufCMessage base;
  char *some_text;
};
#define CMSG_TEST__NOTIFY_CLIENT__NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__notify_client__notification__descriptor) \
, NULL }


struct  CMsgTestMessageToServerRequest
{
  ProtobufCMessage base;
  char *some_text;
};
#define CMSG_TEST__MESSAGE_TO_SERVER__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__message_to_server__request__descriptor) \
, NULL }


struct  CMsgTestMessageToServerResponse
{
  ProtobufCMessage base;
  char *some_text;
};
#define CMSG_TEST__MESSAGE_TO_SERVER__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__message_to_server__response__descriptor) \
, NULL }


struct  CMsgTestNotifyServerNotification
{
  ProtobufCMessage base;
  char *some_text;
};
#define CMSG_TEST__NOTIFY_SERVER__NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__notify_server__notification__descriptor) \
, NULL }


struct  CMsgTestTestClientCallRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_param;
  int32_t param;
};
#define CMSG_TEST__TEST_CLIENT_CALL__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__test_client_call__request__descriptor) \
, 0, 0 }


struct  CMsgTestTestClientCallResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_result;
  int32_t result;
};
#define CMSG_TEST__TEST_CLIENT_CALL__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__test_client_call__response__descriptor) \
, 0, 0 }


struct  CMsgTestNoBodyRequest
{
  ProtobufCMessage base;
};
#define CMSG_TEST__NO_BODY__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__no_body__request__descriptor) \
 }


struct  CMsgTestCallClientResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_testvalue;
  int32_t testvalue;
};
#define CMSG_TEST__CALL_CLIENT__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg_test__call_client__response__descriptor) \
, 0, 0 }


/* CMsgTestMessageToClientRequest methods */
void   cmsg_test__message_to_client__request__init
                     (CMsgTestMessageToClientRequest         *message);
size_t cmsg_test__message_to_client__request__get_packed_size
                     (const CMsgTestMessageToClientRequest   *message);
size_t cmsg_test__message_to_client__request__pack
                     (const CMsgTestMessageToClientRequest   *message,
                      uint8_t             *out);
size_t cmsg_test__message_to_client__request__pack_to_buffer
                     (const CMsgTestMessageToClientRequest   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestMessageToClientRequest *
       cmsg_test__message_to_client__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__message_to_client__request__free_unpacked
                     (CMsgTestMessageToClientRequest *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestMessageToClientResponse methods */
void   cmsg_test__message_to_client__response__init
                     (CMsgTestMessageToClientResponse         *message);
size_t cmsg_test__message_to_client__response__get_packed_size
                     (const CMsgTestMessageToClientResponse   *message);
size_t cmsg_test__message_to_client__response__pack
                     (const CMsgTestMessageToClientResponse   *message,
                      uint8_t             *out);
size_t cmsg_test__message_to_client__response__pack_to_buffer
                     (const CMsgTestMessageToClientResponse   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestMessageToClientResponse *
       cmsg_test__message_to_client__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__message_to_client__response__free_unpacked
                     (CMsgTestMessageToClientResponse *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestNotifyClientNotification methods */
void   cmsg_test__notify_client__notification__init
                     (CMsgTestNotifyClientNotification         *message);
size_t cmsg_test__notify_client__notification__get_packed_size
                     (const CMsgTestNotifyClientNotification   *message);
size_t cmsg_test__notify_client__notification__pack
                     (const CMsgTestNotifyClientNotification   *message,
                      uint8_t             *out);
size_t cmsg_test__notify_client__notification__pack_to_buffer
                     (const CMsgTestNotifyClientNotification   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestNotifyClientNotification *
       cmsg_test__notify_client__notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__notify_client__notification__free_unpacked
                     (CMsgTestNotifyClientNotification *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestMessageToServerRequest methods */
void   cmsg_test__message_to_server__request__init
                     (CMsgTestMessageToServerRequest         *message);
size_t cmsg_test__message_to_server__request__get_packed_size
                     (const CMsgTestMessageToServerRequest   *message);
size_t cmsg_test__message_to_server__request__pack
                     (const CMsgTestMessageToServerRequest   *message,
                      uint8_t             *out);
size_t cmsg_test__message_to_server__request__pack_to_buffer
                     (const CMsgTestMessageToServerRequest   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestMessageToServerRequest *
       cmsg_test__message_to_server__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__message_to_server__request__free_unpacked
                     (CMsgTestMessageToServerRequest *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestMessageToServerResponse methods */
void   cmsg_test__message_to_server__response__init
                     (CMsgTestMessageToServerResponse         *message);
size_t cmsg_test__message_to_server__response__get_packed_size
                     (const CMsgTestMessageToServerResponse   *message);
size_t cmsg_test__message_to_server__response__pack
                     (const CMsgTestMessageToServerResponse   *message,
                      uint8_t             *out);
size_t cmsg_test__message_to_server__response__pack_to_buffer
                     (const CMsgTestMessageToServerResponse   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestMessageToServerResponse *
       cmsg_test__message_to_server__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__message_to_server__response__free_unpacked
                     (CMsgTestMessageToServerResponse *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestNotifyServerNotification methods */
void   cmsg_test__notify_server__notification__init
                     (CMsgTestNotifyServerNotification         *message);
size_t cmsg_test__notify_server__notification__get_packed_size
                     (const CMsgTestNotifyServerNotification   *message);
size_t cmsg_test__notify_server__notification__pack
                     (const CMsgTestNotifyServerNotification   *message,
                      uint8_t             *out);
size_t cmsg_test__notify_server__notification__pack_to_buffer
                     (const CMsgTestNotifyServerNotification   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestNotifyServerNotification *
       cmsg_test__notify_server__notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__notify_server__notification__free_unpacked
                     (CMsgTestNotifyServerNotification *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestTestClientCallRequest methods */
void   cmsg_test__test_client_call__request__init
                     (CMsgTestTestClientCallRequest         *message);
size_t cmsg_test__test_client_call__request__get_packed_size
                     (const CMsgTestTestClientCallRequest   *message);
size_t cmsg_test__test_client_call__request__pack
                     (const CMsgTestTestClientCallRequest   *message,
                      uint8_t             *out);
size_t cmsg_test__test_client_call__request__pack_to_buffer
                     (const CMsgTestTestClientCallRequest   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestTestClientCallRequest *
       cmsg_test__test_client_call__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__test_client_call__request__free_unpacked
                     (CMsgTestTestClientCallRequest *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestTestClientCallResponse methods */
void   cmsg_test__test_client_call__response__init
                     (CMsgTestTestClientCallResponse         *message);
size_t cmsg_test__test_client_call__response__get_packed_size
                     (const CMsgTestTestClientCallResponse   *message);
size_t cmsg_test__test_client_call__response__pack
                     (const CMsgTestTestClientCallResponse   *message,
                      uint8_t             *out);
size_t cmsg_test__test_client_call__response__pack_to_buffer
                     (const CMsgTestTestClientCallResponse   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestTestClientCallResponse *
       cmsg_test__test_client_call__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__test_client_call__response__free_unpacked
                     (CMsgTestTestClientCallResponse *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestNoBodyRequest methods */
void   cmsg_test__no_body__request__init
                     (CMsgTestNoBodyRequest         *message);
size_t cmsg_test__no_body__request__get_packed_size
                     (const CMsgTestNoBodyRequest   *message);
size_t cmsg_test__no_body__request__pack
                     (const CMsgTestNoBodyRequest   *message,
                      uint8_t             *out);
size_t cmsg_test__no_body__request__pack_to_buffer
                     (const CMsgTestNoBodyRequest   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestNoBodyRequest *
       cmsg_test__no_body__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__no_body__request__free_unpacked
                     (CMsgTestNoBodyRequest *message,
                      ProtobufCAllocator *allocator);
/* CMsgTestCallClientResponse methods */
void   cmsg_test__call_client__response__init
                     (CMsgTestCallClientResponse         *message);
size_t cmsg_test__call_client__response__get_packed_size
                     (const CMsgTestCallClientResponse   *message);
size_t cmsg_test__call_client__response__pack
                     (const CMsgTestCallClientResponse   *message,
                      uint8_t             *out);
size_t cmsg_test__call_client__response__pack_to_buffer
                     (const CMsgTestCallClientResponse   *message,
                      ProtobufCBuffer     *buffer);
CMsgTestCallClientResponse *
       cmsg_test__call_client__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg_test__call_client__response__free_unpacked
                     (CMsgTestCallClientResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CMsgTestMessageToClientRequest_Closure)
                 (const CMsgTestMessageToClientRequest *message,
                  void *closure_data);
typedef void (*CMsgTestMessageToClientResponse_Closure)
                 (const CMsgTestMessageToClientResponse *message,
                  void *closure_data);
typedef void (*CMsgTestNotifyClientNotification_Closure)
                 (const CMsgTestNotifyClientNotification *message,
                  void *closure_data);
typedef void (*CMsgTestMessageToServerRequest_Closure)
                 (const CMsgTestMessageToServerRequest *message,
                  void *closure_data);
typedef void (*CMsgTestMessageToServerResponse_Closure)
                 (const CMsgTestMessageToServerResponse *message,
                  void *closure_data);
typedef void (*CMsgTestNotifyServerNotification_Closure)
                 (const CMsgTestNotifyServerNotification *message,
                  void *closure_data);
typedef void (*CMsgTestTestClientCallRequest_Closure)
                 (const CMsgTestTestClientCallRequest *message,
                  void *closure_data);
typedef void (*CMsgTestTestClientCallResponse_Closure)
                 (const CMsgTestTestClientCallResponse *message,
                  void *closure_data);
typedef void (*CMsgTestNoBodyRequest_Closure)
                 (const CMsgTestNoBodyRequest *message,
                  void *closure_data);
typedef void (*CMsgTestCallClientResponse_Closure)
                 (const CMsgTestCallClientResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct TestSteamClient_Service TestSteamClient_Service;
struct TestSteamClient_Service
{
  ProtobufCService base;
  void (*message_to_client)(TestSteamClient_Service *service,
                            const CMsgTestMessageToClientRequest *input,
                            CMsgTestMessageToClientResponse_Closure closure,
                            void *closure_data);
  void (*notify_client)(TestSteamClient_Service *service,
                        const CMsgTestNotifyClientNotification *input,
                        NoResponse_Closure closure,
                        void *closure_data);
};
typedef void (*TestSteamClient_ServiceDestroy)(TestSteamClient_Service *);
void test_steam_client__init (TestSteamClient_Service *service,
                              TestSteamClient_ServiceDestroy destroy);
#define TEST_STEAM_CLIENT__BASE_INIT \
    { &test_steam_client__descriptor, protobuf_c_service_invoke_internal, NULL }
#define TEST_STEAM_CLIENT__INIT(function_prefix__) \
    { TEST_STEAM_CLIENT__BASE_INIT,\
      function_prefix__ ## message_to_client,\
      function_prefix__ ## notify_client  }
void test_steam_client__message_to_client(ProtobufCService *service,
                                          const CMsgTestMessageToClientRequest *input,
                                          CMsgTestMessageToClientResponse_Closure closure,
                                          void *closure_data);
void test_steam_client__notify_client(ProtobufCService *service,
                                      const CMsgTestNotifyClientNotification *input,
                                      NoResponse_Closure closure,
                                      void *closure_data);
typedef struct TestServerFromClient_Service TestServerFromClient_Service;
struct TestServerFromClient_Service
{
  ProtobufCService base;
  void (*message_to_server)(TestServerFromClient_Service *service,
                            const CMsgTestMessageToServerRequest *input,
                            CMsgTestMessageToServerResponse_Closure closure,
                            void *closure_data);
  void (*notify_server)(TestServerFromClient_Service *service,
                        const CMsgTestNotifyServerNotification *input,
                        NoResponse_Closure closure,
                        void *closure_data);
  void (*client_call_authed1)(TestServerFromClient_Service *service,
                              const CMsgTestTestClientCallRequest *input,
                              CMsgTestTestClientCallResponse_Closure closure,
                              void *closure_data);
  void (*client_call_authed2)(TestServerFromClient_Service *service,
                              const CMsgTestTestClientCallRequest *input,
                              CMsgTestTestClientCallResponse_Closure closure,
                              void *closure_data);
  void (*client_call_authed3)(TestServerFromClient_Service *service,
                              const CMsgTestTestClientCallRequest *input,
                              CMsgTestTestClientCallResponse_Closure closure,
                              void *closure_data);
  void (*client_call_authed4)(TestServerFromClient_Service *service,
                              const CMsgTestTestClientCallRequest *input,
                              CMsgTestTestClientCallResponse_Closure closure,
                              void *closure_data);
};
typedef void (*TestServerFromClient_ServiceDestroy)(TestServerFromClient_Service *);
void test_server_from_client__init (TestServerFromClient_Service *service,
                                    TestServerFromClient_ServiceDestroy destroy);
#define TEST_SERVER_FROM_CLIENT__BASE_INIT \
    { &test_server_from_client__descriptor, protobuf_c_service_invoke_internal, NULL }
#define TEST_SERVER_FROM_CLIENT__INIT(function_prefix__) \
    { TEST_SERVER_FROM_CLIENT__BASE_INIT,\
      function_prefix__ ## message_to_server,\
      function_prefix__ ## notify_server,\
      function_prefix__ ## client_call_authed1,\
      function_prefix__ ## client_call_authed2,\
      function_prefix__ ## client_call_authed3,\
      function_prefix__ ## client_call_authed4  }
void test_server_from_client__message_to_server(ProtobufCService *service,
                                                const CMsgTestMessageToServerRequest *input,
                                                CMsgTestMessageToServerResponse_Closure closure,
                                                void *closure_data);
void test_server_from_client__notify_server(ProtobufCService *service,
                                            const CMsgTestNotifyServerNotification *input,
                                            NoResponse_Closure closure,
                                            void *closure_data);
void test_server_from_client__client_call_authed1(ProtobufCService *service,
                                                  const CMsgTestTestClientCallRequest *input,
                                                  CMsgTestTestClientCallResponse_Closure closure,
                                                  void *closure_data);
void test_server_from_client__client_call_authed2(ProtobufCService *service,
                                                  const CMsgTestTestClientCallRequest *input,
                                                  CMsgTestTestClientCallResponse_Closure closure,
                                                  void *closure_data);
void test_server_from_client__client_call_authed3(ProtobufCService *service,
                                                  const CMsgTestTestClientCallRequest *input,
                                                  CMsgTestTestClientCallResponse_Closure closure,
                                                  void *closure_data);
void test_server_from_client__client_call_authed4(ProtobufCService *service,
                                                  const CMsgTestTestClientCallRequest *input,
                                                  CMsgTestTestClientCallResponse_Closure closure,
                                                  void *closure_data);
typedef struct TestExternalPrivilege_Service TestExternalPrivilege_Service;
struct TestExternalPrivilege_Service
{
  ProtobufCService base;
  void (*call_client)(TestExternalPrivilege_Service *service,
                      const CMsgTestNoBodyRequest *input,
                      CMsgTestCallClientResponse_Closure closure,
                      void *closure_data);
};
typedef void (*TestExternalPrivilege_ServiceDestroy)(TestExternalPrivilege_Service *);
void test_external_privilege__init (TestExternalPrivilege_Service *service,
                                    TestExternalPrivilege_ServiceDestroy destroy);
#define TEST_EXTERNAL_PRIVILEGE__BASE_INIT \
    { &test_external_privilege__descriptor, protobuf_c_service_invoke_internal, NULL }
#define TEST_EXTERNAL_PRIVILEGE__INIT(function_prefix__) \
    { TEST_EXTERNAL_PRIVILEGE__BASE_INIT,\
      function_prefix__ ## call_client  }
void test_external_privilege__call_client(ProtobufCService *service,
                                          const CMsgTestNoBodyRequest *input,
                                          CMsgTestCallClientResponse_Closure closure,
                                          void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cmsg_test__message_to_client__request__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__message_to_client__response__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__notify_client__notification__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__message_to_server__request__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__message_to_server__response__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__notify_server__notification__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__test_client_call__request__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__test_client_call__response__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__no_body__request__descriptor;
extern const ProtobufCMessageDescriptor cmsg_test__call_client__response__descriptor;
extern const ProtobufCServiceDescriptor test_steam_client__descriptor;
extern const ProtobufCServiceDescriptor test_server_from_client__descriptor;
extern const ProtobufCServiceDescriptor test_external_privilege__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5funified_5ftest_2esteamclient_2eproto__INCLUDED */
