/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_inventory.steamclient.proto */

#ifndef PROTOBUF_C_steammessages_5finventory_2esteamclient_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5finventory_2esteamclient_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "steammessages_unified_base.steamclient.pb-c.h"

typedef struct CInventoryGetInventoryRequest CInventoryGetInventoryRequest;
typedef struct CInventoryResponse CInventoryResponse;
typedef struct CInventoryExchangeItemRequest CInventoryExchangeItemRequest;
typedef struct CInventoryGetEligiblePromoItemDefIDsRequest CInventoryGetEligiblePromoItemDefIDsRequest;
typedef struct CInventoryGetEligiblePromoItemDefIDsResponse CInventoryGetEligiblePromoItemDefIDsResponse;
typedef struct CInventoryAddItemRequest CInventoryAddItemRequest;
typedef struct CInventoryModifyItemsRequest CInventoryModifyItemsRequest;
typedef struct CInventoryModifyItemsRequest__ItemPropertyUpdate CInventoryModifyItemsRequest__ItemPropertyUpdate;
typedef struct CInventoryConsumePlaytimeRequest CInventoryConsumePlaytimeRequest;
typedef struct CInventoryConsumeItemRequest CInventoryConsumeItemRequest;
typedef struct CInventoryDevSetNextDropRequest CInventoryDevSetNextDropRequest;
typedef struct CInventorySplitItemStackRequest CInventorySplitItemStackRequest;
typedef struct CInventoryCombineItemStacksRequest CInventoryCombineItemStacksRequest;
typedef struct CInventoryGetItemDefMetaRequest CInventoryGetItemDefMetaRequest;
typedef struct CInventoryGetItemDefMetaResponse CInventoryGetItemDefMetaResponse;
typedef struct CInventoryGetUserPurchaseInfoRequest CInventoryGetUserPurchaseInfoRequest;
typedef struct CInventoryGetUserPurchaseInfoResponse CInventoryGetUserPurchaseInfoResponse;
typedef struct CInventoryPurchaseInitRequest CInventoryPurchaseInitRequest;
typedef struct CInventoryPurchaseInitRequest__LineItem CInventoryPurchaseInitRequest__LineItem;
typedef struct CInventoryPurchaseInitResponse CInventoryPurchaseInitResponse;
typedef struct CInventoryPurchaseFinalizeRequest CInventoryPurchaseFinalizeRequest;
typedef struct CInventoryInspectItemRequest CInventoryInspectItemRequest;
typedef struct CInventoryClientNewItemsNotification CInventoryClientNewItemsNotification;


/* --- enums --- */


/* --- messages --- */

struct  CInventoryGetInventoryRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
};
#define CINVENTORY__GET_INVENTORY__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__get_inventory__request__descriptor) \
, 0, 0, 0, 0 }


struct  CInventoryResponse
{
  ProtobufCMessage base;
  char *etag;
  size_t n_removeditemids;
  uint64_t *removeditemids;
  char *item_json;
  char *itemdef_json;
  protobuf_c_boolean has_ticket;
  ProtobufCBinaryData ticket;
  protobuf_c_boolean has_replayed;
  protobuf_c_boolean replayed;
};
#define CINVENTORY__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__response__descriptor) \
, NULL, 0,NULL, NULL, NULL, 0, {0,NULL}, 0, 0 }


struct  CInventoryExchangeItemRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  size_t n_materialsitemid;
  uint64_t *materialsitemid;
  size_t n_materialsquantity;
  uint32_t *materialsquantity;
  protobuf_c_boolean has_outputitemdefid;
  uint64_t outputitemdefid;
};
#define CINVENTORY__EXCHANGE_ITEM__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__exchange_item__request__descriptor) \
, 0, 0, 0, 0, 0,NULL, 0,NULL, 0, 0 }


struct  CInventoryGetEligiblePromoItemDefIDsRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
};
#define CINVENTORY__GET_ELIGIBLE_PROMO_ITEM_DEF_IDS__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__get_eligible_promo_item_def_ids__request__descriptor) \
, 0, 0, 0, 0 }


struct  CInventoryGetEligiblePromoItemDefIDsResponse
{
  ProtobufCMessage base;
  size_t n_itemdefids;
  uint64_t *itemdefids;
};
#define CINVENTORY__GET_ELIGIBLE_PROMO_ITEM_DEF_IDS__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__get_eligible_promo_item_def_ids__response__descriptor) \
, 0,NULL }


struct  CInventoryAddItemRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  size_t n_itemdefid;
  uint64_t *itemdefid;
  size_t n_itempropsjson;
  char **itempropsjson;
  size_t n_itemquantity;
  uint32_t *itemquantity;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  protobuf_c_boolean has_notify;
  protobuf_c_boolean notify;
  protobuf_c_boolean has_requestid;
  uint64_t requestid;
  protobuf_c_boolean has_trade_restriction;
  protobuf_c_boolean trade_restriction;
  protobuf_c_boolean has_is_purchase;
  protobuf_c_boolean is_purchase;
};
#define CINVENTORY__ADD_ITEM__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__add_item__request__descriptor) \
, 0, 0, 0,NULL, 0,NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CInventoryModifyItemsRequest__ItemPropertyUpdate
{
  ProtobufCMessage base;
  protobuf_c_boolean has_itemid;
  uint64_t itemid;
  protobuf_c_boolean has_remove_property;
  protobuf_c_boolean remove_property;
  char *property_name;
  protobuf_c_boolean has_property_value_bool;
  protobuf_c_boolean property_value_bool;
  protobuf_c_boolean has_property_value_int;
  int64_t property_value_int;
  char *property_value_string;
  protobuf_c_boolean has_property_value_float;
  float property_value_float;
};
#define CINVENTORY__MODIFY_ITEMS__REQUEST__ITEM_PROPERTY_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__modify_items__request__item_property_update__descriptor) \
, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0 }


struct  CInventoryModifyItemsRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  size_t n_updates;
  CInventoryModifyItemsRequest__ItemPropertyUpdate **updates;
  protobuf_c_boolean has_timestamp;
  uint32_t timestamp;
};
#define CINVENTORY__MODIFY_ITEMS__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__modify_items__request__descriptor) \
, 0, 0, 0, 0, 0,NULL, 0, 0 }


struct  CInventoryConsumePlaytimeRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_itemdefid;
  uint64_t itemdefid;
};
#define CINVENTORY__CONSUME_PLAYTIME__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__consume_playtime__request__descriptor) \
, 0, 0, 0, 0 }


struct  CInventoryConsumeItemRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_itemid;
  uint64_t itemid;
  protobuf_c_boolean has_quantity;
  uint32_t quantity;
  char *timestamp;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  protobuf_c_boolean has_requestid;
  uint64_t requestid;
};
#define CINVENTORY__CONSUME_ITEM__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__consume_item__request__descriptor) \
, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0 }


struct  CInventoryDevSetNextDropRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_itemdefid;
  uint64_t itemdefid;
  char *droptime;
};
#define CINVENTORY__DEV_SET_NEXT_DROP__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__dev_set_next_drop__request__descriptor) \
, 0, 0, 0, 0, NULL }


struct  CInventorySplitItemStackRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_itemid;
  uint64_t itemid;
  protobuf_c_boolean has_quantity;
  uint32_t quantity;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
};
#define CINVENTORY__SPLIT_ITEM_STACK__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__split_item_stack__request__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CInventoryCombineItemStacksRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_fromitemid;
  uint64_t fromitemid;
  protobuf_c_boolean has_destitemid;
  uint64_t destitemid;
  protobuf_c_boolean has_quantity;
  uint32_t quantity;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
};
#define CINVENTORY__COMBINE_ITEM_STACKS__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__combine_item_stacks__request__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CInventoryGetItemDefMetaRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
};
#define CINVENTORY__GET_ITEM_DEF_META__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__get_item_def_meta__request__descriptor) \
, 0, 0 }


struct  CInventoryGetItemDefMetaResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_modified;
  uint32_t modified;
  char *digest;
};
#define CINVENTORY__GET_ITEM_DEF_META__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__get_item_def_meta__response__descriptor) \
, 0, 0, NULL }


struct  CInventoryGetUserPurchaseInfoRequest
{
  ProtobufCMessage base;
};
#define CINVENTORY__GET_USER_PURCHASE_INFO__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__get_user_purchase_info__request__descriptor) \
 }


struct  CInventoryGetUserPurchaseInfoResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_ecurrency;
  int32_t ecurrency;
};
#define CINVENTORY__GET_USER_PURCHASE_INFO__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__get_user_purchase_info__response__descriptor) \
, 0, 0 }


struct  CInventoryPurchaseInitRequest__LineItem
{
  ProtobufCMessage base;
  protobuf_c_boolean has_itemdefid;
  uint64_t itemdefid;
  protobuf_c_boolean has_quantity;
  uint32_t quantity;
};
#define CINVENTORY__PURCHASE_INIT__REQUEST__LINE_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__purchase_init__request__line_item__descriptor) \
, 0, 0, 0, 0 }


struct  CInventoryPurchaseInitRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_language;
  int32_t language;
  size_t n_line_items;
  CInventoryPurchaseInitRequest__LineItem **line_items;
};
#define CINVENTORY__PURCHASE_INIT__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__purchase_init__request__descriptor) \
, 0, 0, 0, 0, 0,NULL }


struct  CInventoryPurchaseInitResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_orderid;
  uint64_t orderid;
  protobuf_c_boolean has_transid;
  uint64_t transid;
};
#define CINVENTORY__PURCHASE_INIT__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__purchase_init__response__descriptor) \
, 0, 0, 0, 0 }


struct  CInventoryPurchaseFinalizeRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_language;
  int32_t language;
  protobuf_c_boolean has_orderid;
  uint64_t orderid;
};
#define CINVENTORY__PURCHASE_FINALIZE__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__purchase_finalize__request__descriptor) \
, 0, 0, 0, 0, 0, 0 }


struct  CInventoryInspectItemRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_itemdefid;
  uint64_t itemdefid;
  protobuf_c_boolean has_itemid;
  uint64_t itemid;
  char *tags;
};
#define CINVENTORY__INSPECT_ITEM__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory__inspect_item__request__descriptor) \
, 0, 0, 0, 0, NULL }


struct  CInventoryClientNewItemsNotification
{
  ProtobufCMessage base;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  CInventoryResponse *inventory_response;
};
#define CINVENTORY_CLIENT__NEW_ITEMS__NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cinventory_client__new_items__notification__descriptor) \
, 0, 0, NULL }


/* CInventoryGetInventoryRequest methods */
void   cinventory__get_inventory__request__init
                     (CInventoryGetInventoryRequest         *message);
size_t cinventory__get_inventory__request__get_packed_size
                     (const CInventoryGetInventoryRequest   *message);
size_t cinventory__get_inventory__request__pack
                     (const CInventoryGetInventoryRequest   *message,
                      uint8_t             *out);
size_t cinventory__get_inventory__request__pack_to_buffer
                     (const CInventoryGetInventoryRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryGetInventoryRequest *
       cinventory__get_inventory__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__get_inventory__request__free_unpacked
                     (CInventoryGetInventoryRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryResponse methods */
void   cinventory__response__init
                     (CInventoryResponse         *message);
size_t cinventory__response__get_packed_size
                     (const CInventoryResponse   *message);
size_t cinventory__response__pack
                     (const CInventoryResponse   *message,
                      uint8_t             *out);
size_t cinventory__response__pack_to_buffer
                     (const CInventoryResponse   *message,
                      ProtobufCBuffer     *buffer);
CInventoryResponse *
       cinventory__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__response__free_unpacked
                     (CInventoryResponse *message,
                      ProtobufCAllocator *allocator);
/* CInventoryExchangeItemRequest methods */
void   cinventory__exchange_item__request__init
                     (CInventoryExchangeItemRequest         *message);
size_t cinventory__exchange_item__request__get_packed_size
                     (const CInventoryExchangeItemRequest   *message);
size_t cinventory__exchange_item__request__pack
                     (const CInventoryExchangeItemRequest   *message,
                      uint8_t             *out);
size_t cinventory__exchange_item__request__pack_to_buffer
                     (const CInventoryExchangeItemRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryExchangeItemRequest *
       cinventory__exchange_item__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__exchange_item__request__free_unpacked
                     (CInventoryExchangeItemRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryGetEligiblePromoItemDefIDsRequest methods */
void   cinventory__get_eligible_promo_item_def_ids__request__init
                     (CInventoryGetEligiblePromoItemDefIDsRequest         *message);
size_t cinventory__get_eligible_promo_item_def_ids__request__get_packed_size
                     (const CInventoryGetEligiblePromoItemDefIDsRequest   *message);
size_t cinventory__get_eligible_promo_item_def_ids__request__pack
                     (const CInventoryGetEligiblePromoItemDefIDsRequest   *message,
                      uint8_t             *out);
size_t cinventory__get_eligible_promo_item_def_ids__request__pack_to_buffer
                     (const CInventoryGetEligiblePromoItemDefIDsRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryGetEligiblePromoItemDefIDsRequest *
       cinventory__get_eligible_promo_item_def_ids__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__get_eligible_promo_item_def_ids__request__free_unpacked
                     (CInventoryGetEligiblePromoItemDefIDsRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryGetEligiblePromoItemDefIDsResponse methods */
void   cinventory__get_eligible_promo_item_def_ids__response__init
                     (CInventoryGetEligiblePromoItemDefIDsResponse         *message);
size_t cinventory__get_eligible_promo_item_def_ids__response__get_packed_size
                     (const CInventoryGetEligiblePromoItemDefIDsResponse   *message);
size_t cinventory__get_eligible_promo_item_def_ids__response__pack
                     (const CInventoryGetEligiblePromoItemDefIDsResponse   *message,
                      uint8_t             *out);
size_t cinventory__get_eligible_promo_item_def_ids__response__pack_to_buffer
                     (const CInventoryGetEligiblePromoItemDefIDsResponse   *message,
                      ProtobufCBuffer     *buffer);
CInventoryGetEligiblePromoItemDefIDsResponse *
       cinventory__get_eligible_promo_item_def_ids__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__get_eligible_promo_item_def_ids__response__free_unpacked
                     (CInventoryGetEligiblePromoItemDefIDsResponse *message,
                      ProtobufCAllocator *allocator);
/* CInventoryAddItemRequest methods */
void   cinventory__add_item__request__init
                     (CInventoryAddItemRequest         *message);
size_t cinventory__add_item__request__get_packed_size
                     (const CInventoryAddItemRequest   *message);
size_t cinventory__add_item__request__pack
                     (const CInventoryAddItemRequest   *message,
                      uint8_t             *out);
size_t cinventory__add_item__request__pack_to_buffer
                     (const CInventoryAddItemRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryAddItemRequest *
       cinventory__add_item__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__add_item__request__free_unpacked
                     (CInventoryAddItemRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryModifyItemsRequest__ItemPropertyUpdate methods */
void   cinventory__modify_items__request__item_property_update__init
                     (CInventoryModifyItemsRequest__ItemPropertyUpdate         *message);
/* CInventoryModifyItemsRequest methods */
void   cinventory__modify_items__request__init
                     (CInventoryModifyItemsRequest         *message);
size_t cinventory__modify_items__request__get_packed_size
                     (const CInventoryModifyItemsRequest   *message);
size_t cinventory__modify_items__request__pack
                     (const CInventoryModifyItemsRequest   *message,
                      uint8_t             *out);
size_t cinventory__modify_items__request__pack_to_buffer
                     (const CInventoryModifyItemsRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryModifyItemsRequest *
       cinventory__modify_items__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__modify_items__request__free_unpacked
                     (CInventoryModifyItemsRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryConsumePlaytimeRequest methods */
void   cinventory__consume_playtime__request__init
                     (CInventoryConsumePlaytimeRequest         *message);
size_t cinventory__consume_playtime__request__get_packed_size
                     (const CInventoryConsumePlaytimeRequest   *message);
size_t cinventory__consume_playtime__request__pack
                     (const CInventoryConsumePlaytimeRequest   *message,
                      uint8_t             *out);
size_t cinventory__consume_playtime__request__pack_to_buffer
                     (const CInventoryConsumePlaytimeRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryConsumePlaytimeRequest *
       cinventory__consume_playtime__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__consume_playtime__request__free_unpacked
                     (CInventoryConsumePlaytimeRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryConsumeItemRequest methods */
void   cinventory__consume_item__request__init
                     (CInventoryConsumeItemRequest         *message);
size_t cinventory__consume_item__request__get_packed_size
                     (const CInventoryConsumeItemRequest   *message);
size_t cinventory__consume_item__request__pack
                     (const CInventoryConsumeItemRequest   *message,
                      uint8_t             *out);
size_t cinventory__consume_item__request__pack_to_buffer
                     (const CInventoryConsumeItemRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryConsumeItemRequest *
       cinventory__consume_item__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__consume_item__request__free_unpacked
                     (CInventoryConsumeItemRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryDevSetNextDropRequest methods */
void   cinventory__dev_set_next_drop__request__init
                     (CInventoryDevSetNextDropRequest         *message);
size_t cinventory__dev_set_next_drop__request__get_packed_size
                     (const CInventoryDevSetNextDropRequest   *message);
size_t cinventory__dev_set_next_drop__request__pack
                     (const CInventoryDevSetNextDropRequest   *message,
                      uint8_t             *out);
size_t cinventory__dev_set_next_drop__request__pack_to_buffer
                     (const CInventoryDevSetNextDropRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryDevSetNextDropRequest *
       cinventory__dev_set_next_drop__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__dev_set_next_drop__request__free_unpacked
                     (CInventoryDevSetNextDropRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventorySplitItemStackRequest methods */
void   cinventory__split_item_stack__request__init
                     (CInventorySplitItemStackRequest         *message);
size_t cinventory__split_item_stack__request__get_packed_size
                     (const CInventorySplitItemStackRequest   *message);
size_t cinventory__split_item_stack__request__pack
                     (const CInventorySplitItemStackRequest   *message,
                      uint8_t             *out);
size_t cinventory__split_item_stack__request__pack_to_buffer
                     (const CInventorySplitItemStackRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventorySplitItemStackRequest *
       cinventory__split_item_stack__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__split_item_stack__request__free_unpacked
                     (CInventorySplitItemStackRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryCombineItemStacksRequest methods */
void   cinventory__combine_item_stacks__request__init
                     (CInventoryCombineItemStacksRequest         *message);
size_t cinventory__combine_item_stacks__request__get_packed_size
                     (const CInventoryCombineItemStacksRequest   *message);
size_t cinventory__combine_item_stacks__request__pack
                     (const CInventoryCombineItemStacksRequest   *message,
                      uint8_t             *out);
size_t cinventory__combine_item_stacks__request__pack_to_buffer
                     (const CInventoryCombineItemStacksRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryCombineItemStacksRequest *
       cinventory__combine_item_stacks__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__combine_item_stacks__request__free_unpacked
                     (CInventoryCombineItemStacksRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryGetItemDefMetaRequest methods */
void   cinventory__get_item_def_meta__request__init
                     (CInventoryGetItemDefMetaRequest         *message);
size_t cinventory__get_item_def_meta__request__get_packed_size
                     (const CInventoryGetItemDefMetaRequest   *message);
size_t cinventory__get_item_def_meta__request__pack
                     (const CInventoryGetItemDefMetaRequest   *message,
                      uint8_t             *out);
size_t cinventory__get_item_def_meta__request__pack_to_buffer
                     (const CInventoryGetItemDefMetaRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryGetItemDefMetaRequest *
       cinventory__get_item_def_meta__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__get_item_def_meta__request__free_unpacked
                     (CInventoryGetItemDefMetaRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryGetItemDefMetaResponse methods */
void   cinventory__get_item_def_meta__response__init
                     (CInventoryGetItemDefMetaResponse         *message);
size_t cinventory__get_item_def_meta__response__get_packed_size
                     (const CInventoryGetItemDefMetaResponse   *message);
size_t cinventory__get_item_def_meta__response__pack
                     (const CInventoryGetItemDefMetaResponse   *message,
                      uint8_t             *out);
size_t cinventory__get_item_def_meta__response__pack_to_buffer
                     (const CInventoryGetItemDefMetaResponse   *message,
                      ProtobufCBuffer     *buffer);
CInventoryGetItemDefMetaResponse *
       cinventory__get_item_def_meta__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__get_item_def_meta__response__free_unpacked
                     (CInventoryGetItemDefMetaResponse *message,
                      ProtobufCAllocator *allocator);
/* CInventoryGetUserPurchaseInfoRequest methods */
void   cinventory__get_user_purchase_info__request__init
                     (CInventoryGetUserPurchaseInfoRequest         *message);
size_t cinventory__get_user_purchase_info__request__get_packed_size
                     (const CInventoryGetUserPurchaseInfoRequest   *message);
size_t cinventory__get_user_purchase_info__request__pack
                     (const CInventoryGetUserPurchaseInfoRequest   *message,
                      uint8_t             *out);
size_t cinventory__get_user_purchase_info__request__pack_to_buffer
                     (const CInventoryGetUserPurchaseInfoRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryGetUserPurchaseInfoRequest *
       cinventory__get_user_purchase_info__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__get_user_purchase_info__request__free_unpacked
                     (CInventoryGetUserPurchaseInfoRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryGetUserPurchaseInfoResponse methods */
void   cinventory__get_user_purchase_info__response__init
                     (CInventoryGetUserPurchaseInfoResponse         *message);
size_t cinventory__get_user_purchase_info__response__get_packed_size
                     (const CInventoryGetUserPurchaseInfoResponse   *message);
size_t cinventory__get_user_purchase_info__response__pack
                     (const CInventoryGetUserPurchaseInfoResponse   *message,
                      uint8_t             *out);
size_t cinventory__get_user_purchase_info__response__pack_to_buffer
                     (const CInventoryGetUserPurchaseInfoResponse   *message,
                      ProtobufCBuffer     *buffer);
CInventoryGetUserPurchaseInfoResponse *
       cinventory__get_user_purchase_info__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__get_user_purchase_info__response__free_unpacked
                     (CInventoryGetUserPurchaseInfoResponse *message,
                      ProtobufCAllocator *allocator);
/* CInventoryPurchaseInitRequest__LineItem methods */
void   cinventory__purchase_init__request__line_item__init
                     (CInventoryPurchaseInitRequest__LineItem         *message);
/* CInventoryPurchaseInitRequest methods */
void   cinventory__purchase_init__request__init
                     (CInventoryPurchaseInitRequest         *message);
size_t cinventory__purchase_init__request__get_packed_size
                     (const CInventoryPurchaseInitRequest   *message);
size_t cinventory__purchase_init__request__pack
                     (const CInventoryPurchaseInitRequest   *message,
                      uint8_t             *out);
size_t cinventory__purchase_init__request__pack_to_buffer
                     (const CInventoryPurchaseInitRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryPurchaseInitRequest *
       cinventory__purchase_init__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__purchase_init__request__free_unpacked
                     (CInventoryPurchaseInitRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryPurchaseInitResponse methods */
void   cinventory__purchase_init__response__init
                     (CInventoryPurchaseInitResponse         *message);
size_t cinventory__purchase_init__response__get_packed_size
                     (const CInventoryPurchaseInitResponse   *message);
size_t cinventory__purchase_init__response__pack
                     (const CInventoryPurchaseInitResponse   *message,
                      uint8_t             *out);
size_t cinventory__purchase_init__response__pack_to_buffer
                     (const CInventoryPurchaseInitResponse   *message,
                      ProtobufCBuffer     *buffer);
CInventoryPurchaseInitResponse *
       cinventory__purchase_init__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__purchase_init__response__free_unpacked
                     (CInventoryPurchaseInitResponse *message,
                      ProtobufCAllocator *allocator);
/* CInventoryPurchaseFinalizeRequest methods */
void   cinventory__purchase_finalize__request__init
                     (CInventoryPurchaseFinalizeRequest         *message);
size_t cinventory__purchase_finalize__request__get_packed_size
                     (const CInventoryPurchaseFinalizeRequest   *message);
size_t cinventory__purchase_finalize__request__pack
                     (const CInventoryPurchaseFinalizeRequest   *message,
                      uint8_t             *out);
size_t cinventory__purchase_finalize__request__pack_to_buffer
                     (const CInventoryPurchaseFinalizeRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryPurchaseFinalizeRequest *
       cinventory__purchase_finalize__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__purchase_finalize__request__free_unpacked
                     (CInventoryPurchaseFinalizeRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryInspectItemRequest methods */
void   cinventory__inspect_item__request__init
                     (CInventoryInspectItemRequest         *message);
size_t cinventory__inspect_item__request__get_packed_size
                     (const CInventoryInspectItemRequest   *message);
size_t cinventory__inspect_item__request__pack
                     (const CInventoryInspectItemRequest   *message,
                      uint8_t             *out);
size_t cinventory__inspect_item__request__pack_to_buffer
                     (const CInventoryInspectItemRequest   *message,
                      ProtobufCBuffer     *buffer);
CInventoryInspectItemRequest *
       cinventory__inspect_item__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory__inspect_item__request__free_unpacked
                     (CInventoryInspectItemRequest *message,
                      ProtobufCAllocator *allocator);
/* CInventoryClientNewItemsNotification methods */
void   cinventory_client__new_items__notification__init
                     (CInventoryClientNewItemsNotification         *message);
size_t cinventory_client__new_items__notification__get_packed_size
                     (const CInventoryClientNewItemsNotification   *message);
size_t cinventory_client__new_items__notification__pack
                     (const CInventoryClientNewItemsNotification   *message,
                      uint8_t             *out);
size_t cinventory_client__new_items__notification__pack_to_buffer
                     (const CInventoryClientNewItemsNotification   *message,
                      ProtobufCBuffer     *buffer);
CInventoryClientNewItemsNotification *
       cinventory_client__new_items__notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cinventory_client__new_items__notification__free_unpacked
                     (CInventoryClientNewItemsNotification *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CInventoryGetInventoryRequest_Closure)
                 (const CInventoryGetInventoryRequest *message,
                  void *closure_data);
typedef void (*CInventoryResponse_Closure)
                 (const CInventoryResponse *message,
                  void *closure_data);
typedef void (*CInventoryExchangeItemRequest_Closure)
                 (const CInventoryExchangeItemRequest *message,
                  void *closure_data);
typedef void (*CInventoryGetEligiblePromoItemDefIDsRequest_Closure)
                 (const CInventoryGetEligiblePromoItemDefIDsRequest *message,
                  void *closure_data);
typedef void (*CInventoryGetEligiblePromoItemDefIDsResponse_Closure)
                 (const CInventoryGetEligiblePromoItemDefIDsResponse *message,
                  void *closure_data);
typedef void (*CInventoryAddItemRequest_Closure)
                 (const CInventoryAddItemRequest *message,
                  void *closure_data);
typedef void (*CInventoryModifyItemsRequest__ItemPropertyUpdate_Closure)
                 (const CInventoryModifyItemsRequest__ItemPropertyUpdate *message,
                  void *closure_data);
typedef void (*CInventoryModifyItemsRequest_Closure)
                 (const CInventoryModifyItemsRequest *message,
                  void *closure_data);
typedef void (*CInventoryConsumePlaytimeRequest_Closure)
                 (const CInventoryConsumePlaytimeRequest *message,
                  void *closure_data);
typedef void (*CInventoryConsumeItemRequest_Closure)
                 (const CInventoryConsumeItemRequest *message,
                  void *closure_data);
typedef void (*CInventoryDevSetNextDropRequest_Closure)
                 (const CInventoryDevSetNextDropRequest *message,
                  void *closure_data);
typedef void (*CInventorySplitItemStackRequest_Closure)
                 (const CInventorySplitItemStackRequest *message,
                  void *closure_data);
typedef void (*CInventoryCombineItemStacksRequest_Closure)
                 (const CInventoryCombineItemStacksRequest *message,
                  void *closure_data);
typedef void (*CInventoryGetItemDefMetaRequest_Closure)
                 (const CInventoryGetItemDefMetaRequest *message,
                  void *closure_data);
typedef void (*CInventoryGetItemDefMetaResponse_Closure)
                 (const CInventoryGetItemDefMetaResponse *message,
                  void *closure_data);
typedef void (*CInventoryGetUserPurchaseInfoRequest_Closure)
                 (const CInventoryGetUserPurchaseInfoRequest *message,
                  void *closure_data);
typedef void (*CInventoryGetUserPurchaseInfoResponse_Closure)
                 (const CInventoryGetUserPurchaseInfoResponse *message,
                  void *closure_data);
typedef void (*CInventoryPurchaseInitRequest__LineItem_Closure)
                 (const CInventoryPurchaseInitRequest__LineItem *message,
                  void *closure_data);
typedef void (*CInventoryPurchaseInitRequest_Closure)
                 (const CInventoryPurchaseInitRequest *message,
                  void *closure_data);
typedef void (*CInventoryPurchaseInitResponse_Closure)
                 (const CInventoryPurchaseInitResponse *message,
                  void *closure_data);
typedef void (*CInventoryPurchaseFinalizeRequest_Closure)
                 (const CInventoryPurchaseFinalizeRequest *message,
                  void *closure_data);
typedef void (*CInventoryInspectItemRequest_Closure)
                 (const CInventoryInspectItemRequest *message,
                  void *closure_data);
typedef void (*CInventoryClientNewItemsNotification_Closure)
                 (const CInventoryClientNewItemsNotification *message,
                  void *closure_data);

/* --- services --- */

typedef struct Inventory_Service Inventory_Service;
struct Inventory_Service
{
  ProtobufCService base;
  void (*get_inventory)(Inventory_Service *service,
                        const CInventoryGetInventoryRequest *input,
                        CInventoryResponse_Closure closure,
                        void *closure_data);
  void (*exchange_item)(Inventory_Service *service,
                        const CInventoryExchangeItemRequest *input,
                        CInventoryResponse_Closure closure,
                        void *closure_data);
  void (*get_eligible_promo_item_def_ids)(Inventory_Service *service,
                                          const CInventoryGetEligiblePromoItemDefIDsRequest *input,
                                          CInventoryGetEligiblePromoItemDefIDsResponse_Closure closure,
                                          void *closure_data);
  void (*add_promo_item)(Inventory_Service *service,
                         const CInventoryAddItemRequest *input,
                         CInventoryResponse_Closure closure,
                         void *closure_data);
  void (*safe_modify_items)(Inventory_Service *service,
                            const CInventoryModifyItemsRequest *input,
                            CInventoryResponse_Closure closure,
                            void *closure_data);
  void (*consume_playtime)(Inventory_Service *service,
                           const CInventoryConsumePlaytimeRequest *input,
                           CInventoryResponse_Closure closure,
                           void *closure_data);
  void (*consume_item)(Inventory_Service *service,
                       const CInventoryConsumeItemRequest *input,
                       CInventoryResponse_Closure closure,
                       void *closure_data);
  void (*dev_generate_item)(Inventory_Service *service,
                            const CInventoryAddItemRequest *input,
                            CInventoryResponse_Closure closure,
                            void *closure_data);
  void (*dev_set_next_drop)(Inventory_Service *service,
                            const CInventoryDevSetNextDropRequest *input,
                            CInventoryResponse_Closure closure,
                            void *closure_data);
  void (*split_item_stack)(Inventory_Service *service,
                           const CInventorySplitItemStackRequest *input,
                           CInventoryResponse_Closure closure,
                           void *closure_data);
  void (*combine_item_stacks)(Inventory_Service *service,
                              const CInventoryCombineItemStacksRequest *input,
                              CInventoryResponse_Closure closure,
                              void *closure_data);
  void (*get_item_def_meta)(Inventory_Service *service,
                            const CInventoryGetItemDefMetaRequest *input,
                            CInventoryGetItemDefMetaResponse_Closure closure,
                            void *closure_data);
  void (*get_user_purchase_info)(Inventory_Service *service,
                                 const CInventoryGetUserPurchaseInfoRequest *input,
                                 CInventoryGetUserPurchaseInfoResponse_Closure closure,
                                 void *closure_data);
  void (*purchase_init)(Inventory_Service *service,
                        const CInventoryPurchaseInitRequest *input,
                        CInventoryPurchaseInitResponse_Closure closure,
                        void *closure_data);
  void (*purchase_finalize)(Inventory_Service *service,
                            const CInventoryPurchaseFinalizeRequest *input,
                            CInventoryResponse_Closure closure,
                            void *closure_data);
  void (*inspect_item)(Inventory_Service *service,
                       const CInventoryInspectItemRequest *input,
                       CInventoryResponse_Closure closure,
                       void *closure_data);
};
typedef void (*Inventory_ServiceDestroy)(Inventory_Service *);
void inventory__init (Inventory_Service *service,
                      Inventory_ServiceDestroy destroy);
#define INVENTORY__BASE_INIT \
    { &inventory__descriptor, protobuf_c_service_invoke_internal, NULL }
#define INVENTORY__INIT(function_prefix__) \
    { INVENTORY__BASE_INIT,\
      function_prefix__ ## get_inventory,\
      function_prefix__ ## exchange_item,\
      function_prefix__ ## get_eligible_promo_item_def_ids,\
      function_prefix__ ## add_promo_item,\
      function_prefix__ ## safe_modify_items,\
      function_prefix__ ## consume_playtime,\
      function_prefix__ ## consume_item,\
      function_prefix__ ## dev_generate_item,\
      function_prefix__ ## dev_set_next_drop,\
      function_prefix__ ## split_item_stack,\
      function_prefix__ ## combine_item_stacks,\
      function_prefix__ ## get_item_def_meta,\
      function_prefix__ ## get_user_purchase_info,\
      function_prefix__ ## purchase_init,\
      function_prefix__ ## purchase_finalize,\
      function_prefix__ ## inspect_item  }
void inventory__get_inventory(ProtobufCService *service,
                              const CInventoryGetInventoryRequest *input,
                              CInventoryResponse_Closure closure,
                              void *closure_data);
void inventory__exchange_item(ProtobufCService *service,
                              const CInventoryExchangeItemRequest *input,
                              CInventoryResponse_Closure closure,
                              void *closure_data);
void inventory__get_eligible_promo_item_def_ids(ProtobufCService *service,
                                                const CInventoryGetEligiblePromoItemDefIDsRequest *input,
                                                CInventoryGetEligiblePromoItemDefIDsResponse_Closure closure,
                                                void *closure_data);
void inventory__add_promo_item(ProtobufCService *service,
                               const CInventoryAddItemRequest *input,
                               CInventoryResponse_Closure closure,
                               void *closure_data);
void inventory__safe_modify_items(ProtobufCService *service,
                                  const CInventoryModifyItemsRequest *input,
                                  CInventoryResponse_Closure closure,
                                  void *closure_data);
void inventory__consume_playtime(ProtobufCService *service,
                                 const CInventoryConsumePlaytimeRequest *input,
                                 CInventoryResponse_Closure closure,
                                 void *closure_data);
void inventory__consume_item(ProtobufCService *service,
                             const CInventoryConsumeItemRequest *input,
                             CInventoryResponse_Closure closure,
                             void *closure_data);
void inventory__dev_generate_item(ProtobufCService *service,
                                  const CInventoryAddItemRequest *input,
                                  CInventoryResponse_Closure closure,
                                  void *closure_data);
void inventory__dev_set_next_drop(ProtobufCService *service,
                                  const CInventoryDevSetNextDropRequest *input,
                                  CInventoryResponse_Closure closure,
                                  void *closure_data);
void inventory__split_item_stack(ProtobufCService *service,
                                 const CInventorySplitItemStackRequest *input,
                                 CInventoryResponse_Closure closure,
                                 void *closure_data);
void inventory__combine_item_stacks(ProtobufCService *service,
                                    const CInventoryCombineItemStacksRequest *input,
                                    CInventoryResponse_Closure closure,
                                    void *closure_data);
void inventory__get_item_def_meta(ProtobufCService *service,
                                  const CInventoryGetItemDefMetaRequest *input,
                                  CInventoryGetItemDefMetaResponse_Closure closure,
                                  void *closure_data);
void inventory__get_user_purchase_info(ProtobufCService *service,
                                       const CInventoryGetUserPurchaseInfoRequest *input,
                                       CInventoryGetUserPurchaseInfoResponse_Closure closure,
                                       void *closure_data);
void inventory__purchase_init(ProtobufCService *service,
                              const CInventoryPurchaseInitRequest *input,
                              CInventoryPurchaseInitResponse_Closure closure,
                              void *closure_data);
void inventory__purchase_finalize(ProtobufCService *service,
                                  const CInventoryPurchaseFinalizeRequest *input,
                                  CInventoryResponse_Closure closure,
                                  void *closure_data);
void inventory__inspect_item(ProtobufCService *service,
                             const CInventoryInspectItemRequest *input,
                             CInventoryResponse_Closure closure,
                             void *closure_data);
typedef struct InventoryClient_Service InventoryClient_Service;
struct InventoryClient_Service
{
  ProtobufCService base;
  void (*notify_new_items)(InventoryClient_Service *service,
                           const CInventoryClientNewItemsNotification *input,
                           NoResponse_Closure closure,
                           void *closure_data);
};
typedef void (*InventoryClient_ServiceDestroy)(InventoryClient_Service *);
void inventory_client__init (InventoryClient_Service *service,
                             InventoryClient_ServiceDestroy destroy);
#define INVENTORY_CLIENT__BASE_INIT \
    { &inventory_client__descriptor, protobuf_c_service_invoke_internal, NULL }
#define INVENTORY_CLIENT__INIT(function_prefix__) \
    { INVENTORY_CLIENT__BASE_INIT,\
      function_prefix__ ## notify_new_items  }
void inventory_client__notify_new_items(ProtobufCService *service,
                                        const CInventoryClientNewItemsNotification *input,
                                        NoResponse_Closure closure,
                                        void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cinventory__get_inventory__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__response__descriptor;
extern const ProtobufCMessageDescriptor cinventory__exchange_item__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__get_eligible_promo_item_def_ids__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__get_eligible_promo_item_def_ids__response__descriptor;
extern const ProtobufCMessageDescriptor cinventory__add_item__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__modify_items__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__modify_items__request__item_property_update__descriptor;
extern const ProtobufCMessageDescriptor cinventory__consume_playtime__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__consume_item__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__dev_set_next_drop__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__split_item_stack__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__combine_item_stacks__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__get_item_def_meta__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__get_item_def_meta__response__descriptor;
extern const ProtobufCMessageDescriptor cinventory__get_user_purchase_info__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__get_user_purchase_info__response__descriptor;
extern const ProtobufCMessageDescriptor cinventory__purchase_init__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__purchase_init__request__line_item__descriptor;
extern const ProtobufCMessageDescriptor cinventory__purchase_init__response__descriptor;
extern const ProtobufCMessageDescriptor cinventory__purchase_finalize__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory__inspect_item__request__descriptor;
extern const ProtobufCMessageDescriptor cinventory_client__new_items__notification__descriptor;
extern const ProtobufCServiceDescriptor inventory__descriptor;
extern const ProtobufCServiceDescriptor inventory_client__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5finventory_2esteamclient_2eproto__INCLUDED */
