/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_remoteclient_service.steamclient.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "steammessages_remoteclient_service.steamclient.pb-c.h"
static const ProtobufCMethodDescriptor remote_client__method_descriptors[14] =
{
  { "GetPairingInfo", &cremote_client__get_pairing_info__request__descriptor, &cremote_client__get_pairing_info__response__descriptor },
  { "NotifyOnline", &cremote_client__online__notification__descriptor, &no_response__descriptor },
  { "GetRecentClients", &cremote_client__get_recent_clients__request__descriptor, &cremote_client__get_recent_clients__response__descriptor },
  { "MarkTaskComplete", &cremote_client__mark_task_complete__request__descriptor, &cremote_client__mark_task_complete__response__descriptor },
  { "NotifyReplyPacket", &cremote_client__reply_packet__notification__descriptor, &no_response__descriptor },
  { "AllocateRelayServer", &cremote_client__allocate_relay_server__request__descriptor, &cremote_client__allocate_relay_server__response__descriptor },
  { "AllocateSDR", &cremote_client__allocate_sdr__request__descriptor, &cremote_client__allocate_sdr__response__descriptor },
  { "SendSteamBroadcastPacket", &cremote_client__steam_broadcast__notification__descriptor, &no_response__descriptor },
  { "SendSteamToSteamPacket", &cremote_client__steam_to_steam__notification__descriptor, &no_response__descriptor },
  { "SendRemotePlaySessionStarted", &cremote_play__session_started__request__descriptor, &cremote_play__session_started__response__descriptor },
  { "SendRemotePlaySessionStopped", &cremote_play__session_stopped__notification__descriptor, &no_response__descriptor },
  { "SendRemotePlayTogetherPacket", &cremote_play_together__notification__descriptor, &no_response__descriptor },
  { "CreateRemotePlayTogetherInvitation", &cremote_client__create_remote_play_together_invitation__request__descriptor, &cremote_client__create_remote_play_together_invitation__response__descriptor },
  { "DeleteRemotePlayTogetherInvitation", &cremote_client__delete_remote_play_together_invitation__request__descriptor, &cremote_client__delete_remote_play_together_invitation__response__descriptor },
};
const unsigned remote_client__method_indices_by_name[] = {
  5,        /* AllocateRelayServer */
  6,        /* AllocateSDR */
  12,        /* CreateRemotePlayTogetherInvitation */
  13,        /* DeleteRemotePlayTogetherInvitation */
  0,        /* GetPairingInfo */
  2,        /* GetRecentClients */
  3,        /* MarkTaskComplete */
  1,        /* NotifyOnline */
  4,        /* NotifyReplyPacket */
  9,        /* SendRemotePlaySessionStarted */
  10,        /* SendRemotePlaySessionStopped */
  11,        /* SendRemotePlayTogetherPacket */
  7,        /* SendSteamBroadcastPacket */
  8         /* SendSteamToSteamPacket */
};
const ProtobufCServiceDescriptor remote_client__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "RemoteClient",
  "RemoteClient",
  "RemoteClient",
  "",
  14,
  remote_client__method_descriptors,
  remote_client__method_indices_by_name
};
void remote_client__get_pairing_info(ProtobufCService *service,
                                     const CRemoteClientGetPairingInfoRequest *input,
                                     CRemoteClientGetPairingInfoResponse_Closure closure,
                                     void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__notify_online(ProtobufCService *service,
                                  const CRemoteClientOnlineNotification *input,
                                  NoResponse_Closure closure,
                                  void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__get_recent_clients(ProtobufCService *service,
                                       const CRemoteClientGetRecentClientsRequest *input,
                                       CRemoteClientGetRecentClientsResponse_Closure closure,
                                       void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__mark_task_complete(ProtobufCService *service,
                                       const CRemoteClientMarkTaskCompleteRequest *input,
                                       CRemoteClientMarkTaskCompleteResponse_Closure closure,
                                       void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__notify_reply_packet(ProtobufCService *service,
                                        const CRemoteClientReplyPacketNotification *input,
                                        NoResponse_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__allocate_relay_server(ProtobufCService *service,
                                          const CRemoteClientAllocateRelayServerRequest *input,
                                          CRemoteClientAllocateRelayServerResponse_Closure closure,
                                          void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__allocate_sdr(ProtobufCService *service,
                                 const CRemoteClientAllocateSDRRequest *input,
                                 CRemoteClientAllocateSDRResponse_Closure closure,
                                 void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__send_steam_broadcast_packet(ProtobufCService *service,
                                                const CRemoteClientSteamBroadcastNotification *input,
                                                NoResponse_Closure closure,
                                                void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__send_steam_to_steam_packet(ProtobufCService *service,
                                               const CRemoteClientSteamToSteamNotification *input,
                                               NoResponse_Closure closure,
                                               void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 8, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__send_remote_play_session_started(ProtobufCService *service,
                                                     const CRemotePlaySessionStartedRequest *input,
                                                     CRemotePlaySessionStartedResponse_Closure closure,
                                                     void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 9, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__send_remote_play_session_stopped(ProtobufCService *service,
                                                     const CRemotePlaySessionStoppedNotification *input,
                                                     NoResponse_Closure closure,
                                                     void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 10, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__send_remote_play_together_packet(ProtobufCService *service,
                                                     const CRemotePlayTogetherNotification *input,
                                                     NoResponse_Closure closure,
                                                     void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 11, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__create_remote_play_together_invitation(ProtobufCService *service,
                                                           const CRemoteClientCreateRemotePlayTogetherInvitationRequest *input,
                                                           CRemoteClientCreateRemotePlayTogetherInvitationResponse_Closure closure,
                                                           void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 12, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__delete_remote_play_together_invitation(ProtobufCService *service,
                                                           const CRemoteClientDeleteRemotePlayTogetherInvitationRequest *input,
                                                           CRemoteClientDeleteRemotePlayTogetherInvitationResponse_Closure closure,
                                                           void *closure_data)
{
  assert(service->descriptor == &remote_client__descriptor);
  service->invoke(service, 13, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client__init (RemoteClient_Service *service,
                          RemoteClient_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &remote_client__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
static const ProtobufCMethodDescriptor remote_client_steam_client__method_descriptors[9] =
{
  { "NotifyRegisterStatusUpdate", &cremote_client__register_status_update__notification__descriptor, &no_response__descriptor },
  { "NotifyUnregisterStatusUpdate", &cremote_client__unregister_status_update__notification__descriptor, &no_response__descriptor },
  { "NotifyRemotePacket", &cremote_client__remote_packet__notification__descriptor, &no_response__descriptor },
  { "NotifyEnableSteamBroadcast", &cremote_client__enable_steam_broadcast__notification__descriptor, &no_response__descriptor },
  { "NotifyDisableSteamBroadcast", &cremote_client__disable_steam_broadcast__notification__descriptor, &no_response__descriptor },
  { "NotifySteamBroadcastPacket", &cremote_client__steam_broadcast__notification__descriptor, &no_response__descriptor },
  { "NotifySteamToSteamPacket", &cremote_client__steam_to_steam__notification__descriptor, &no_response__descriptor },
  { "NotifyRemotePlayTogetherPacket", &cremote_play_together__notification__descriptor, &no_response__descriptor },
  { "NotifyTaskList", &cremote_client__task_list__notification__descriptor, &no_response__descriptor },
};
const unsigned remote_client_steam_client__method_indices_by_name[] = {
  4,        /* NotifyDisableSteamBroadcast */
  3,        /* NotifyEnableSteamBroadcast */
  0,        /* NotifyRegisterStatusUpdate */
  2,        /* NotifyRemotePacket */
  7,        /* NotifyRemotePlayTogetherPacket */
  5,        /* NotifySteamBroadcastPacket */
  6,        /* NotifySteamToSteamPacket */
  8,        /* NotifyTaskList */
  1         /* NotifyUnregisterStatusUpdate */
};
const ProtobufCServiceDescriptor remote_client_steam_client__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "RemoteClientSteamClient",
  "RemoteClientSteamClient",
  "RemoteClientSteamClient",
  "",
  9,
  remote_client_steam_client__method_descriptors,
  remote_client_steam_client__method_indices_by_name
};
void remote_client_steam_client__notify_register_status_update(ProtobufCService *service,
                                                               const CRemoteClientRegisterStatusUpdateNotification *input,
                                                               NoResponse_Closure closure,
                                                               void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__notify_unregister_status_update(ProtobufCService *service,
                                                                 const CRemoteClientUnregisterStatusUpdateNotification *input,
                                                                 NoResponse_Closure closure,
                                                                 void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__notify_remote_packet(ProtobufCService *service,
                                                      const CRemoteClientRemotePacketNotification *input,
                                                      NoResponse_Closure closure,
                                                      void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__notify_enable_steam_broadcast(ProtobufCService *service,
                                                               const CRemoteClientEnableSteamBroadcastNotification *input,
                                                               NoResponse_Closure closure,
                                                               void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__notify_disable_steam_broadcast(ProtobufCService *service,
                                                                const CRemoteClientDisableSteamBroadcastNotification *input,
                                                                NoResponse_Closure closure,
                                                                void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__notify_steam_broadcast_packet(ProtobufCService *service,
                                                               const CRemoteClientSteamBroadcastNotification *input,
                                                               NoResponse_Closure closure,
                                                               void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__notify_steam_to_steam_packet(ProtobufCService *service,
                                                              const CRemoteClientSteamToSteamNotification *input,
                                                              NoResponse_Closure closure,
                                                              void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__notify_remote_play_together_packet(ProtobufCService *service,
                                                                    const CRemotePlayTogetherNotification *input,
                                                                    NoResponse_Closure closure,
                                                                    void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__notify_task_list(ProtobufCService *service,
                                                  const CRemoteClientTaskListNotification *input,
                                                  NoResponse_Closure closure,
                                                  void *closure_data)
{
  assert(service->descriptor == &remote_client_steam_client__descriptor);
  service->invoke(service, 8, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void remote_client_steam_client__init (RemoteClientSteamClient_Service *service,
                                       RemoteClientSteamClient_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &remote_client_steam_client__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
