/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_twofactor.steamclient.proto */

#ifndef PROTOBUF_C_steammessages_5ftwofactor_2esteamclient_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5ftwofactor_2esteamclient_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "steammessages_unified_base.steamclient.pb-c.h"

typedef struct CTwoFactorTimeRequest CTwoFactorTimeRequest;
typedef struct CTwoFactorTimeResponse CTwoFactorTimeResponse;
typedef struct CTwoFactorStatusRequest CTwoFactorStatusRequest;
typedef struct CTwoFactorUsageEvent CTwoFactorUsageEvent;
typedef struct CTwoFactorStatusResponse CTwoFactorStatusResponse;
typedef struct CTwoFactorAddAuthenticatorRequest CTwoFactorAddAuthenticatorRequest;
typedef struct CTwoFactorAddAuthenticatorResponse CTwoFactorAddAuthenticatorResponse;
typedef struct CTwoFactorFinalizeAddAuthenticatorRequest CTwoFactorFinalizeAddAuthenticatorRequest;
typedef struct CTwoFactorFinalizeAddAuthenticatorResponse CTwoFactorFinalizeAddAuthenticatorResponse;
typedef struct CTwoFactorUpdateTokenVersionRequest CTwoFactorUpdateTokenVersionRequest;
typedef struct CTwoFactorUpdateTokenVersionResponse CTwoFactorUpdateTokenVersionResponse;
typedef struct CTwoFactorRemoveAuthenticatorRequest CTwoFactorRemoveAuthenticatorRequest;
typedef struct CTwoFactorRemoveAuthenticatorResponse CTwoFactorRemoveAuthenticatorResponse;
typedef struct CTwoFactorRemoveAuthenticatorViaChallengeStartRequest CTwoFactorRemoveAuthenticatorViaChallengeStartRequest;
typedef struct CTwoFactorRemoveAuthenticatorViaChallengeStartResponse CTwoFactorRemoveAuthenticatorViaChallengeStartResponse;
typedef struct CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest;
typedef struct CRemoveAuthenticatorViaChallengeContinueReplacementToken CRemoveAuthenticatorViaChallengeContinueReplacementToken;
typedef struct CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse;


/* --- enums --- */

typedef enum _ETwoFactorStatusFieldFlag {
  ETWO_FACTOR_STATUS_FIELD_FLAG__k_ETwoFactorStatusFieldFlag_None = 0,
  ETWO_FACTOR_STATUS_FIELD_FLAG__k_ETwoFactorStatusFieldFlag_LastUsage = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ETWO_FACTOR_STATUS_FIELD_FLAG)
} ETwoFactorStatusFieldFlag;
typedef enum _ETwoFactorUsageType {
  ETWO_FACTOR_USAGE_TYPE__k_ETwoFactorUsageType_Unknown = 0,
  ETWO_FACTOR_USAGE_TYPE__k_ETwoFactorUsageType_None = 1,
  ETWO_FACTOR_USAGE_TYPE__k_ETwoFactorUsageType_MobileConfirmation = 2,
  ETWO_FACTOR_USAGE_TYPE__k_ETwoFactorUsageType_Login = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ETWO_FACTOR_USAGE_TYPE)
} ETwoFactorUsageType;

/* --- messages --- */

struct  CTwoFactorTimeRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_sender_time;
  uint64_t sender_time;
};
#define CTWO_FACTOR__TIME__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__time__request__descriptor) \
, 0, 0 }


struct  CTwoFactorTimeResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_server_time;
  uint64_t server_time;
  protobuf_c_boolean has_skew_tolerance_seconds;
  uint64_t skew_tolerance_seconds;
  protobuf_c_boolean has_large_time_jink;
  uint64_t large_time_jink;
  protobuf_c_boolean has_probe_frequency_seconds;
  uint32_t probe_frequency_seconds;
  protobuf_c_boolean has_adjusted_time_probe_frequency_seconds;
  uint32_t adjusted_time_probe_frequency_seconds;
  protobuf_c_boolean has_hint_probe_frequency_seconds;
  uint32_t hint_probe_frequency_seconds;
  protobuf_c_boolean has_sync_timeout;
  uint32_t sync_timeout;
  protobuf_c_boolean has_try_again_seconds;
  uint32_t try_again_seconds;
  protobuf_c_boolean has_max_attempts;
  uint32_t max_attempts;
};
#define CTWO_FACTOR__TIME__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__time__response__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CTwoFactorStatusRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  protobuf_c_boolean has_include;
  ETwoFactorStatusFieldFlag include;
};
#define CTWO_FACTOR__STATUS__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__status__request__descriptor) \
, 0, 0, 0, ETWO_FACTOR_STATUS_FIELD_FLAG__k_ETwoFactorStatusFieldFlag_None }


struct  CTwoFactorUsageEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_time;
  uint32_t time;
  protobuf_c_boolean has_usage_type;
  ETwoFactorUsageType usage_type;
  protobuf_c_boolean has_confirmation_type;
  int32_t confirmation_type;
  protobuf_c_boolean has_confirmation_action;
  int32_t confirmation_action;
};
#define CTWO_FACTOR__USAGE_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__usage_event__descriptor) \
, 0, 0, 0, ETWO_FACTOR_USAGE_TYPE__k_ETwoFactorUsageType_Unknown, 0, 0, 0, 0 }


struct  CTwoFactorStatusResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_state;
  uint32_t state;
  protobuf_c_boolean has_inactivation_reason;
  uint32_t inactivation_reason;
  protobuf_c_boolean has_authenticator_type;
  uint32_t authenticator_type;
  protobuf_c_boolean has_authenticator_allowed;
  protobuf_c_boolean authenticator_allowed;
  protobuf_c_boolean has_steamguard_scheme;
  uint32_t steamguard_scheme;
  char *token_gid;
  protobuf_c_boolean has_email_validated;
  protobuf_c_boolean email_validated;
  char *device_identifier;
  protobuf_c_boolean has_time_created;
  uint32_t time_created;
  protobuf_c_boolean has_revocation_attempts_remaining;
  uint32_t revocation_attempts_remaining;
  char *classified_agent;
  protobuf_c_boolean has_allow_external_authenticator;
  protobuf_c_boolean allow_external_authenticator;
  protobuf_c_boolean has_time_transferred;
  uint32_t time_transferred;
  protobuf_c_boolean has_version;
  uint32_t version;
  protobuf_c_boolean has_last_seen_auth_token_id;
  uint64_t last_seen_auth_token_id;
  size_t n_usages;
  CTwoFactorUsageEvent **usages;
};
#define CTWO_FACTOR__STATUS__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__status__response__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL }


struct  CTwoFactorAddAuthenticatorRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  protobuf_c_boolean has_authenticator_time;
  uint64_t authenticator_time;
  protobuf_c_boolean has_serial_number;
  uint64_t serial_number;
  protobuf_c_boolean has_authenticator_type;
  uint32_t authenticator_type;
  char *device_identifier;
  size_t n_http_headers;
  char **http_headers;
  protobuf_c_boolean has_version;
  uint32_t version;
};
#define CTWO_FACTOR__ADD_AUTHENTICATOR__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__add_authenticator__request__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0,NULL, 0, 1u }


struct  CTwoFactorAddAuthenticatorResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_shared_secret;
  ProtobufCBinaryData shared_secret;
  protobuf_c_boolean has_serial_number;
  uint64_t serial_number;
  char *revocation_code;
  char *uri;
  protobuf_c_boolean has_server_time;
  uint64_t server_time;
  char *account_name;
  char *token_gid;
  protobuf_c_boolean has_identity_secret;
  ProtobufCBinaryData identity_secret;
  protobuf_c_boolean has_secret_1;
  ProtobufCBinaryData secret_1;
  protobuf_c_boolean has_status;
  int32_t status;
  char *phone_number_hint;
  protobuf_c_boolean has_confirm_type;
  int32_t confirm_type;
};
#define CTWO_FACTOR__ADD_AUTHENTICATOR__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__add_authenticator__response__descriptor) \
, 0, {0,NULL}, 0, 0, NULL, NULL, 0, 0, NULL, NULL, 0, {0,NULL}, 0, {0,NULL}, 0, 0, NULL, 0, 0 }


struct  CTwoFactorFinalizeAddAuthenticatorRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  char *authenticator_code;
  protobuf_c_boolean has_authenticator_time;
  uint64_t authenticator_time;
  char *activation_code;
  size_t n_http_headers;
  char **http_headers;
  protobuf_c_boolean has_validate_sms_code;
  protobuf_c_boolean validate_sms_code;
};
#define CTWO_FACTOR__FINALIZE_ADD_AUTHENTICATOR__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__finalize_add_authenticator__request__descriptor) \
, 0, 0, NULL, 0, 0, NULL, 0,NULL, 0, 0 }


struct  CTwoFactorFinalizeAddAuthenticatorResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_success;
  protobuf_c_boolean success;
  protobuf_c_boolean has_server_time;
  uint64_t server_time;
  protobuf_c_boolean has_status;
  int32_t status;
};
#define CTWO_FACTOR__FINALIZE_ADD_AUTHENTICATOR__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__finalize_add_authenticator__response__descriptor) \
, 0, 0, 0, 0, 0, 0 }


struct  CTwoFactorUpdateTokenVersionRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  protobuf_c_boolean has_version;
  uint32_t version;
  protobuf_c_boolean has_signature;
  ProtobufCBinaryData signature;
};
#define CTWO_FACTOR__UPDATE_TOKEN_VERSION__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__update_token_version__request__descriptor) \
, 0, 0, 0, 0, 0, {0,NULL} }


struct  CTwoFactorUpdateTokenVersionResponse
{
  ProtobufCMessage base;
};
#define CTWO_FACTOR__UPDATE_TOKEN_VERSION__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__update_token_version__response__descriptor) \
 }


struct  CTwoFactorRemoveAuthenticatorRequest
{
  ProtobufCMessage base;
  char *revocation_code;
  protobuf_c_boolean has_revocation_reason;
  uint32_t revocation_reason;
  protobuf_c_boolean has_steamguard_scheme;
  uint32_t steamguard_scheme;
  protobuf_c_boolean has_remove_all_steamguard_cookies;
  protobuf_c_boolean remove_all_steamguard_cookies;
};
#define CTWO_FACTOR__REMOVE_AUTHENTICATOR__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__remove_authenticator__request__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0 }


struct  CTwoFactorRemoveAuthenticatorResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_success;
  protobuf_c_boolean success;
  protobuf_c_boolean has_server_time;
  uint64_t server_time;
  protobuf_c_boolean has_revocation_attempts_remaining;
  uint32_t revocation_attempts_remaining;
};
#define CTWO_FACTOR__REMOVE_AUTHENTICATOR__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__remove_authenticator__response__descriptor) \
, 0, 0, 0, 0, 0, 0 }


struct  CTwoFactorRemoveAuthenticatorViaChallengeStartRequest
{
  ProtobufCMessage base;
};
#define CTWO_FACTOR__REMOVE_AUTHENTICATOR_VIA_CHALLENGE_START__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__remove_authenticator_via_challenge_start__request__descriptor) \
 }


struct  CTwoFactorRemoveAuthenticatorViaChallengeStartResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_success;
  protobuf_c_boolean success;
};
#define CTWO_FACTOR__REMOVE_AUTHENTICATOR_VIA_CHALLENGE_START__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__remove_authenticator_via_challenge_start__response__descriptor) \
, 0, 0 }


struct  CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest
{
  ProtobufCMessage base;
  char *sms_code;
  protobuf_c_boolean has_generate_new_token;
  protobuf_c_boolean generate_new_token;
  protobuf_c_boolean has_version;
  uint32_t version;
};
#define CTWO_FACTOR__REMOVE_AUTHENTICATOR_VIA_CHALLENGE_CONTINUE__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__remove_authenticator_via_challenge_continue__request__descriptor) \
, NULL, 0, 0, 0, 1u }


struct  CRemoveAuthenticatorViaChallengeContinueReplacementToken
{
  ProtobufCMessage base;
  protobuf_c_boolean has_shared_secret;
  ProtobufCBinaryData shared_secret;
  protobuf_c_boolean has_serial_number;
  uint64_t serial_number;
  char *revocation_code;
  char *uri;
  protobuf_c_boolean has_server_time;
  uint64_t server_time;
  char *account_name;
  char *token_gid;
  protobuf_c_boolean has_identity_secret;
  ProtobufCBinaryData identity_secret;
  protobuf_c_boolean has_secret_1;
  ProtobufCBinaryData secret_1;
  protobuf_c_boolean has_status;
  int32_t status;
  protobuf_c_boolean has_steamguard_scheme;
  uint32_t steamguard_scheme;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
};
#define CREMOVE_AUTHENTICATOR_VIA_CHALLENGE_CONTINUE__REPLACEMENT__TOKEN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cremove_authenticator_via_challenge_continue__replacement__token__descriptor) \
, 0, {0,NULL}, 0, 0, NULL, NULL, 0, 0, NULL, NULL, 0, {0,NULL}, 0, {0,NULL}, 0, 0, 0, 0, 0, 0 }


struct  CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_success;
  protobuf_c_boolean success;
  CRemoveAuthenticatorViaChallengeContinueReplacementToken *replacement_token;
};
#define CTWO_FACTOR__REMOVE_AUTHENTICATOR_VIA_CHALLENGE_CONTINUE__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctwo_factor__remove_authenticator_via_challenge_continue__response__descriptor) \
, 0, 0, NULL }


/* CTwoFactorTimeRequest methods */
void   ctwo_factor__time__request__init
                     (CTwoFactorTimeRequest         *message);
size_t ctwo_factor__time__request__get_packed_size
                     (const CTwoFactorTimeRequest   *message);
size_t ctwo_factor__time__request__pack
                     (const CTwoFactorTimeRequest   *message,
                      uint8_t             *out);
size_t ctwo_factor__time__request__pack_to_buffer
                     (const CTwoFactorTimeRequest   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorTimeRequest *
       ctwo_factor__time__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__time__request__free_unpacked
                     (CTwoFactorTimeRequest *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorTimeResponse methods */
void   ctwo_factor__time__response__init
                     (CTwoFactorTimeResponse         *message);
size_t ctwo_factor__time__response__get_packed_size
                     (const CTwoFactorTimeResponse   *message);
size_t ctwo_factor__time__response__pack
                     (const CTwoFactorTimeResponse   *message,
                      uint8_t             *out);
size_t ctwo_factor__time__response__pack_to_buffer
                     (const CTwoFactorTimeResponse   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorTimeResponse *
       ctwo_factor__time__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__time__response__free_unpacked
                     (CTwoFactorTimeResponse *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorStatusRequest methods */
void   ctwo_factor__status__request__init
                     (CTwoFactorStatusRequest         *message);
size_t ctwo_factor__status__request__get_packed_size
                     (const CTwoFactorStatusRequest   *message);
size_t ctwo_factor__status__request__pack
                     (const CTwoFactorStatusRequest   *message,
                      uint8_t             *out);
size_t ctwo_factor__status__request__pack_to_buffer
                     (const CTwoFactorStatusRequest   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorStatusRequest *
       ctwo_factor__status__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__status__request__free_unpacked
                     (CTwoFactorStatusRequest *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorUsageEvent methods */
void   ctwo_factor__usage_event__init
                     (CTwoFactorUsageEvent         *message);
size_t ctwo_factor__usage_event__get_packed_size
                     (const CTwoFactorUsageEvent   *message);
size_t ctwo_factor__usage_event__pack
                     (const CTwoFactorUsageEvent   *message,
                      uint8_t             *out);
size_t ctwo_factor__usage_event__pack_to_buffer
                     (const CTwoFactorUsageEvent   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorUsageEvent *
       ctwo_factor__usage_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__usage_event__free_unpacked
                     (CTwoFactorUsageEvent *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorStatusResponse methods */
void   ctwo_factor__status__response__init
                     (CTwoFactorStatusResponse         *message);
size_t ctwo_factor__status__response__get_packed_size
                     (const CTwoFactorStatusResponse   *message);
size_t ctwo_factor__status__response__pack
                     (const CTwoFactorStatusResponse   *message,
                      uint8_t             *out);
size_t ctwo_factor__status__response__pack_to_buffer
                     (const CTwoFactorStatusResponse   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorStatusResponse *
       ctwo_factor__status__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__status__response__free_unpacked
                     (CTwoFactorStatusResponse *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorAddAuthenticatorRequest methods */
void   ctwo_factor__add_authenticator__request__init
                     (CTwoFactorAddAuthenticatorRequest         *message);
size_t ctwo_factor__add_authenticator__request__get_packed_size
                     (const CTwoFactorAddAuthenticatorRequest   *message);
size_t ctwo_factor__add_authenticator__request__pack
                     (const CTwoFactorAddAuthenticatorRequest   *message,
                      uint8_t             *out);
size_t ctwo_factor__add_authenticator__request__pack_to_buffer
                     (const CTwoFactorAddAuthenticatorRequest   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorAddAuthenticatorRequest *
       ctwo_factor__add_authenticator__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__add_authenticator__request__free_unpacked
                     (CTwoFactorAddAuthenticatorRequest *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorAddAuthenticatorResponse methods */
void   ctwo_factor__add_authenticator__response__init
                     (CTwoFactorAddAuthenticatorResponse         *message);
size_t ctwo_factor__add_authenticator__response__get_packed_size
                     (const CTwoFactorAddAuthenticatorResponse   *message);
size_t ctwo_factor__add_authenticator__response__pack
                     (const CTwoFactorAddAuthenticatorResponse   *message,
                      uint8_t             *out);
size_t ctwo_factor__add_authenticator__response__pack_to_buffer
                     (const CTwoFactorAddAuthenticatorResponse   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorAddAuthenticatorResponse *
       ctwo_factor__add_authenticator__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__add_authenticator__response__free_unpacked
                     (CTwoFactorAddAuthenticatorResponse *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorFinalizeAddAuthenticatorRequest methods */
void   ctwo_factor__finalize_add_authenticator__request__init
                     (CTwoFactorFinalizeAddAuthenticatorRequest         *message);
size_t ctwo_factor__finalize_add_authenticator__request__get_packed_size
                     (const CTwoFactorFinalizeAddAuthenticatorRequest   *message);
size_t ctwo_factor__finalize_add_authenticator__request__pack
                     (const CTwoFactorFinalizeAddAuthenticatorRequest   *message,
                      uint8_t             *out);
size_t ctwo_factor__finalize_add_authenticator__request__pack_to_buffer
                     (const CTwoFactorFinalizeAddAuthenticatorRequest   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorFinalizeAddAuthenticatorRequest *
       ctwo_factor__finalize_add_authenticator__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__finalize_add_authenticator__request__free_unpacked
                     (CTwoFactorFinalizeAddAuthenticatorRequest *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorFinalizeAddAuthenticatorResponse methods */
void   ctwo_factor__finalize_add_authenticator__response__init
                     (CTwoFactorFinalizeAddAuthenticatorResponse         *message);
size_t ctwo_factor__finalize_add_authenticator__response__get_packed_size
                     (const CTwoFactorFinalizeAddAuthenticatorResponse   *message);
size_t ctwo_factor__finalize_add_authenticator__response__pack
                     (const CTwoFactorFinalizeAddAuthenticatorResponse   *message,
                      uint8_t             *out);
size_t ctwo_factor__finalize_add_authenticator__response__pack_to_buffer
                     (const CTwoFactorFinalizeAddAuthenticatorResponse   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorFinalizeAddAuthenticatorResponse *
       ctwo_factor__finalize_add_authenticator__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__finalize_add_authenticator__response__free_unpacked
                     (CTwoFactorFinalizeAddAuthenticatorResponse *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorUpdateTokenVersionRequest methods */
void   ctwo_factor__update_token_version__request__init
                     (CTwoFactorUpdateTokenVersionRequest         *message);
size_t ctwo_factor__update_token_version__request__get_packed_size
                     (const CTwoFactorUpdateTokenVersionRequest   *message);
size_t ctwo_factor__update_token_version__request__pack
                     (const CTwoFactorUpdateTokenVersionRequest   *message,
                      uint8_t             *out);
size_t ctwo_factor__update_token_version__request__pack_to_buffer
                     (const CTwoFactorUpdateTokenVersionRequest   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorUpdateTokenVersionRequest *
       ctwo_factor__update_token_version__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__update_token_version__request__free_unpacked
                     (CTwoFactorUpdateTokenVersionRequest *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorUpdateTokenVersionResponse methods */
void   ctwo_factor__update_token_version__response__init
                     (CTwoFactorUpdateTokenVersionResponse         *message);
size_t ctwo_factor__update_token_version__response__get_packed_size
                     (const CTwoFactorUpdateTokenVersionResponse   *message);
size_t ctwo_factor__update_token_version__response__pack
                     (const CTwoFactorUpdateTokenVersionResponse   *message,
                      uint8_t             *out);
size_t ctwo_factor__update_token_version__response__pack_to_buffer
                     (const CTwoFactorUpdateTokenVersionResponse   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorUpdateTokenVersionResponse *
       ctwo_factor__update_token_version__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__update_token_version__response__free_unpacked
                     (CTwoFactorUpdateTokenVersionResponse *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorRemoveAuthenticatorRequest methods */
void   ctwo_factor__remove_authenticator__request__init
                     (CTwoFactorRemoveAuthenticatorRequest         *message);
size_t ctwo_factor__remove_authenticator__request__get_packed_size
                     (const CTwoFactorRemoveAuthenticatorRequest   *message);
size_t ctwo_factor__remove_authenticator__request__pack
                     (const CTwoFactorRemoveAuthenticatorRequest   *message,
                      uint8_t             *out);
size_t ctwo_factor__remove_authenticator__request__pack_to_buffer
                     (const CTwoFactorRemoveAuthenticatorRequest   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorRemoveAuthenticatorRequest *
       ctwo_factor__remove_authenticator__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__remove_authenticator__request__free_unpacked
                     (CTwoFactorRemoveAuthenticatorRequest *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorRemoveAuthenticatorResponse methods */
void   ctwo_factor__remove_authenticator__response__init
                     (CTwoFactorRemoveAuthenticatorResponse         *message);
size_t ctwo_factor__remove_authenticator__response__get_packed_size
                     (const CTwoFactorRemoveAuthenticatorResponse   *message);
size_t ctwo_factor__remove_authenticator__response__pack
                     (const CTwoFactorRemoveAuthenticatorResponse   *message,
                      uint8_t             *out);
size_t ctwo_factor__remove_authenticator__response__pack_to_buffer
                     (const CTwoFactorRemoveAuthenticatorResponse   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorRemoveAuthenticatorResponse *
       ctwo_factor__remove_authenticator__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__remove_authenticator__response__free_unpacked
                     (CTwoFactorRemoveAuthenticatorResponse *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorRemoveAuthenticatorViaChallengeStartRequest methods */
void   ctwo_factor__remove_authenticator_via_challenge_start__request__init
                     (CTwoFactorRemoveAuthenticatorViaChallengeStartRequest         *message);
size_t ctwo_factor__remove_authenticator_via_challenge_start__request__get_packed_size
                     (const CTwoFactorRemoveAuthenticatorViaChallengeStartRequest   *message);
size_t ctwo_factor__remove_authenticator_via_challenge_start__request__pack
                     (const CTwoFactorRemoveAuthenticatorViaChallengeStartRequest   *message,
                      uint8_t             *out);
size_t ctwo_factor__remove_authenticator_via_challenge_start__request__pack_to_buffer
                     (const CTwoFactorRemoveAuthenticatorViaChallengeStartRequest   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorRemoveAuthenticatorViaChallengeStartRequest *
       ctwo_factor__remove_authenticator_via_challenge_start__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__remove_authenticator_via_challenge_start__request__free_unpacked
                     (CTwoFactorRemoveAuthenticatorViaChallengeStartRequest *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorRemoveAuthenticatorViaChallengeStartResponse methods */
void   ctwo_factor__remove_authenticator_via_challenge_start__response__init
                     (CTwoFactorRemoveAuthenticatorViaChallengeStartResponse         *message);
size_t ctwo_factor__remove_authenticator_via_challenge_start__response__get_packed_size
                     (const CTwoFactorRemoveAuthenticatorViaChallengeStartResponse   *message);
size_t ctwo_factor__remove_authenticator_via_challenge_start__response__pack
                     (const CTwoFactorRemoveAuthenticatorViaChallengeStartResponse   *message,
                      uint8_t             *out);
size_t ctwo_factor__remove_authenticator_via_challenge_start__response__pack_to_buffer
                     (const CTwoFactorRemoveAuthenticatorViaChallengeStartResponse   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorRemoveAuthenticatorViaChallengeStartResponse *
       ctwo_factor__remove_authenticator_via_challenge_start__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__remove_authenticator_via_challenge_start__response__free_unpacked
                     (CTwoFactorRemoveAuthenticatorViaChallengeStartResponse *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest methods */
void   ctwo_factor__remove_authenticator_via_challenge_continue__request__init
                     (CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest         *message);
size_t ctwo_factor__remove_authenticator_via_challenge_continue__request__get_packed_size
                     (const CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest   *message);
size_t ctwo_factor__remove_authenticator_via_challenge_continue__request__pack
                     (const CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest   *message,
                      uint8_t             *out);
size_t ctwo_factor__remove_authenticator_via_challenge_continue__request__pack_to_buffer
                     (const CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest *
       ctwo_factor__remove_authenticator_via_challenge_continue__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__remove_authenticator_via_challenge_continue__request__free_unpacked
                     (CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest *message,
                      ProtobufCAllocator *allocator);
/* CRemoveAuthenticatorViaChallengeContinueReplacementToken methods */
void   cremove_authenticator_via_challenge_continue__replacement__token__init
                     (CRemoveAuthenticatorViaChallengeContinueReplacementToken         *message);
size_t cremove_authenticator_via_challenge_continue__replacement__token__get_packed_size
                     (const CRemoveAuthenticatorViaChallengeContinueReplacementToken   *message);
size_t cremove_authenticator_via_challenge_continue__replacement__token__pack
                     (const CRemoveAuthenticatorViaChallengeContinueReplacementToken   *message,
                      uint8_t             *out);
size_t cremove_authenticator_via_challenge_continue__replacement__token__pack_to_buffer
                     (const CRemoveAuthenticatorViaChallengeContinueReplacementToken   *message,
                      ProtobufCBuffer     *buffer);
CRemoveAuthenticatorViaChallengeContinueReplacementToken *
       cremove_authenticator_via_challenge_continue__replacement__token__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cremove_authenticator_via_challenge_continue__replacement__token__free_unpacked
                     (CRemoveAuthenticatorViaChallengeContinueReplacementToken *message,
                      ProtobufCAllocator *allocator);
/* CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse methods */
void   ctwo_factor__remove_authenticator_via_challenge_continue__response__init
                     (CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse         *message);
size_t ctwo_factor__remove_authenticator_via_challenge_continue__response__get_packed_size
                     (const CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse   *message);
size_t ctwo_factor__remove_authenticator_via_challenge_continue__response__pack
                     (const CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse   *message,
                      uint8_t             *out);
size_t ctwo_factor__remove_authenticator_via_challenge_continue__response__pack_to_buffer
                     (const CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse   *message,
                      ProtobufCBuffer     *buffer);
CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse *
       ctwo_factor__remove_authenticator_via_challenge_continue__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctwo_factor__remove_authenticator_via_challenge_continue__response__free_unpacked
                     (CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CTwoFactorTimeRequest_Closure)
                 (const CTwoFactorTimeRequest *message,
                  void *closure_data);
typedef void (*CTwoFactorTimeResponse_Closure)
                 (const CTwoFactorTimeResponse *message,
                  void *closure_data);
typedef void (*CTwoFactorStatusRequest_Closure)
                 (const CTwoFactorStatusRequest *message,
                  void *closure_data);
typedef void (*CTwoFactorUsageEvent_Closure)
                 (const CTwoFactorUsageEvent *message,
                  void *closure_data);
typedef void (*CTwoFactorStatusResponse_Closure)
                 (const CTwoFactorStatusResponse *message,
                  void *closure_data);
typedef void (*CTwoFactorAddAuthenticatorRequest_Closure)
                 (const CTwoFactorAddAuthenticatorRequest *message,
                  void *closure_data);
typedef void (*CTwoFactorAddAuthenticatorResponse_Closure)
                 (const CTwoFactorAddAuthenticatorResponse *message,
                  void *closure_data);
typedef void (*CTwoFactorFinalizeAddAuthenticatorRequest_Closure)
                 (const CTwoFactorFinalizeAddAuthenticatorRequest *message,
                  void *closure_data);
typedef void (*CTwoFactorFinalizeAddAuthenticatorResponse_Closure)
                 (const CTwoFactorFinalizeAddAuthenticatorResponse *message,
                  void *closure_data);
typedef void (*CTwoFactorUpdateTokenVersionRequest_Closure)
                 (const CTwoFactorUpdateTokenVersionRequest *message,
                  void *closure_data);
typedef void (*CTwoFactorUpdateTokenVersionResponse_Closure)
                 (const CTwoFactorUpdateTokenVersionResponse *message,
                  void *closure_data);
typedef void (*CTwoFactorRemoveAuthenticatorRequest_Closure)
                 (const CTwoFactorRemoveAuthenticatorRequest *message,
                  void *closure_data);
typedef void (*CTwoFactorRemoveAuthenticatorResponse_Closure)
                 (const CTwoFactorRemoveAuthenticatorResponse *message,
                  void *closure_data);
typedef void (*CTwoFactorRemoveAuthenticatorViaChallengeStartRequest_Closure)
                 (const CTwoFactorRemoveAuthenticatorViaChallengeStartRequest *message,
                  void *closure_data);
typedef void (*CTwoFactorRemoveAuthenticatorViaChallengeStartResponse_Closure)
                 (const CTwoFactorRemoveAuthenticatorViaChallengeStartResponse *message,
                  void *closure_data);
typedef void (*CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest_Closure)
                 (const CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest *message,
                  void *closure_data);
typedef void (*CRemoveAuthenticatorViaChallengeContinueReplacementToken_Closure)
                 (const CRemoveAuthenticatorViaChallengeContinueReplacementToken *message,
                  void *closure_data);
typedef void (*CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse_Closure)
                 (const CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct TwoFactor_Service TwoFactor_Service;
struct TwoFactor_Service
{
  ProtobufCService base;
  void (*query_time)(TwoFactor_Service *service,
                     const CTwoFactorTimeRequest *input,
                     CTwoFactorTimeResponse_Closure closure,
                     void *closure_data);
  void (*query_status)(TwoFactor_Service *service,
                       const CTwoFactorStatusRequest *input,
                       CTwoFactorStatusResponse_Closure closure,
                       void *closure_data);
  void (*add_authenticator)(TwoFactor_Service *service,
                            const CTwoFactorAddAuthenticatorRequest *input,
                            CTwoFactorAddAuthenticatorResponse_Closure closure,
                            void *closure_data);
  void (*finalize_add_authenticator)(TwoFactor_Service *service,
                                     const CTwoFactorFinalizeAddAuthenticatorRequest *input,
                                     CTwoFactorFinalizeAddAuthenticatorResponse_Closure closure,
                                     void *closure_data);
  void (*update_token_version)(TwoFactor_Service *service,
                               const CTwoFactorUpdateTokenVersionRequest *input,
                               CTwoFactorUpdateTokenVersionResponse_Closure closure,
                               void *closure_data);
  void (*remove_authenticator)(TwoFactor_Service *service,
                               const CTwoFactorRemoveAuthenticatorRequest *input,
                               CTwoFactorRemoveAuthenticatorResponse_Closure closure,
                               void *closure_data);
  void (*remove_authenticator_via_challenge_start)(TwoFactor_Service *service,
                                                   const CTwoFactorRemoveAuthenticatorViaChallengeStartRequest *input,
                                                   CTwoFactorRemoveAuthenticatorViaChallengeStartResponse_Closure closure,
                                                   void *closure_data);
  void (*remove_authenticator_via_challenge_continue)(TwoFactor_Service *service,
                                                      const CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest *input,
                                                      CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse_Closure closure,
                                                      void *closure_data);
};
typedef void (*TwoFactor_ServiceDestroy)(TwoFactor_Service *);
void two_factor__init (TwoFactor_Service *service,
                       TwoFactor_ServiceDestroy destroy);
#define TWO_FACTOR__BASE_INIT \
    { &two_factor__descriptor, protobuf_c_service_invoke_internal, NULL }
#define TWO_FACTOR__INIT(function_prefix__) \
    { TWO_FACTOR__BASE_INIT,\
      function_prefix__ ## query_time,\
      function_prefix__ ## query_status,\
      function_prefix__ ## add_authenticator,\
      function_prefix__ ## finalize_add_authenticator,\
      function_prefix__ ## update_token_version,\
      function_prefix__ ## remove_authenticator,\
      function_prefix__ ## remove_authenticator_via_challenge_start,\
      function_prefix__ ## remove_authenticator_via_challenge_continue  }
void two_factor__query_time(ProtobufCService *service,
                            const CTwoFactorTimeRequest *input,
                            CTwoFactorTimeResponse_Closure closure,
                            void *closure_data);
void two_factor__query_status(ProtobufCService *service,
                              const CTwoFactorStatusRequest *input,
                              CTwoFactorStatusResponse_Closure closure,
                              void *closure_data);
void two_factor__add_authenticator(ProtobufCService *service,
                                   const CTwoFactorAddAuthenticatorRequest *input,
                                   CTwoFactorAddAuthenticatorResponse_Closure closure,
                                   void *closure_data);
void two_factor__finalize_add_authenticator(ProtobufCService *service,
                                            const CTwoFactorFinalizeAddAuthenticatorRequest *input,
                                            CTwoFactorFinalizeAddAuthenticatorResponse_Closure closure,
                                            void *closure_data);
void two_factor__update_token_version(ProtobufCService *service,
                                      const CTwoFactorUpdateTokenVersionRequest *input,
                                      CTwoFactorUpdateTokenVersionResponse_Closure closure,
                                      void *closure_data);
void two_factor__remove_authenticator(ProtobufCService *service,
                                      const CTwoFactorRemoveAuthenticatorRequest *input,
                                      CTwoFactorRemoveAuthenticatorResponse_Closure closure,
                                      void *closure_data);
void two_factor__remove_authenticator_via_challenge_start(ProtobufCService *service,
                                                          const CTwoFactorRemoveAuthenticatorViaChallengeStartRequest *input,
                                                          CTwoFactorRemoveAuthenticatorViaChallengeStartResponse_Closure closure,
                                                          void *closure_data);
void two_factor__remove_authenticator_via_challenge_continue(ProtobufCService *service,
                                                             const CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest *input,
                                                             CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse_Closure closure,
                                                             void *closure_data);

/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    etwo_factor_status_field_flag__descriptor;
extern const ProtobufCEnumDescriptor    etwo_factor_usage_type__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__time__request__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__time__response__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__status__request__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__usage_event__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__status__response__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__add_authenticator__request__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__add_authenticator__response__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__finalize_add_authenticator__request__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__finalize_add_authenticator__response__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__update_token_version__request__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__update_token_version__response__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__remove_authenticator__request__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__remove_authenticator__response__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__remove_authenticator_via_challenge_start__request__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__remove_authenticator_via_challenge_start__response__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__remove_authenticator_via_challenge_continue__request__descriptor;
extern const ProtobufCMessageDescriptor cremove_authenticator_via_challenge_continue__replacement__token__descriptor;
extern const ProtobufCMessageDescriptor ctwo_factor__remove_authenticator_via_challenge_continue__response__descriptor;
extern const ProtobufCServiceDescriptor two_factor__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5ftwofactor_2esteamclient_2eproto__INCLUDED */
