/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_vac.steamclient.proto */

#ifndef PROTOBUF_C_steammessages_5fvac_2esteamclient_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5fvac_2esteamclient_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "steammessages_unified_base.steamclient.pb-c.h"

typedef struct CFileVerificationSignatureCheckRequest CFileVerificationSignatureCheckRequest;
typedef struct CFileVerificationSignatureCheckResponse CFileVerificationSignatureCheckResponse;
typedef struct CFileVerificationSteamServiceCheckRequest CFileVerificationSteamServiceCheckRequest;
typedef struct CFileVerificationSteamServiceCheckResponse CFileVerificationSteamServiceCheckResponse;


/* --- enums --- */


/* --- messages --- */

struct  CFileVerificationSignatureCheckRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_steamid;
  uint64_t steamid;
  protobuf_c_boolean has_appid;
  uint32_t appid;
  protobuf_c_boolean has_file_size;
  uint64_t file_size;
  protobuf_c_boolean has_file_timestamp;
  uint32_t file_timestamp;
  protobuf_c_boolean has_file_timestamp2;
  uint32_t file_timestamp2;
  protobuf_c_boolean has_signature_result;
  uint32_t signature_result;
  char *filename;
  protobuf_c_boolean has_client_package_version;
  uint32_t client_package_version;
  protobuf_c_boolean has_sha1hash;
  ProtobufCBinaryData sha1hash;
};
#define CFILE_VERIFICATION__SIGNATURE_CHECK__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfile_verification__signature_check__request__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, {0,NULL} }


struct  CFileVerificationSignatureCheckResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_deny_operation;
  protobuf_c_boolean deny_operation;
};
#define CFILE_VERIFICATION__SIGNATURE_CHECK__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfile_verification__signature_check__response__descriptor) \
, 0, 0 }


struct  CFileVerificationSteamServiceCheckRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_service_status;
  uint32_t service_status;
  protobuf_c_boolean has_client_package_version;
  uint32_t client_package_version;
  protobuf_c_boolean has_launcher_type;
  uint32_t launcher_type;
  protobuf_c_boolean has_os_type;
  uint32_t os_type;
  protobuf_c_boolean has_service_repair;
  uint32_t service_repair;
};
#define CFILE_VERIFICATION__STEAM_SERVICE_CHECK__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfile_verification__steam_service_check__request__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CFileVerificationSteamServiceCheckResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_attempt_repair;
  protobuf_c_boolean attempt_repair;
};
#define CFILE_VERIFICATION__STEAM_SERVICE_CHECK__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfile_verification__steam_service_check__response__descriptor) \
, 0, 0 }


/* CFileVerificationSignatureCheckRequest methods */
void   cfile_verification__signature_check__request__init
                     (CFileVerificationSignatureCheckRequest         *message);
size_t cfile_verification__signature_check__request__get_packed_size
                     (const CFileVerificationSignatureCheckRequest   *message);
size_t cfile_verification__signature_check__request__pack
                     (const CFileVerificationSignatureCheckRequest   *message,
                      uint8_t             *out);
size_t cfile_verification__signature_check__request__pack_to_buffer
                     (const CFileVerificationSignatureCheckRequest   *message,
                      ProtobufCBuffer     *buffer);
CFileVerificationSignatureCheckRequest *
       cfile_verification__signature_check__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfile_verification__signature_check__request__free_unpacked
                     (CFileVerificationSignatureCheckRequest *message,
                      ProtobufCAllocator *allocator);
/* CFileVerificationSignatureCheckResponse methods */
void   cfile_verification__signature_check__response__init
                     (CFileVerificationSignatureCheckResponse         *message);
size_t cfile_verification__signature_check__response__get_packed_size
                     (const CFileVerificationSignatureCheckResponse   *message);
size_t cfile_verification__signature_check__response__pack
                     (const CFileVerificationSignatureCheckResponse   *message,
                      uint8_t             *out);
size_t cfile_verification__signature_check__response__pack_to_buffer
                     (const CFileVerificationSignatureCheckResponse   *message,
                      ProtobufCBuffer     *buffer);
CFileVerificationSignatureCheckResponse *
       cfile_verification__signature_check__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfile_verification__signature_check__response__free_unpacked
                     (CFileVerificationSignatureCheckResponse *message,
                      ProtobufCAllocator *allocator);
/* CFileVerificationSteamServiceCheckRequest methods */
void   cfile_verification__steam_service_check__request__init
                     (CFileVerificationSteamServiceCheckRequest         *message);
size_t cfile_verification__steam_service_check__request__get_packed_size
                     (const CFileVerificationSteamServiceCheckRequest   *message);
size_t cfile_verification__steam_service_check__request__pack
                     (const CFileVerificationSteamServiceCheckRequest   *message,
                      uint8_t             *out);
size_t cfile_verification__steam_service_check__request__pack_to_buffer
                     (const CFileVerificationSteamServiceCheckRequest   *message,
                      ProtobufCBuffer     *buffer);
CFileVerificationSteamServiceCheckRequest *
       cfile_verification__steam_service_check__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfile_verification__steam_service_check__request__free_unpacked
                     (CFileVerificationSteamServiceCheckRequest *message,
                      ProtobufCAllocator *allocator);
/* CFileVerificationSteamServiceCheckResponse methods */
void   cfile_verification__steam_service_check__response__init
                     (CFileVerificationSteamServiceCheckResponse         *message);
size_t cfile_verification__steam_service_check__response__get_packed_size
                     (const CFileVerificationSteamServiceCheckResponse   *message);
size_t cfile_verification__steam_service_check__response__pack
                     (const CFileVerificationSteamServiceCheckResponse   *message,
                      uint8_t             *out);
size_t cfile_verification__steam_service_check__response__pack_to_buffer
                     (const CFileVerificationSteamServiceCheckResponse   *message,
                      ProtobufCBuffer     *buffer);
CFileVerificationSteamServiceCheckResponse *
       cfile_verification__steam_service_check__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfile_verification__steam_service_check__response__free_unpacked
                     (CFileVerificationSteamServiceCheckResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CFileVerificationSignatureCheckRequest_Closure)
                 (const CFileVerificationSignatureCheckRequest *message,
                  void *closure_data);
typedef void (*CFileVerificationSignatureCheckResponse_Closure)
                 (const CFileVerificationSignatureCheckResponse *message,
                  void *closure_data);
typedef void (*CFileVerificationSteamServiceCheckRequest_Closure)
                 (const CFileVerificationSteamServiceCheckRequest *message,
                  void *closure_data);
typedef void (*CFileVerificationSteamServiceCheckResponse_Closure)
                 (const CFileVerificationSteamServiceCheckResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct FileVerification_Service FileVerification_Service;
struct FileVerification_Service
{
  ProtobufCService base;
  void (*signature_check)(FileVerification_Service *service,
                          const CFileVerificationSignatureCheckRequest *input,
                          CFileVerificationSignatureCheckResponse_Closure closure,
                          void *closure_data);
  void (*steam_service_check)(FileVerification_Service *service,
                              const CFileVerificationSteamServiceCheckRequest *input,
                              CFileVerificationSteamServiceCheckResponse_Closure closure,
                              void *closure_data);
};
typedef void (*FileVerification_ServiceDestroy)(FileVerification_Service *);
void file_verification__init (FileVerification_Service *service,
                              FileVerification_ServiceDestroy destroy);
#define FILE_VERIFICATION__BASE_INIT \
    { &file_verification__descriptor, protobuf_c_service_invoke_internal, NULL }
#define FILE_VERIFICATION__INIT(function_prefix__) \
    { FILE_VERIFICATION__BASE_INIT,\
      function_prefix__ ## signature_check,\
      function_prefix__ ## steam_service_check  }
void file_verification__signature_check(ProtobufCService *service,
                                        const CFileVerificationSignatureCheckRequest *input,
                                        CFileVerificationSignatureCheckResponse_Closure closure,
                                        void *closure_data);
void file_verification__steam_service_check(ProtobufCService *service,
                                            const CFileVerificationSteamServiceCheckRequest *input,
                                            CFileVerificationSteamServiceCheckResponse_Closure closure,
                                            void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cfile_verification__signature_check__request__descriptor;
extern const ProtobufCMessageDescriptor cfile_verification__signature_check__response__descriptor;
extern const ProtobufCMessageDescriptor cfile_verification__steam_service_check__request__descriptor;
extern const ProtobufCMessageDescriptor cfile_verification__steam_service_check__response__descriptor;
extern const ProtobufCServiceDescriptor file_verification__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5fvac_2esteamclient_2eproto__INCLUDED */
