/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_workshop.steamclient.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "steammessages_workshop.steamclient.pb-c.h"
void   cworkshop__get_eulastatus__request__init
                     (CWorkshopGetEULAStatusRequest         *message)
{
  static const CWorkshopGetEULAStatusRequest init_value = CWORKSHOP__GET_EULASTATUS__REQUEST__INIT;
  *message = init_value;
}
size_t cworkshop__get_eulastatus__request__get_packed_size
                     (const CWorkshopGetEULAStatusRequest *message)
{
  assert(message->base.descriptor == &cworkshop__get_eulastatus__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cworkshop__get_eulastatus__request__pack
                     (const CWorkshopGetEULAStatusRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cworkshop__get_eulastatus__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cworkshop__get_eulastatus__request__pack_to_buffer
                     (const CWorkshopGetEULAStatusRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cworkshop__get_eulastatus__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CWorkshopGetEULAStatusRequest *
       cworkshop__get_eulastatus__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CWorkshopGetEULAStatusRequest *)
     protobuf_c_message_unpack (&cworkshop__get_eulastatus__request__descriptor,
                                allocator, len, data);
}
void   cworkshop__get_eulastatus__request__free_unpacked
                     (CWorkshopGetEULAStatusRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cworkshop__get_eulastatus__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cworkshop__get_eulastatus__response__init
                     (CWorkshopGetEULAStatusResponse         *message)
{
  static const CWorkshopGetEULAStatusResponse init_value = CWORKSHOP__GET_EULASTATUS__RESPONSE__INIT;
  *message = init_value;
}
size_t cworkshop__get_eulastatus__response__get_packed_size
                     (const CWorkshopGetEULAStatusResponse *message)
{
  assert(message->base.descriptor == &cworkshop__get_eulastatus__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cworkshop__get_eulastatus__response__pack
                     (const CWorkshopGetEULAStatusResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cworkshop__get_eulastatus__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cworkshop__get_eulastatus__response__pack_to_buffer
                     (const CWorkshopGetEULAStatusResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cworkshop__get_eulastatus__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CWorkshopGetEULAStatusResponse *
       cworkshop__get_eulastatus__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CWorkshopGetEULAStatusResponse *)
     protobuf_c_message_unpack (&cworkshop__get_eulastatus__response__descriptor,
                                allocator, len, data);
}
void   cworkshop__get_eulastatus__response__free_unpacked
                     (CWorkshopGetEULAStatusResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cworkshop__get_eulastatus__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cworkshop__get_eulastatus__request__field_descriptors[1] =
{
  {
    "appid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CWorkshopGetEULAStatusRequest, has_appid),
    offsetof(CWorkshopGetEULAStatusRequest, appid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cworkshop__get_eulastatus__request__field_indices_by_name[] = {
  0,   /* field[0] = appid */
};
static const ProtobufCIntRange cworkshop__get_eulastatus__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cworkshop__get_eulastatus__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CWorkshop_GetEULAStatus_Request",
  "CWorkshopGetEULAStatusRequest",
  "CWorkshopGetEULAStatusRequest",
  "",
  sizeof(CWorkshopGetEULAStatusRequest),
  1,
  cworkshop__get_eulastatus__request__field_descriptors,
  cworkshop__get_eulastatus__request__field_indices_by_name,
  1,  cworkshop__get_eulastatus__request__number_ranges,
  (ProtobufCMessageInit) cworkshop__get_eulastatus__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cworkshop__get_eulastatus__response__field_descriptors[4] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CWorkshopGetEULAStatusResponse, has_version),
    offsetof(CWorkshopGetEULAStatusResponse, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_action",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CWorkshopGetEULAStatusResponse, has_timestamp_action),
    offsetof(CWorkshopGetEULAStatusResponse, timestamp_action),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accepted",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CWorkshopGetEULAStatusResponse, has_accepted),
    offsetof(CWorkshopGetEULAStatusResponse, accepted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "needs_action",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CWorkshopGetEULAStatusResponse, has_needs_action),
    offsetof(CWorkshopGetEULAStatusResponse, needs_action),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cworkshop__get_eulastatus__response__field_indices_by_name[] = {
  2,   /* field[2] = accepted */
  3,   /* field[3] = needs_action */
  1,   /* field[1] = timestamp_action */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange cworkshop__get_eulastatus__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cworkshop__get_eulastatus__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CWorkshop_GetEULAStatus_Response",
  "CWorkshopGetEULAStatusResponse",
  "CWorkshopGetEULAStatusResponse",
  "",
  sizeof(CWorkshopGetEULAStatusResponse),
  4,
  cworkshop__get_eulastatus__response__field_descriptors,
  cworkshop__get_eulastatus__response__field_indices_by_name,
  1,  cworkshop__get_eulastatus__response__number_ranges,
  (ProtobufCMessageInit) cworkshop__get_eulastatus__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor workshop__method_descriptors[1] =
{
  { "GetEULAStatus", &cworkshop__get_eulastatus__request__descriptor, &cworkshop__get_eulastatus__response__descriptor },
};
const unsigned workshop__method_indices_by_name[] = {
  0         /* GetEULAStatus */
};
const ProtobufCServiceDescriptor workshop__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "Workshop",
  "Workshop",
  "Workshop",
  "",
  1,
  workshop__method_descriptors,
  workshop__method_indices_by_name
};
void workshop__get_eulastatus(ProtobufCService *service,
                              const CWorkshopGetEULAStatusRequest *input,
                              CWorkshopGetEULAStatusResponse_Closure closure,
                              void *closure_data)
{
  assert(service->descriptor == &workshop__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void workshop__init (Workshop_Service *service,
                     Workshop_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &workshop__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
