/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_gamerecording_objects.proto */

#ifndef PROTOBUF_C_steammessages_5fgamerecording_5fobjects_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5fgamerecording_5fobjects_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "enums.pb-c.h"

typedef struct CGameRecordingAudioSessionsChangedNotification CGameRecordingAudioSessionsChangedNotification;
typedef struct CGameRecordingAudioSessionsChangedNotification__Session CGameRecordingAudioSessionsChangedNotification__Session;


/* --- enums --- */


/* --- messages --- */

struct  CGameRecordingAudioSessionsChangedNotification__Session
{
  ProtobufCMessage base;
  char *id;
  char *name;
  protobuf_c_boolean has_is_system;
  protobuf_c_boolean is_system;
  protobuf_c_boolean has_is_muted;
  protobuf_c_boolean is_muted;
  protobuf_c_boolean has_is_active;
  protobuf_c_boolean is_active;
  protobuf_c_boolean has_is_captured;
  protobuf_c_boolean is_captured;
  protobuf_c_boolean has_recent_peak;
  float recent_peak;
  protobuf_c_boolean has_is_game;
  protobuf_c_boolean is_game;
  protobuf_c_boolean has_is_steam;
  protobuf_c_boolean is_steam;
  protobuf_c_boolean has_is_saved;
  protobuf_c_boolean is_saved;
};
#define CGAME_RECORDING__AUDIO_SESSIONS_CHANGED__NOTIFICATION__SESSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cgame_recording__audio_sessions_changed__notification__session__descriptor) \
, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CGameRecordingAudioSessionsChangedNotification
{
  ProtobufCMessage base;
  size_t n_sessions;
  CGameRecordingAudioSessionsChangedNotification__Session **sessions;
};
#define CGAME_RECORDING__AUDIO_SESSIONS_CHANGED__NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cgame_recording__audio_sessions_changed__notification__descriptor) \
, 0,NULL }


/* CGameRecordingAudioSessionsChangedNotification__Session methods */
void   cgame_recording__audio_sessions_changed__notification__session__init
                     (CGameRecordingAudioSessionsChangedNotification__Session         *message);
/* CGameRecordingAudioSessionsChangedNotification methods */
void   cgame_recording__audio_sessions_changed__notification__init
                     (CGameRecordingAudioSessionsChangedNotification         *message);
size_t cgame_recording__audio_sessions_changed__notification__get_packed_size
                     (const CGameRecordingAudioSessionsChangedNotification   *message);
size_t cgame_recording__audio_sessions_changed__notification__pack
                     (const CGameRecordingAudioSessionsChangedNotification   *message,
                      uint8_t             *out);
size_t cgame_recording__audio_sessions_changed__notification__pack_to_buffer
                     (const CGameRecordingAudioSessionsChangedNotification   *message,
                      ProtobufCBuffer     *buffer);
CGameRecordingAudioSessionsChangedNotification *
       cgame_recording__audio_sessions_changed__notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cgame_recording__audio_sessions_changed__notification__free_unpacked
                     (CGameRecordingAudioSessionsChangedNotification *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CGameRecordingAudioSessionsChangedNotification__Session_Closure)
                 (const CGameRecordingAudioSessionsChangedNotification__Session *message,
                  void *closure_data);
typedef void (*CGameRecordingAudioSessionsChangedNotification_Closure)
                 (const CGameRecordingAudioSessionsChangedNotification *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cgame_recording__audio_sessions_changed__notification__descriptor;
extern const ProtobufCMessageDescriptor cgame_recording__audio_sessions_changed__notification__session__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5fgamerecording_5fobjects_2eproto__INCLUDED */
