/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: webuimessages_gamenotes.proto */

#ifndef PROTOBUF_C_webuimessages_5fgamenotes_2eproto__INCLUDED
#define PROTOBUF_C_webuimessages_5fgamenotes_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "webuimessages_base.pb-c.h"

typedef struct CGameNotesUploadImageRequest CGameNotesUploadImageRequest;
typedef struct CGameNotesUploadImageResponse CGameNotesUploadImageResponse;


/* --- enums --- */


/* --- messages --- */

struct  CGameNotesUploadImageRequest
{
  ProtobufCMessage base;
  char *file_prefix;
  char *mime_type;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
};
#define CGAME_NOTES__UPLOAD_IMAGE__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cgame_notes__upload_image__request__descriptor) \
, NULL, NULL, 0, {0,NULL} }


struct  CGameNotesUploadImageResponse
{
  ProtobufCMessage base;
  char *filename;
};
#define CGAME_NOTES__UPLOAD_IMAGE__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cgame_notes__upload_image__response__descriptor) \
, NULL }


/* CGameNotesUploadImageRequest methods */
void   cgame_notes__upload_image__request__init
                     (CGameNotesUploadImageRequest         *message);
size_t cgame_notes__upload_image__request__get_packed_size
                     (const CGameNotesUploadImageRequest   *message);
size_t cgame_notes__upload_image__request__pack
                     (const CGameNotesUploadImageRequest   *message,
                      uint8_t             *out);
size_t cgame_notes__upload_image__request__pack_to_buffer
                     (const CGameNotesUploadImageRequest   *message,
                      ProtobufCBuffer     *buffer);
CGameNotesUploadImageRequest *
       cgame_notes__upload_image__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cgame_notes__upload_image__request__free_unpacked
                     (CGameNotesUploadImageRequest *message,
                      ProtobufCAllocator *allocator);
/* CGameNotesUploadImageResponse methods */
void   cgame_notes__upload_image__response__init
                     (CGameNotesUploadImageResponse         *message);
size_t cgame_notes__upload_image__response__get_packed_size
                     (const CGameNotesUploadImageResponse   *message);
size_t cgame_notes__upload_image__response__pack
                     (const CGameNotesUploadImageResponse   *message,
                      uint8_t             *out);
size_t cgame_notes__upload_image__response__pack_to_buffer
                     (const CGameNotesUploadImageResponse   *message,
                      ProtobufCBuffer     *buffer);
CGameNotesUploadImageResponse *
       cgame_notes__upload_image__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cgame_notes__upload_image__response__free_unpacked
                     (CGameNotesUploadImageResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CGameNotesUploadImageRequest_Closure)
                 (const CGameNotesUploadImageRequest *message,
                  void *closure_data);
typedef void (*CGameNotesUploadImageResponse_Closure)
                 (const CGameNotesUploadImageResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct GameNotes_Service GameNotes_Service;
struct GameNotes_Service
{
  ProtobufCService base;
  void (*upload_image)(GameNotes_Service *service,
                       const CGameNotesUploadImageRequest *input,
                       CGameNotesUploadImageResponse_Closure closure,
                       void *closure_data);
};
typedef void (*GameNotes_ServiceDestroy)(GameNotes_Service *);
void game_notes__init (GameNotes_Service *service,
                       GameNotes_ServiceDestroy destroy);
#define GAME_NOTES__BASE_INIT \
    { &game_notes__descriptor, protobuf_c_service_invoke_internal, NULL }
#define GAME_NOTES__INIT(function_prefix__) \
    { GAME_NOTES__BASE_INIT,\
      function_prefix__ ## upload_image  }
void game_notes__upload_image(ProtobufCService *service,
                              const CGameNotesUploadImageRequest *input,
                              CGameNotesUploadImageResponse_Closure closure,
                              void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cgame_notes__upload_image__request__descriptor;
extern const ProtobufCMessageDescriptor cgame_notes__upload_image__response__descriptor;
extern const ProtobufCServiceDescriptor game_notes__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_webuimessages_5fgamenotes_2eproto__INCLUDED */
