/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: webuimessages_storagedevicemanager.proto */

#ifndef PROTOBUF_C_webuimessages_5fstoragedevicemanager_2eproto__INCLUDED
#define PROTOBUF_C_webuimessages_5fstoragedevicemanager_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "enums.pb-c.h"
#include "steammessages_base.pb-c.h"
#include "webuimessages_base.pb-c.h"

typedef struct CStorageDeviceManagerIsServiceAvailableRequest CStorageDeviceManagerIsServiceAvailableRequest;
typedef struct CStorageDeviceManagerIsServiceAvailableResponse CStorageDeviceManagerIsServiceAvailableResponse;
typedef struct CStorageDeviceManagerDrive CStorageDeviceManagerDrive;
typedef struct CStorageDeviceManagerBlockDevice CStorageDeviceManagerBlockDevice;
typedef struct CStorageDeviceManagerState CStorageDeviceManagerState;
typedef struct CStorageDeviceManagerGetStateRequest CStorageDeviceManagerGetStateRequest;
typedef struct CStorageDeviceManagerGetStateResponse CStorageDeviceManagerGetStateResponse;
typedef struct CStorageDeviceManagerStateChangedNotification CStorageDeviceManagerStateChangedNotification;
typedef struct CStorageDeviceManagerEjectRequest CStorageDeviceManagerEjectRequest;
typedef struct CStorageDeviceManagerEjectResponse CStorageDeviceManagerEjectResponse;
typedef struct CStorageDeviceManagerAdoptRequest CStorageDeviceManagerAdoptRequest;
typedef struct CStorageDeviceManagerAdoptResponse CStorageDeviceManagerAdoptResponse;
typedef struct CStorageDeviceManagerFormatRequest CStorageDeviceManagerFormatRequest;
typedef struct CStorageDeviceManagerFormatResponse CStorageDeviceManagerFormatResponse;
typedef struct CStorageDeviceManagerUnmountRequest CStorageDeviceManagerUnmountRequest;
typedef struct CStorageDeviceManagerUnmountResponse CStorageDeviceManagerUnmountResponse;
typedef struct CStorageDeviceManagerTrimAllRequest CStorageDeviceManagerTrimAllRequest;
typedef struct CStorageDeviceManagerTrimAllResponse CStorageDeviceManagerTrimAllResponse;


/* --- enums --- */


/* --- messages --- */

struct  CStorageDeviceManagerIsServiceAvailableRequest
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__IS_SERVICE_AVAILABLE__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__is_service_available__request__descriptor) \
 }


struct  CStorageDeviceManagerIsServiceAvailableResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_is_available;
  protobuf_c_boolean is_available;
};
#define CSTORAGE_DEVICE_MANAGER__IS_SERVICE_AVAILABLE__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__is_service_available__response__descriptor) \
, 0, 0 }


struct  CStorageDeviceManagerDrive
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  uint32_t id;
  char *model;
  char *vendor;
  char *serial;
  protobuf_c_boolean has_is_ejectable;
  protobuf_c_boolean is_ejectable;
  protobuf_c_boolean has_size_bytes;
  uint64_t size_bytes;
  protobuf_c_boolean has_media_type;
  EStorageDriveMediaType media_type;
  protobuf_c_boolean has_is_unformatted;
  protobuf_c_boolean is_unformatted;
  protobuf_c_boolean has_adopt_stage;
  EStorageFormatStage adopt_stage;
  protobuf_c_boolean has_is_formattable;
  protobuf_c_boolean is_formattable;
  protobuf_c_boolean has_is_media_available;
  protobuf_c_boolean is_media_available;
};
#define CSTORAGE_DEVICE_MANAGER_DRIVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager_drive__descriptor) \
, 0, 0u, NULL, NULL, NULL, 0, 0, 0, 0, 0, ESTORAGE_DRIVE_MEDIA_TYPE__k_EStorageDriveMediaType_Invalid, 0, 0, 0, ESTORAGE_FORMAT_STAGE__k_EStorageFormatStage_Invalid, 0, 0, 0, 0 }


struct  CStorageDeviceManagerBlockDevice
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  uint32_t id;
  protobuf_c_boolean has_drive_id;
  uint32_t drive_id;
  char *path;
  char *friendly_path;
  char *label;
  protobuf_c_boolean has_size_bytes;
  uint64_t size_bytes;
  protobuf_c_boolean has_is_formattable;
  protobuf_c_boolean is_formattable;
  protobuf_c_boolean has_is_read_only;
  protobuf_c_boolean is_read_only;
  protobuf_c_boolean has_is_root_device;
  protobuf_c_boolean is_root_device;
  protobuf_c_boolean has_content_type;
  EStorageBlockContentType content_type;
  protobuf_c_boolean has_filesystem_type;
  EStorageBlockFileSystemType filesystem_type;
  size_t n_mount_paths;
  char **mount_paths;
  protobuf_c_boolean has_is_unmounting;
  protobuf_c_boolean is_unmounting;
  protobuf_c_boolean has_has_steam_library;
  protobuf_c_boolean has_steam_library;
};
#define CSTORAGE_DEVICE_MANAGER_BLOCK_DEVICE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager_block_device__descriptor) \
, 0, 0u, 0, 0u, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, ESTORAGE_BLOCK_CONTENT_TYPE__k_EStorageBlockContentType_Invalid, 0, ESTORAGE_BLOCK_FILE_SYSTEM_TYPE__k_EStorageBlockFileSystemType_Invalid, 0,NULL, 0, 0, 0, 0 }


struct  CStorageDeviceManagerState
{
  ProtobufCMessage base;
  size_t n_drives;
  CStorageDeviceManagerDrive **drives;
  size_t n_block_devices;
  CStorageDeviceManagerBlockDevice **block_devices;
  protobuf_c_boolean has_is_unmount_supported;
  protobuf_c_boolean is_unmount_supported;
  protobuf_c_boolean has_is_trim_supported;
  protobuf_c_boolean is_trim_supported;
  protobuf_c_boolean has_is_trim_running;
  protobuf_c_boolean is_trim_running;
  protobuf_c_boolean has_is_adopt_supported;
  protobuf_c_boolean is_adopt_supported;
};
#define CSTORAGE_DEVICE_MANAGER_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager_state__descriptor) \
, 0,NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  CStorageDeviceManagerGetStateRequest
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__GET_STATE__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__get_state__request__descriptor) \
 }


struct  CStorageDeviceManagerGetStateResponse
{
  ProtobufCMessage base;
  CStorageDeviceManagerState *state;
};
#define CSTORAGE_DEVICE_MANAGER__GET_STATE__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__get_state__response__descriptor) \
, NULL }


struct  CStorageDeviceManagerStateChangedNotification
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__STATE_CHANGED__NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__state_changed__notification__descriptor) \
 }


struct  CStorageDeviceManagerEjectRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_drive_id;
  uint32_t drive_id;
};
#define CSTORAGE_DEVICE_MANAGER__EJECT__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__eject__request__descriptor) \
, 0, 0 }


struct  CStorageDeviceManagerEjectResponse
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__EJECT__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__eject__response__descriptor) \
 }


struct  CStorageDeviceManagerAdoptRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_drive_id;
  uint32_t drive_id;
  char *label;
  protobuf_c_boolean has_validate;
  protobuf_c_boolean validate;
};
#define CSTORAGE_DEVICE_MANAGER__ADOPT__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__adopt__request__descriptor) \
, 0, 0, NULL, 0, 0 }


struct  CStorageDeviceManagerAdoptResponse
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__ADOPT__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__adopt__response__descriptor) \
 }


struct  CStorageDeviceManagerFormatRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_block_device_id;
  uint32_t block_device_id;
};
#define CSTORAGE_DEVICE_MANAGER__FORMAT__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__format__request__descriptor) \
, 0, 0 }


struct  CStorageDeviceManagerFormatResponse
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__FORMAT__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__format__response__descriptor) \
 }


struct  CStorageDeviceManagerUnmountRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_block_device_id;
  uint32_t block_device_id;
};
#define CSTORAGE_DEVICE_MANAGER__UNMOUNT__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__unmount__request__descriptor) \
, 0, 0 }


struct  CStorageDeviceManagerUnmountResponse
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__UNMOUNT__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__unmount__response__descriptor) \
 }


struct  CStorageDeviceManagerTrimAllRequest
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__TRIM_ALL__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__trim_all__request__descriptor) \
 }


struct  CStorageDeviceManagerTrimAllResponse
{
  ProtobufCMessage base;
};
#define CSTORAGE_DEVICE_MANAGER__TRIM_ALL__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstorage_device_manager__trim_all__response__descriptor) \
 }


/* CStorageDeviceManagerIsServiceAvailableRequest methods */
void   cstorage_device_manager__is_service_available__request__init
                     (CStorageDeviceManagerIsServiceAvailableRequest         *message);
size_t cstorage_device_manager__is_service_available__request__get_packed_size
                     (const CStorageDeviceManagerIsServiceAvailableRequest   *message);
size_t cstorage_device_manager__is_service_available__request__pack
                     (const CStorageDeviceManagerIsServiceAvailableRequest   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__is_service_available__request__pack_to_buffer
                     (const CStorageDeviceManagerIsServiceAvailableRequest   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerIsServiceAvailableRequest *
       cstorage_device_manager__is_service_available__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__is_service_available__request__free_unpacked
                     (CStorageDeviceManagerIsServiceAvailableRequest *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerIsServiceAvailableResponse methods */
void   cstorage_device_manager__is_service_available__response__init
                     (CStorageDeviceManagerIsServiceAvailableResponse         *message);
size_t cstorage_device_manager__is_service_available__response__get_packed_size
                     (const CStorageDeviceManagerIsServiceAvailableResponse   *message);
size_t cstorage_device_manager__is_service_available__response__pack
                     (const CStorageDeviceManagerIsServiceAvailableResponse   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__is_service_available__response__pack_to_buffer
                     (const CStorageDeviceManagerIsServiceAvailableResponse   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerIsServiceAvailableResponse *
       cstorage_device_manager__is_service_available__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__is_service_available__response__free_unpacked
                     (CStorageDeviceManagerIsServiceAvailableResponse *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerDrive methods */
void   cstorage_device_manager_drive__init
                     (CStorageDeviceManagerDrive         *message);
size_t cstorage_device_manager_drive__get_packed_size
                     (const CStorageDeviceManagerDrive   *message);
size_t cstorage_device_manager_drive__pack
                     (const CStorageDeviceManagerDrive   *message,
                      uint8_t             *out);
size_t cstorage_device_manager_drive__pack_to_buffer
                     (const CStorageDeviceManagerDrive   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerDrive *
       cstorage_device_manager_drive__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager_drive__free_unpacked
                     (CStorageDeviceManagerDrive *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerBlockDevice methods */
void   cstorage_device_manager_block_device__init
                     (CStorageDeviceManagerBlockDevice         *message);
size_t cstorage_device_manager_block_device__get_packed_size
                     (const CStorageDeviceManagerBlockDevice   *message);
size_t cstorage_device_manager_block_device__pack
                     (const CStorageDeviceManagerBlockDevice   *message,
                      uint8_t             *out);
size_t cstorage_device_manager_block_device__pack_to_buffer
                     (const CStorageDeviceManagerBlockDevice   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerBlockDevice *
       cstorage_device_manager_block_device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager_block_device__free_unpacked
                     (CStorageDeviceManagerBlockDevice *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerState methods */
void   cstorage_device_manager_state__init
                     (CStorageDeviceManagerState         *message);
size_t cstorage_device_manager_state__get_packed_size
                     (const CStorageDeviceManagerState   *message);
size_t cstorage_device_manager_state__pack
                     (const CStorageDeviceManagerState   *message,
                      uint8_t             *out);
size_t cstorage_device_manager_state__pack_to_buffer
                     (const CStorageDeviceManagerState   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerState *
       cstorage_device_manager_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager_state__free_unpacked
                     (CStorageDeviceManagerState *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerGetStateRequest methods */
void   cstorage_device_manager__get_state__request__init
                     (CStorageDeviceManagerGetStateRequest         *message);
size_t cstorage_device_manager__get_state__request__get_packed_size
                     (const CStorageDeviceManagerGetStateRequest   *message);
size_t cstorage_device_manager__get_state__request__pack
                     (const CStorageDeviceManagerGetStateRequest   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__get_state__request__pack_to_buffer
                     (const CStorageDeviceManagerGetStateRequest   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerGetStateRequest *
       cstorage_device_manager__get_state__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__get_state__request__free_unpacked
                     (CStorageDeviceManagerGetStateRequest *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerGetStateResponse methods */
void   cstorage_device_manager__get_state__response__init
                     (CStorageDeviceManagerGetStateResponse         *message);
size_t cstorage_device_manager__get_state__response__get_packed_size
                     (const CStorageDeviceManagerGetStateResponse   *message);
size_t cstorage_device_manager__get_state__response__pack
                     (const CStorageDeviceManagerGetStateResponse   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__get_state__response__pack_to_buffer
                     (const CStorageDeviceManagerGetStateResponse   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerGetStateResponse *
       cstorage_device_manager__get_state__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__get_state__response__free_unpacked
                     (CStorageDeviceManagerGetStateResponse *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerStateChangedNotification methods */
void   cstorage_device_manager__state_changed__notification__init
                     (CStorageDeviceManagerStateChangedNotification         *message);
size_t cstorage_device_manager__state_changed__notification__get_packed_size
                     (const CStorageDeviceManagerStateChangedNotification   *message);
size_t cstorage_device_manager__state_changed__notification__pack
                     (const CStorageDeviceManagerStateChangedNotification   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__state_changed__notification__pack_to_buffer
                     (const CStorageDeviceManagerStateChangedNotification   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerStateChangedNotification *
       cstorage_device_manager__state_changed__notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__state_changed__notification__free_unpacked
                     (CStorageDeviceManagerStateChangedNotification *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerEjectRequest methods */
void   cstorage_device_manager__eject__request__init
                     (CStorageDeviceManagerEjectRequest         *message);
size_t cstorage_device_manager__eject__request__get_packed_size
                     (const CStorageDeviceManagerEjectRequest   *message);
size_t cstorage_device_manager__eject__request__pack
                     (const CStorageDeviceManagerEjectRequest   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__eject__request__pack_to_buffer
                     (const CStorageDeviceManagerEjectRequest   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerEjectRequest *
       cstorage_device_manager__eject__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__eject__request__free_unpacked
                     (CStorageDeviceManagerEjectRequest *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerEjectResponse methods */
void   cstorage_device_manager__eject__response__init
                     (CStorageDeviceManagerEjectResponse         *message);
size_t cstorage_device_manager__eject__response__get_packed_size
                     (const CStorageDeviceManagerEjectResponse   *message);
size_t cstorage_device_manager__eject__response__pack
                     (const CStorageDeviceManagerEjectResponse   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__eject__response__pack_to_buffer
                     (const CStorageDeviceManagerEjectResponse   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerEjectResponse *
       cstorage_device_manager__eject__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__eject__response__free_unpacked
                     (CStorageDeviceManagerEjectResponse *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerAdoptRequest methods */
void   cstorage_device_manager__adopt__request__init
                     (CStorageDeviceManagerAdoptRequest         *message);
size_t cstorage_device_manager__adopt__request__get_packed_size
                     (const CStorageDeviceManagerAdoptRequest   *message);
size_t cstorage_device_manager__adopt__request__pack
                     (const CStorageDeviceManagerAdoptRequest   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__adopt__request__pack_to_buffer
                     (const CStorageDeviceManagerAdoptRequest   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerAdoptRequest *
       cstorage_device_manager__adopt__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__adopt__request__free_unpacked
                     (CStorageDeviceManagerAdoptRequest *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerAdoptResponse methods */
void   cstorage_device_manager__adopt__response__init
                     (CStorageDeviceManagerAdoptResponse         *message);
size_t cstorage_device_manager__adopt__response__get_packed_size
                     (const CStorageDeviceManagerAdoptResponse   *message);
size_t cstorage_device_manager__adopt__response__pack
                     (const CStorageDeviceManagerAdoptResponse   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__adopt__response__pack_to_buffer
                     (const CStorageDeviceManagerAdoptResponse   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerAdoptResponse *
       cstorage_device_manager__adopt__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__adopt__response__free_unpacked
                     (CStorageDeviceManagerAdoptResponse *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerFormatRequest methods */
void   cstorage_device_manager__format__request__init
                     (CStorageDeviceManagerFormatRequest         *message);
size_t cstorage_device_manager__format__request__get_packed_size
                     (const CStorageDeviceManagerFormatRequest   *message);
size_t cstorage_device_manager__format__request__pack
                     (const CStorageDeviceManagerFormatRequest   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__format__request__pack_to_buffer
                     (const CStorageDeviceManagerFormatRequest   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerFormatRequest *
       cstorage_device_manager__format__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__format__request__free_unpacked
                     (CStorageDeviceManagerFormatRequest *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerFormatResponse methods */
void   cstorage_device_manager__format__response__init
                     (CStorageDeviceManagerFormatResponse         *message);
size_t cstorage_device_manager__format__response__get_packed_size
                     (const CStorageDeviceManagerFormatResponse   *message);
size_t cstorage_device_manager__format__response__pack
                     (const CStorageDeviceManagerFormatResponse   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__format__response__pack_to_buffer
                     (const CStorageDeviceManagerFormatResponse   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerFormatResponse *
       cstorage_device_manager__format__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__format__response__free_unpacked
                     (CStorageDeviceManagerFormatResponse *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerUnmountRequest methods */
void   cstorage_device_manager__unmount__request__init
                     (CStorageDeviceManagerUnmountRequest         *message);
size_t cstorage_device_manager__unmount__request__get_packed_size
                     (const CStorageDeviceManagerUnmountRequest   *message);
size_t cstorage_device_manager__unmount__request__pack
                     (const CStorageDeviceManagerUnmountRequest   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__unmount__request__pack_to_buffer
                     (const CStorageDeviceManagerUnmountRequest   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerUnmountRequest *
       cstorage_device_manager__unmount__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__unmount__request__free_unpacked
                     (CStorageDeviceManagerUnmountRequest *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerUnmountResponse methods */
void   cstorage_device_manager__unmount__response__init
                     (CStorageDeviceManagerUnmountResponse         *message);
size_t cstorage_device_manager__unmount__response__get_packed_size
                     (const CStorageDeviceManagerUnmountResponse   *message);
size_t cstorage_device_manager__unmount__response__pack
                     (const CStorageDeviceManagerUnmountResponse   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__unmount__response__pack_to_buffer
                     (const CStorageDeviceManagerUnmountResponse   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerUnmountResponse *
       cstorage_device_manager__unmount__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__unmount__response__free_unpacked
                     (CStorageDeviceManagerUnmountResponse *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerTrimAllRequest methods */
void   cstorage_device_manager__trim_all__request__init
                     (CStorageDeviceManagerTrimAllRequest         *message);
size_t cstorage_device_manager__trim_all__request__get_packed_size
                     (const CStorageDeviceManagerTrimAllRequest   *message);
size_t cstorage_device_manager__trim_all__request__pack
                     (const CStorageDeviceManagerTrimAllRequest   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__trim_all__request__pack_to_buffer
                     (const CStorageDeviceManagerTrimAllRequest   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerTrimAllRequest *
       cstorage_device_manager__trim_all__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__trim_all__request__free_unpacked
                     (CStorageDeviceManagerTrimAllRequest *message,
                      ProtobufCAllocator *allocator);
/* CStorageDeviceManagerTrimAllResponse methods */
void   cstorage_device_manager__trim_all__response__init
                     (CStorageDeviceManagerTrimAllResponse         *message);
size_t cstorage_device_manager__trim_all__response__get_packed_size
                     (const CStorageDeviceManagerTrimAllResponse   *message);
size_t cstorage_device_manager__trim_all__response__pack
                     (const CStorageDeviceManagerTrimAllResponse   *message,
                      uint8_t             *out);
size_t cstorage_device_manager__trim_all__response__pack_to_buffer
                     (const CStorageDeviceManagerTrimAllResponse   *message,
                      ProtobufCBuffer     *buffer);
CStorageDeviceManagerTrimAllResponse *
       cstorage_device_manager__trim_all__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstorage_device_manager__trim_all__response__free_unpacked
                     (CStorageDeviceManagerTrimAllResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CStorageDeviceManagerIsServiceAvailableRequest_Closure)
                 (const CStorageDeviceManagerIsServiceAvailableRequest *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerIsServiceAvailableResponse_Closure)
                 (const CStorageDeviceManagerIsServiceAvailableResponse *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerDrive_Closure)
                 (const CStorageDeviceManagerDrive *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerBlockDevice_Closure)
                 (const CStorageDeviceManagerBlockDevice *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerState_Closure)
                 (const CStorageDeviceManagerState *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerGetStateRequest_Closure)
                 (const CStorageDeviceManagerGetStateRequest *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerGetStateResponse_Closure)
                 (const CStorageDeviceManagerGetStateResponse *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerStateChangedNotification_Closure)
                 (const CStorageDeviceManagerStateChangedNotification *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerEjectRequest_Closure)
                 (const CStorageDeviceManagerEjectRequest *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerEjectResponse_Closure)
                 (const CStorageDeviceManagerEjectResponse *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerAdoptRequest_Closure)
                 (const CStorageDeviceManagerAdoptRequest *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerAdoptResponse_Closure)
                 (const CStorageDeviceManagerAdoptResponse *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerFormatRequest_Closure)
                 (const CStorageDeviceManagerFormatRequest *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerFormatResponse_Closure)
                 (const CStorageDeviceManagerFormatResponse *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerUnmountRequest_Closure)
                 (const CStorageDeviceManagerUnmountRequest *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerUnmountResponse_Closure)
                 (const CStorageDeviceManagerUnmountResponse *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerTrimAllRequest_Closure)
                 (const CStorageDeviceManagerTrimAllRequest *message,
                  void *closure_data);
typedef void (*CStorageDeviceManagerTrimAllResponse_Closure)
                 (const CStorageDeviceManagerTrimAllResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct StorageDeviceManager_Service StorageDeviceManager_Service;
struct StorageDeviceManager_Service
{
  ProtobufCService base;
  void (*is_service_available)(StorageDeviceManager_Service *service,
                               const CStorageDeviceManagerIsServiceAvailableRequest *input,
                               CStorageDeviceManagerIsServiceAvailableResponse_Closure closure,
                               void *closure_data);
  void (*get_state)(StorageDeviceManager_Service *service,
                    const CStorageDeviceManagerGetStateRequest *input,
                    CStorageDeviceManagerGetStateResponse_Closure closure,
                    void *closure_data);
  void (*notify_state_changed)(StorageDeviceManager_Service *service,
                               const CStorageDeviceManagerStateChangedNotification *input,
                               WebUINoResponse_Closure closure,
                               void *closure_data);
  void (*adopt)(StorageDeviceManager_Service *service,
                const CStorageDeviceManagerAdoptRequest *input,
                CStorageDeviceManagerAdoptResponse_Closure closure,
                void *closure_data);
  void (*eject)(StorageDeviceManager_Service *service,
                const CStorageDeviceManagerEjectRequest *input,
                CStorageDeviceManagerEjectResponse_Closure closure,
                void *closure_data);
  void (*format)(StorageDeviceManager_Service *service,
                 const CStorageDeviceManagerFormatRequest *input,
                 CStorageDeviceManagerFormatResponse_Closure closure,
                 void *closure_data);
  void (*unmount)(StorageDeviceManager_Service *service,
                  const CStorageDeviceManagerUnmountRequest *input,
                  CStorageDeviceManagerUnmountResponse_Closure closure,
                  void *closure_data);
  void (*trim_all)(StorageDeviceManager_Service *service,
                   const CStorageDeviceManagerTrimAllRequest *input,
                   CStorageDeviceManagerTrimAllResponse_Closure closure,
                   void *closure_data);
};
typedef void (*StorageDeviceManager_ServiceDestroy)(StorageDeviceManager_Service *);
void storage_device_manager__init (StorageDeviceManager_Service *service,
                                   StorageDeviceManager_ServiceDestroy destroy);
#define STORAGE_DEVICE_MANAGER__BASE_INIT \
    { &storage_device_manager__descriptor, protobuf_c_service_invoke_internal, NULL }
#define STORAGE_DEVICE_MANAGER__INIT(function_prefix__) \
    { STORAGE_DEVICE_MANAGER__BASE_INIT,\
      function_prefix__ ## is_service_available,\
      function_prefix__ ## get_state,\
      function_prefix__ ## notify_state_changed,\
      function_prefix__ ## adopt,\
      function_prefix__ ## eject,\
      function_prefix__ ## format,\
      function_prefix__ ## unmount,\
      function_prefix__ ## trim_all  }
void storage_device_manager__is_service_available(ProtobufCService *service,
                                                  const CStorageDeviceManagerIsServiceAvailableRequest *input,
                                                  CStorageDeviceManagerIsServiceAvailableResponse_Closure closure,
                                                  void *closure_data);
void storage_device_manager__get_state(ProtobufCService *service,
                                       const CStorageDeviceManagerGetStateRequest *input,
                                       CStorageDeviceManagerGetStateResponse_Closure closure,
                                       void *closure_data);
void storage_device_manager__notify_state_changed(ProtobufCService *service,
                                                  const CStorageDeviceManagerStateChangedNotification *input,
                                                  WebUINoResponse_Closure closure,
                                                  void *closure_data);
void storage_device_manager__adopt(ProtobufCService *service,
                                   const CStorageDeviceManagerAdoptRequest *input,
                                   CStorageDeviceManagerAdoptResponse_Closure closure,
                                   void *closure_data);
void storage_device_manager__eject(ProtobufCService *service,
                                   const CStorageDeviceManagerEjectRequest *input,
                                   CStorageDeviceManagerEjectResponse_Closure closure,
                                   void *closure_data);
void storage_device_manager__format(ProtobufCService *service,
                                    const CStorageDeviceManagerFormatRequest *input,
                                    CStorageDeviceManagerFormatResponse_Closure closure,
                                    void *closure_data);
void storage_device_manager__unmount(ProtobufCService *service,
                                     const CStorageDeviceManagerUnmountRequest *input,
                                     CStorageDeviceManagerUnmountResponse_Closure closure,
                                     void *closure_data);
void storage_device_manager__trim_all(ProtobufCService *service,
                                      const CStorageDeviceManagerTrimAllRequest *input,
                                      CStorageDeviceManagerTrimAllResponse_Closure closure,
                                      void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cstorage_device_manager__is_service_available__request__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__is_service_available__response__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager_drive__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager_block_device__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager_state__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__get_state__request__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__get_state__response__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__state_changed__notification__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__eject__request__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__eject__response__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__adopt__request__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__adopt__response__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__format__request__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__format__response__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__unmount__request__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__unmount__response__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__trim_all__request__descriptor;
extern const ProtobufCMessageDescriptor cstorage_device_manager__trim_all__response__descriptor;
extern const ProtobufCServiceDescriptor storage_device_manager__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_webuimessages_5fstoragedevicemanager_2eproto__INCLUDED */
