/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: webuimessages_transport.proto */

#ifndef PROTOBUF_C_webuimessages_5ftransport_2eproto__INCLUDED
#define PROTOBUF_C_webuimessages_5ftransport_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "webuimessages_base.pb-c.h"

typedef struct CTransportAuthAuthenticateRequest CTransportAuthAuthenticateRequest;
typedef struct CTransportAuthAuthenticateResponse CTransportAuthAuthenticateResponse;
typedef struct CTransportAuthStartShutdownNotification CTransportAuthStartShutdownNotification;


/* --- enums --- */


/* --- messages --- */

struct  CTransportAuthAuthenticateRequest
{
  ProtobufCMessage base;
  char *auth_key;
};
#define CTRANSPORT_AUTH__AUTHENTICATE__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctransport_auth__authenticate__request__descriptor) \
, NULL }


struct  CTransportAuthAuthenticateResponse
{
  ProtobufCMessage base;
};
#define CTRANSPORT_AUTH__AUTHENTICATE__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctransport_auth__authenticate__response__descriptor) \
 }


struct  CTransportAuthStartShutdownNotification
{
  ProtobufCMessage base;
};
#define CTRANSPORT_AUTH__START_SHUTDOWN__NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctransport_auth__start_shutdown__notification__descriptor) \
 }


/* CTransportAuthAuthenticateRequest methods */
void   ctransport_auth__authenticate__request__init
                     (CTransportAuthAuthenticateRequest         *message);
size_t ctransport_auth__authenticate__request__get_packed_size
                     (const CTransportAuthAuthenticateRequest   *message);
size_t ctransport_auth__authenticate__request__pack
                     (const CTransportAuthAuthenticateRequest   *message,
                      uint8_t             *out);
size_t ctransport_auth__authenticate__request__pack_to_buffer
                     (const CTransportAuthAuthenticateRequest   *message,
                      ProtobufCBuffer     *buffer);
CTransportAuthAuthenticateRequest *
       ctransport_auth__authenticate__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctransport_auth__authenticate__request__free_unpacked
                     (CTransportAuthAuthenticateRequest *message,
                      ProtobufCAllocator *allocator);
/* CTransportAuthAuthenticateResponse methods */
void   ctransport_auth__authenticate__response__init
                     (CTransportAuthAuthenticateResponse         *message);
size_t ctransport_auth__authenticate__response__get_packed_size
                     (const CTransportAuthAuthenticateResponse   *message);
size_t ctransport_auth__authenticate__response__pack
                     (const CTransportAuthAuthenticateResponse   *message,
                      uint8_t             *out);
size_t ctransport_auth__authenticate__response__pack_to_buffer
                     (const CTransportAuthAuthenticateResponse   *message,
                      ProtobufCBuffer     *buffer);
CTransportAuthAuthenticateResponse *
       ctransport_auth__authenticate__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctransport_auth__authenticate__response__free_unpacked
                     (CTransportAuthAuthenticateResponse *message,
                      ProtobufCAllocator *allocator);
/* CTransportAuthStartShutdownNotification methods */
void   ctransport_auth__start_shutdown__notification__init
                     (CTransportAuthStartShutdownNotification         *message);
size_t ctransport_auth__start_shutdown__notification__get_packed_size
                     (const CTransportAuthStartShutdownNotification   *message);
size_t ctransport_auth__start_shutdown__notification__pack
                     (const CTransportAuthStartShutdownNotification   *message,
                      uint8_t             *out);
size_t ctransport_auth__start_shutdown__notification__pack_to_buffer
                     (const CTransportAuthStartShutdownNotification   *message,
                      ProtobufCBuffer     *buffer);
CTransportAuthStartShutdownNotification *
       ctransport_auth__start_shutdown__notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctransport_auth__start_shutdown__notification__free_unpacked
                     (CTransportAuthStartShutdownNotification *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CTransportAuthAuthenticateRequest_Closure)
                 (const CTransportAuthAuthenticateRequest *message,
                  void *closure_data);
typedef void (*CTransportAuthAuthenticateResponse_Closure)
                 (const CTransportAuthAuthenticateResponse *message,
                  void *closure_data);
typedef void (*CTransportAuthStartShutdownNotification_Closure)
                 (const CTransportAuthStartShutdownNotification *message,
                  void *closure_data);

/* --- services --- */

typedef struct TransportAuth_Service TransportAuth_Service;
struct TransportAuth_Service
{
  ProtobufCService base;
  void (*authenticate)(TransportAuth_Service *service,
                       const CTransportAuthAuthenticateRequest *input,
                       CTransportAuthAuthenticateResponse_Closure closure,
                       void *closure_data);
  void (*notify_start_shutdown)(TransportAuth_Service *service,
                                const CTransportAuthStartShutdownNotification *input,
                                WebUINoResponse_Closure closure,
                                void *closure_data);
};
typedef void (*TransportAuth_ServiceDestroy)(TransportAuth_Service *);
void transport_auth__init (TransportAuth_Service *service,
                           TransportAuth_ServiceDestroy destroy);
#define TRANSPORT_AUTH__BASE_INIT \
    { &transport_auth__descriptor, protobuf_c_service_invoke_internal, NULL }
#define TRANSPORT_AUTH__INIT(function_prefix__) \
    { TRANSPORT_AUTH__BASE_INIT,\
      function_prefix__ ## authenticate,\
      function_prefix__ ## notify_start_shutdown  }
void transport_auth__authenticate(ProtobufCService *service,
                                  const CTransportAuthAuthenticateRequest *input,
                                  CTransportAuthAuthenticateResponse_Closure closure,
                                  void *closure_data);
void transport_auth__notify_start_shutdown(ProtobufCService *service,
                                           const CTransportAuthStartShutdownNotification *input,
                                           WebUINoResponse_Closure closure,
                                           void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ctransport_auth__authenticate__request__descriptor;
extern const ProtobufCMessageDescriptor ctransport_auth__authenticate__response__descriptor;
extern const ProtobufCMessageDescriptor ctransport_auth__start_shutdown__notification__descriptor;
extern const ProtobufCServiceDescriptor transport_auth__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_webuimessages_5ftransport_2eproto__INCLUDED */
