/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: webuimessages_systemmanager.proto */

#ifndef PROTOBUF_C_webuimessages_5fsystemmanager_2eproto__INCLUDED
#define PROTOBUF_C_webuimessages_5fsystemmanager_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "steammessages_base.pb-c.h"
#include "webuimessages_base.pb-c.h"

typedef struct CSystemManagerHibernateRequest CSystemManagerHibernateRequest;
typedef struct CSystemManagerHibernateResponse CSystemManagerHibernateResponse;
typedef struct CSystemManagerWriteFileRequest CSystemManagerWriteFileRequest;
typedef struct CSystemManagerWriteFileResponse CSystemManagerWriteFileResponse;


/* --- enums --- */


/* --- messages --- */

struct  CSystemManagerHibernateRequest
{
  ProtobufCMessage base;
};
#define CSYSTEM_MANAGER__HIBERNATE__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&csystem_manager__hibernate__request__descriptor) \
 }


struct  CSystemManagerHibernateResponse
{
  ProtobufCMessage base;
};
#define CSYSTEM_MANAGER__HIBERNATE__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&csystem_manager__hibernate__response__descriptor) \
 }


struct  CSystemManagerWriteFileRequest
{
  ProtobufCMessage base;
  char *path;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
};
#define CSYSTEM_MANAGER__WRITE_FILE__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&csystem_manager__write_file__request__descriptor) \
, NULL, 0, {0,NULL} }


struct  CSystemManagerWriteFileResponse
{
  ProtobufCMessage base;
};
#define CSYSTEM_MANAGER__WRITE_FILE__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&csystem_manager__write_file__response__descriptor) \
 }


/* CSystemManagerHibernateRequest methods */
void   csystem_manager__hibernate__request__init
                     (CSystemManagerHibernateRequest         *message);
size_t csystem_manager__hibernate__request__get_packed_size
                     (const CSystemManagerHibernateRequest   *message);
size_t csystem_manager__hibernate__request__pack
                     (const CSystemManagerHibernateRequest   *message,
                      uint8_t             *out);
size_t csystem_manager__hibernate__request__pack_to_buffer
                     (const CSystemManagerHibernateRequest   *message,
                      ProtobufCBuffer     *buffer);
CSystemManagerHibernateRequest *
       csystem_manager__hibernate__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   csystem_manager__hibernate__request__free_unpacked
                     (CSystemManagerHibernateRequest *message,
                      ProtobufCAllocator *allocator);
/* CSystemManagerHibernateResponse methods */
void   csystem_manager__hibernate__response__init
                     (CSystemManagerHibernateResponse         *message);
size_t csystem_manager__hibernate__response__get_packed_size
                     (const CSystemManagerHibernateResponse   *message);
size_t csystem_manager__hibernate__response__pack
                     (const CSystemManagerHibernateResponse   *message,
                      uint8_t             *out);
size_t csystem_manager__hibernate__response__pack_to_buffer
                     (const CSystemManagerHibernateResponse   *message,
                      ProtobufCBuffer     *buffer);
CSystemManagerHibernateResponse *
       csystem_manager__hibernate__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   csystem_manager__hibernate__response__free_unpacked
                     (CSystemManagerHibernateResponse *message,
                      ProtobufCAllocator *allocator);
/* CSystemManagerWriteFileRequest methods */
void   csystem_manager__write_file__request__init
                     (CSystemManagerWriteFileRequest         *message);
size_t csystem_manager__write_file__request__get_packed_size
                     (const CSystemManagerWriteFileRequest   *message);
size_t csystem_manager__write_file__request__pack
                     (const CSystemManagerWriteFileRequest   *message,
                      uint8_t             *out);
size_t csystem_manager__write_file__request__pack_to_buffer
                     (const CSystemManagerWriteFileRequest   *message,
                      ProtobufCBuffer     *buffer);
CSystemManagerWriteFileRequest *
       csystem_manager__write_file__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   csystem_manager__write_file__request__free_unpacked
                     (CSystemManagerWriteFileRequest *message,
                      ProtobufCAllocator *allocator);
/* CSystemManagerWriteFileResponse methods */
void   csystem_manager__write_file__response__init
                     (CSystemManagerWriteFileResponse         *message);
size_t csystem_manager__write_file__response__get_packed_size
                     (const CSystemManagerWriteFileResponse   *message);
size_t csystem_manager__write_file__response__pack
                     (const CSystemManagerWriteFileResponse   *message,
                      uint8_t             *out);
size_t csystem_manager__write_file__response__pack_to_buffer
                     (const CSystemManagerWriteFileResponse   *message,
                      ProtobufCBuffer     *buffer);
CSystemManagerWriteFileResponse *
       csystem_manager__write_file__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   csystem_manager__write_file__response__free_unpacked
                     (CSystemManagerWriteFileResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CSystemManagerHibernateRequest_Closure)
                 (const CSystemManagerHibernateRequest *message,
                  void *closure_data);
typedef void (*CSystemManagerHibernateResponse_Closure)
                 (const CSystemManagerHibernateResponse *message,
                  void *closure_data);
typedef void (*CSystemManagerWriteFileRequest_Closure)
                 (const CSystemManagerWriteFileRequest *message,
                  void *closure_data);
typedef void (*CSystemManagerWriteFileResponse_Closure)
                 (const CSystemManagerWriteFileResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct SystemManager_Service SystemManager_Service;
struct SystemManager_Service
{
  ProtobufCService base;
  void (*hibernate)(SystemManager_Service *service,
                    const CSystemManagerHibernateRequest *input,
                    CSystemManagerHibernateResponse_Closure closure,
                    void *closure_data);
  void (*write_file)(SystemManager_Service *service,
                     const CSystemManagerWriteFileRequest *input,
                     CSystemManagerWriteFileResponse_Closure closure,
                     void *closure_data);
};
typedef void (*SystemManager_ServiceDestroy)(SystemManager_Service *);
void system_manager__init (SystemManager_Service *service,
                           SystemManager_ServiceDestroy destroy);
#define SYSTEM_MANAGER__BASE_INIT \
    { &system_manager__descriptor, protobuf_c_service_invoke_internal, NULL }
#define SYSTEM_MANAGER__INIT(function_prefix__) \
    { SYSTEM_MANAGER__BASE_INIT,\
      function_prefix__ ## hibernate,\
      function_prefix__ ## write_file  }
void system_manager__hibernate(ProtobufCService *service,
                               const CSystemManagerHibernateRequest *input,
                               CSystemManagerHibernateResponse_Closure closure,
                               void *closure_data);
void system_manager__write_file(ProtobufCService *service,
                                const CSystemManagerWriteFileRequest *input,
                                CSystemManagerWriteFileResponse_Closure closure,
                                void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor csystem_manager__hibernate__request__descriptor;
extern const ProtobufCMessageDescriptor csystem_manager__hibernate__response__descriptor;
extern const ProtobufCMessageDescriptor csystem_manager__write_file__request__descriptor;
extern const ProtobufCMessageDescriptor csystem_manager__write_file__response__descriptor;
extern const ProtobufCServiceDescriptor system_manager__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_webuimessages_5fsystemmanager_2eproto__INCLUDED */
