#ifndef STEAMKIT_STEAM_HANDLERS_STEAM_FRIENDS_CALLBACKS_H
#define STEAMKIT_STEAM_HANDLERS_STEAM_FRIENDS_CALLBACKS_H

#include "steamkit/steam/callbacks.h"
#include "steamkit/types/steam_id.h"
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum sk_friend_relationship {
    SK_FRIEND_RELATIONSHIP_NONE = 0,
    SK_FRIEND_RELATIONSHIP_BLOCKED = 1,
    SK_FRIEND_RELATIONSHIP_REQUEST_RECEIVED = 2,
    SK_FRIEND_RELATIONSHIP_REQUEST_SENT = 4,
    SK_FRIEND_RELATIONSHIP_FRIEND = 8,
    SK_FRIEND_RELATIONSHIP_REQUEST_INITIATOR = 16,
    SK_FRIEND_RELATIONSHIP_FRIENDING = 32,
    SK_FRIEND_RELATIONSHIP_IGNORED = 64,
    SK_FRIEND_RELATIONSHIP_IGNORED_FRIEND = 128,
    SK_FRIEND_RELATIONSHIP_SUGGESTED = 256,
    SK_FRIEND_RELATIONSHIP_CHAT = 512,
    SK_FRIEND_RELATIONSHIP_ALL = SK_FRIEND_RELATIONSHIP_FRIEND | SK_FRIEND_RELATIONSHIP_REQUEST_RECEIVED | SK_FRIEND_RELATIONSHIP_REQUEST_SENT,
} sk_friend_relationship_t;

#ifdef __cplusplus
}
#endif

#endif // STEAMKIT_STEAM_HANDLERS_STEAM_FRIENDS_CALLBACKS_H
